### ISSUE TITLE
Centroids: Why does transform need to contain upper left corner?

### ISSUE THREAD

**Issue by tovogt** [CLIMADA-project/climada_python#100]
There are two places in `centr.py` where users are informed that the raster transform associated to a Centroids object needs to contain the upper left corner:
https://github.com/CLIMADA-project/climada_python/blob/dcef12ab075796baa80fa20d7cb392ab79e1c572/climada/hazard/centroids/centr.py#L86-L89
https://github.com/CLIMADA-project/climada_python/blob/dcef12ab075796baa80fa20d7cb392ab79e1c572/climada/hazard/centroids/centr.py#L133-L135
If not, the `check` method will fail. Can somebody explain why this is enforced?

Unfortunately, the function `from_base_grid` will generate a raster that does NOT contain the upper left corner:
https://github.com/CLIMADA-project/climada_python/blob/dcef12ab075796baa80fa20d7cb392ab79e1c572/climada/hazard/centroids/centr.py#L158-L159
I myself was not aware of this rule when implementing it:
https://github.com/CLIMADA-project/climada_python/blob/dcef12ab075796baa80fa20d7cb392ab79e1c572/climada/hazard/centroids/centr.py#L924
However, I'm reluctant to change the base grid (since it's a binary blob in the repository). Is it really necessary for the raster transform to have this property? Can't we go with arbitrary transforms?

**Comment by chahank** [comment]
To be honest, I have no idea. We should ask someone that maybe worked on this code: @gabrielaznar @ThomasRoosli @sameberenz ?

**Comment by sameberenz** [comment]
Unfortunately, I am not familiar with the centroids module from a developer's perspective and never encountered any problems initiating centroids.

**Comment by tovogt** [comment]
The check was added in 979b316748524ea3b9ee80d14a053ce88653e0c7. To me, it seems like this was for the convenience of the developers so that they don't have to think twice when doing stuff like plotting or indexing (especially when dealing with affine transforms).

The Exposure class contains a similar assumption:
https://github.com/CLIMADA-project/climada_python/blob/f1fd1c7006b619a86cd1ead774276a145c223a5c/climada/entity/exposures/base.py#L89-L92
https://github.com/CLIMADA-project/climada_python/blob/f1fd1c7006b619a86cd1ead774276a145c223a5c/climada/entity/exposures/base.py#L378-L383

I propose to change the ValueError in `check` to a warning that not everything might work as expected. But most functionality should be working just fine. If we stumble across problems, we can still fix them at a later stage. Plus, users have been warned. Here is my PR: #104

**Comment by chahank** [comment]
The question is at the same time: is there a reason for not having the top left corner fixed?

**Comment by tovogt** [comment]
For the end-user, it's always nicer when software is less restrictive about input data formats. Why would CLIMADA accept one GeoTIFF but not another one that looks very similar to the first and can be used with rasterio or GIS-software just the same?

Then, a lot of raster input/output is entirely based on rasterio and rasterio doesn't have this kind of restriction. My interpretation is that CLIMADA is doing things more complicated than necessary. For one example, in the function `Centroids.get_closest_point` CLIMADA is re-implementing something that rasterio is already able to do natively (this is changed by my PR: https://github.com/CLIMADA-project/climada_python/pull/104/files#diff-0ec37b2aaa4e9ad606f7859d74412d0af63acc0712fbc49baed2a7935487e4edL557-R560).

**Comment by chahank** [comment]
Thanks for the clarification! I agree with you that this decision seems arbitrary. However, since there is quite some legacy code, in particular graphs that are mostly not properly tested in our unitest, I am a bit hesitant in making the change and only use some nebulous warning that it might fail. This can quickly become a debugging nightmare. Probably a way to try to prevent this is to find out why @gabrielaznar included this in the code in the first place. Then it is possible to judge whether we can drop it easily or not.

What do you think?

**Comment by tovogt** [comment]
You say that you are hesitant in making the change. Which change?

**Comment by chahank** [comment]
Yes, I was referring to the PR, sorry for the confusion. I thought the PR is a direct answer to this "question" issue.

**Comment by peanutfun** [comment]
This has become obsolete with #787
