### ISSUE TITLE
test_data in new CONFIG

### ISSUE THREAD

**Issue by ThomasRoosli** [CLIMADA-project/climada_python#132]
I have a question regarding the use of the directories from config CONFIG in our tests.
If I run the file climada.hazard.test.test_storm_europe.py in Spyder by pressing the "Run file" button, the test fails because `CONFIG.hazard.test_data.dir()` resolves incorrectly to `WindowsPath('C:/shortpaths/GitHub/climada_python/climada/hazard/test/climada/hazard/test/data')`, which does not exist.

If I change the working directory to the main climada folder using:
`runfile('C:/shortpaths/GitHub/climada_python/climada/hazard/test/test_storm_europe.py', wdir='C:/shortpaths/GitHub/climada_python/')` then `CONFIG.hazard.test_data.dir()` resolves correctly to `WindowsPath('C:/shortpaths/GitHub/climada_python/climada/hazard/test/data')` and the test runs without error.

Is this the desired behaviour, i.e. I should only run tests from the main climada folder?

**Comment by emanuel-schmid** [comment]
Yes, currently the configuration for test is probably not yet ideal:

The config file where the top test directory is specified is most likely the one in `/path/to/git/climada_python/climada.config`

```
{
    ....
    "test_directory": "./climada",
    ...
}
```
Hence the top is pointing to the `climada` directory within the working directory. So if you run tests from anywhere below they may fail. Quick fix: change it to your installation directory, in your case:
```
{
    ...
    "test_directory": "C:/shortpaths/GitHub/climada_python/climada",
    ...
}
```

**Comment by ThomasRoosli** [comment]
Thanks, that worked fine, and solved the issue for me.
If there is a possibility to use `__file__` in config.py to assign the correct path for test_directory by default, that would be a nice addition in the future.
