### ISSUE TITLE
read_ibtracs_netcdf: why round first time to hours?

### ISSUE THREAD

**Issue by tovogt** [CLIMADA-project/climada_python#134]
In TCTracks.read_ibtracs_netcdf, the first time record is rounded to full hours:
https://github.com/CLIMADA-project/climada_python/blob/b4e84e44c60a6e56a7d7bbc747ffe2da7265ce3c/climada/hazard/tc_tracks.py#L414
 Why is this necessary? I remember that I once stumbled upon a problem with `equal_timestep` if the first time wasn't rounded to full hours, but I don't have time right now to verify this.

This issue is for discussing whether the rounding is necessary, harmless, avoidable or should at least be better documented.

**Comment by bguillod** [comment]
Do we know how often (how many tracks) experience first time steps that are not at a round hour?

**Comment by tovogt** [comment]
Regarding your question: Only 22 of the 13469 tracks in IBTrACS are affected by this.

Furthermore, I found the time to check this out: The problem is that `equal_timestep` produces NaNs for data sets that don't start at full hours. Here is an example (after manually removing the rounding in `read_ibtracs_netcdf`):
```
>>> tr = TCTracks()
>>> tr.read_ibtracs_netcdf(storm_id="1998335S12138")
>>> tr.data[0].central_pressure[:5].to_series()
time
1998-11-30 23:30:00    1007.0
1998-12-01 00:00:00    1006.0
1998-12-01 03:00:00    1005.0
1998-12-01 05:30:00    1004.0
1998-12-01 06:00:00    1004.0
Name: central_pressure, dtype: float32
>>> tr.equal_timestep(time_step_h=1)
>>> tr.data[0].central_pressure[:5].to_series()
time
1998-11-30 23:00:00            NaN
1998-12-01 00:00:00    1006.000000
1998-12-01 01:00:00    1005.666667
1998-12-01 02:00:00    1005.333333
1998-12-01 03:00:00    1005.000000
Name: central_pressure, dtype: float64
```
Note that the time steps are not aligned with the start time of the data set, but they are always aligned to 00:00:00 of the first day. So, if you specify `time_step_h=0.75`, the first time step will be at `23:15:00` because the resample bin from `23:15:00` until `00:00:00` is the first resample bin that overlaps the time index. In this case, this produces a NaN value at `23:00:00` which might lead to unwanted problems later on.

I think that this is actually a problem of the `equal_timestep` function and we shouldn't fix this kind of problem in the `read_ibtracs_netcdf` function.

Therefore, I propose to remove the rounding step in `read_ibtracs_netcdf` (this is not a big thing anyway since it only affects 22 tracks in IBTrACS). Then, I propose to always restrict the output of `equal_timestep` to times within the time bounds of the original track so that no additional NaNs are produced. Here is my little PR for that: #137

An alternative would be to enforce the start time of the interpolated track to be the start time of the original track. But I would stick with resample bins relative to `00:00:00` because that's a pandas convention.

**Comment by bguillod** [comment]
Thanks, I am in full agreement and approve the PR.
