### ISSUE TITLE
Saffir-Simpson Hurricane Wind Scale in kn

### ISSUE THREAD

**Issue by ThomasRoosli** [CLIMADA-project/climada_python#14]
A user just made me aware of the following issue:

In the TCTrack Module:

SAFFIR_SIM_CAT = [34, 64, 83, 96, 113, 135, 1000]

""" Saffir-Simpson Hurricane Wind Scale in kn"""

 

Should the value 135 be 137? This would make a category 5 storm start at 137 kn instead of 135 kn. This would allign better with https://www.nhc.noaa.gov/aboutsshws.php

Can somebody working with TC check and change if appropriate?

**Comment by sameberenz** [comment]
Thanks for pointing that out, Thomas!

I have double checked and changed the definition in TCTrack accordingly:

commit to develop: https://github.com/CLIMADA-project/climada_python/commit/2aacc1b3317d9ee89f58dbf159e15b13988d1cbe
