### ISSUE TITLE
tc_surge_geoclaw: irritating error about topo raster

### ISSUE THREAD

**Issue by wenlanzhang** [CLIMADA-project/climada_python#140]
Hi, I am new here, and I need some help with my work with Geoclaw. 

I run the 'climada_hazard_TCSurgeGeoClaw.ipynb', when I execute this line:
`haz = TCSurgeGeoClaw.from_tc_tracks(tracks, ZOS_PATH, TOPO_PATH)`

I have this error:
```
2021-02-10 10:54:43,610 - climada.hazard.tc_surge_geoclaw - INFO - Found Clawpack version 5.7.1 in /Users/zhangwenlan/climada/data/geoclaw/src/clawpack
2021-02-10 10:54:43,876 - climada.util.coordinates - INFO - Sampling from /Users/zhangwenlan/climada/data/GMT_intermediate_coast_distance_01d.tif
2021-02-10 10:54:45,687 - climada.hazard.tc_surge_geoclaw - INFO - Computing TC surge of 1 tracks on 492799 centroids.
2021-02-10 10:54:45,773 - climada.util.coordinates - INFO - Sampling from /Volumes/ZWL Backup Plus Drive/文件/Lidar/Lidar.tif.2021-02-10_05-12-30.tif
2021-02-10 10:54:45,997 - climada.hazard.tc_surge_geoclaw - INFO - Determine georegions and temporal periods of landfall events...

2021-02-10 10:54:47,051 - climada.hazard.tc_surge_geoclaw - INFO - Starting 1 runs of GeoClaw...
2021-02-10 10:54:47,055 - climada.hazard.tc_surge_geoclaw - INFO - Prepare GeoClaw to determine surge on 47819 centroids
2021-02-10 10:54:47,058 - climada.hazard.tc_surge_geoclaw - INFO - Init GeoClaw working directory in /Users/zhangwenlan/climada/data/geoclaw/runs/2021-02-10-10-54-45-2005296N16293/2005-10-23-00
2021-02-10 10:54:47,060 - climada.hazard.tc_surge_geoclaw - INFO - Found Clawpack version 5.7.1 in /Users/zhangwenlan/climada/data/geoclaw/src/clawpack
2021-02-10 10:54:47,093 - climada.hazard.tc_surge_geoclaw - INFO - GeoClaw resolution in arc-seconds: ['907.23', '453.61', '226.81', '113.40', '56.70', '18.90']
2021-02-10 10:54:47,100 - climada.hazard.tc_surge_geoclaw - INFO - Reading sea level data from /Volumes/ZWL Backup Plus Drive/文件/Lidar/global-reanalysis-phy-001-030-monthly_1612952174491.nc
2021-02-10 10:54:47,118 - climada.hazard.tc_surge_geoclaw - INFO - Sea level data available within bounds (-75.166664, 14.0, -66.0, 21.583334)
2021-02-10 10:54:47,120 - climada.hazard.tc_surge_geoclaw - INFO - Sea level data available within period from 1993-01 till 2019-06
2021-02-10 10:54:47,491 - climada.hazard.tc_surge_geoclaw - INFO - Load elevation data [360, (-75.17840576171875, 14.106157302856445, -66.10615539550781, 21.576919555664062)] from /Volumes/ZWL Backup Plus Drive/文件/Lidar/Lidar.tif.2021-02-10_05-12-30.tif
---------------------------------------------------------------------------
CPLE_IllegalArgError                      Traceback (most recent call last)
rasterio/_io.pyx in rasterio._io.DatasetReaderBase._read()

rasterio/shim_rasterioex.pxi in rasterio._shim.io_multi_band()

rasterio/_err.pyx in rasterio._err.exc_wrap_int()

CPLE_IllegalArgError: /Volumes/ZWL Backup Plus Drive/文件/Lidar/Lidar.tif.2021-02-10_05-12-30.tif: Access window out of range in RasterIO().  Requested (0,2323) of size 1x1 on raster of 1861x2323.

During handling of the above exception, another exception occurred:

RasterioIOError                           Traceback (most recent call last)
<ipython-input-26-7edddb1564d1> in <module>
----> 1 haz = TCSurgeGeoClaw.from_tc_tracks(tracks, ZOS_PATH, TOPO_PATH)

~/miniconda3/climada_python-feature-tc_surge_geoclaw/climada/hazard/tc_surge_geoclaw.py in from_tc_tracks(tracks, zos_path, topo_path, centroids, description, gauges, node_max_dist_deg, inland_max_dist_km, offshore_max_dist_km, max_latitude, pool)
    149                                           node_max_dist_deg=node_max_dist_deg,
    150                                           gauges=gauges, pool=pool)
--> 151              for t in tracks.data])
    152         TropCyclone.frequency_from_tracks(haz, tracks.data)
    153         haz.tag.description = description

~/miniconda3/climada_python-feature-tc_surge_geoclaw/climada/hazard/tc_surge_geoclaw.py in <listcomp>(.0)
    149                                           node_max_dist_deg=node_max_dist_deg,
    150                                           gauges=gauges, pool=pool)
--> 151              for t in tracks.data])
    152         TropCyclone.frequency_from_tracks(haz, tracks.data)
    153         haz.tag.description = description

~/miniconda3/climada_python-feature-tc_surge_geoclaw/climada/hazard/tc_surge_geoclaw.py in from_xr_track(track, centroids, coastal_idx, zos_path, topo_path, node_max_dist_deg, gauges, pool)
    189         intensity[coastal_idx], gauge_data = geoclaw_surge_from_track(
    190             track, coastal_centroids, zos_path, topo_path,
--> 191             gauges=gauges, pool=pool, node_max_dist_deg=node_max_dist_deg)
    192 
    193         new_haz = TCSurgeGeoClaw()

~/miniconda3/climada_python-feature-tc_surge_geoclaw/climada/hazard/tc_surge_geoclaw.py in geoclaw_surge_from_track(track, centroids, zos_path, topo_path, gauges, pool, node_max_dist_deg)
    375                                          event['period'][0], event,
    376                                          track_centr[event['centroid_mask']], zos_path,
--> 377                                          topo_path, gauges=gauges))
    378 
    379         if pool is not None:

~/miniconda3/climada_python-feature-tc_surge_geoclaw/climada/hazard/tc_surge_geoclaw.py in __init__(self, base_dir, track, time_offset, areas, centroids, zos_path, topo_path, gauges)
    475 
    476         # write rundata
--> 477         self.write_rundata()
    478 
    479 

~/miniconda3/climada_python-feature-tc_surge_geoclaw/climada/hazard/tc_surge_geoclaw.py in write_rundata(self)
    576         self.set_rundata_claw()
    577         self.set_rundata_amr()
--> 578         self.set_rundata_geo()
    579         self.set_rundata_fgmax()
    580         self.set_rundata_storm()

~/miniconda3/climada_python-feature-tc_surge_geoclaw/climada/hazard/tc_surge_geoclaw.py in set_rundata_geo(self)
    678         dems_for_plot = []
    679         for res_as, bounds in zip(resolutions, areas):
--> 680             bounds, topo = load_topography(self.topo_path, bounds, res_as)
    681             if 0 in topo.Z.shape:
    682                 LOGGER.warning("Area is ignored because it is too small.")

~/miniconda3/climada_python-feature-tc_surge_geoclaw/climada/hazard/tc_surge_geoclaw.py in load_topography(path, bounds, res_as)
    956     LOGGER.info("Load elevation data [%s, %s] from %s", res_as, bounds, path)
    957     res = res_as / (60 * 60)
--> 958     zvalues, transform = coord_util.read_raster_bounds(path, bounds, res=res, bands=[1])
    959     zvalues = zvalues[0]
    960     xres, _, xmin, _, yres, ymin = transform[:6]

~/miniconda3/climada_python-feature-tc_surge_geoclaw/climada/util/coordinates.py in read_raster_bounds(path, bounds, res, bands)
   1314         if bounds[2] <= 180:
   1315             # data = src.read(bands, out_shape=shape, window=window,
-> 1316             data = src.read(bands, out_shape=shape-1, window=window-1,
   1317                             resampling=resampling-1)
   1318         else:

rasterio/_io.pyx in rasterio._io.DatasetReaderBase.read()

rasterio/_io.pyx in rasterio._io.DatasetReaderBase._read()

RasterioIOError: Read or write failed. /Volumes/ZWL Backup Plus Drive/文件/Lidar/Lidar.tif.2021-02-10_05-12-30.tif: Access window out of range in RasterIO().  Requested (0,2323) of size 1x1 on raster of 1861x2323.
```

I want to know how should I change the data I have or should I edit some code here.
I would really appreciate your comments/suggestions.

Regards,
Wenlan

**Comment by tovogt** [comment]
I guess that your topography raster isn't covering a sufficiently large region. Can you provide the output of `gdalinfo /Volumes/ZWL Backup Plus Drive/文件/Lidar/Lidar.tif.2021-02-10_05-12-30.tif`, please?

**Comment by wenlanzhang** [comment]
> The tc_surge_geoclaw feature is not yet released (that's why it's only in an unofficial branch). I'm the only person currently working on it. At the current stage, I can't guarantee that it will work for your input data or that it will always provide you with useful error output.
> 
> I guess that your topography raster isn't covering a sufficiently large region. Can you provide the output of `gdalinfo /Volumes/ZWL Backup Plus Drive/文件/Lidar/Lidar.tif.2021-02-10_05-12-30.tif`, please?

Great thanks for your help!
This is the output. (I just changed the name of my drive)


`Driver: GTiff/GeoTIFF
Files: /Volumes/ZWL_Drive/File/Lidar/Lidar.tif.2021-02-10_05-12-30.tif
Size is 1861, 2323
Coordinate System is:
PROJCRS["WGS 84 / UTM zone 18N",
    BASEGEOGCRS["WGS 84",
        DATUM["World Geodetic System 1984",
            ELLIPSOID["WGS 84",6378137,298.257223563,
                LENGTHUNIT["metre",1]]],
        PRIMEM["Greenwich",0,
            ANGLEUNIT["degree",0.0174532925199433]],
        ID["EPSG",4326]],
    CONVERSION["UTM zone 18N",
        METHOD["Transverse Mercator",
            ID["EPSG",9807]],
        PARAMETER["Latitude of natural origin",0,
            ANGLEUNIT["degree",0.0174532925199433],
            ID["EPSG",8801]],
        PARAMETER["Longitude of natural origin",-75,
            ANGLEUNIT["degree",0.0174532925199433],
            ID["EPSG",8802]],
        PARAMETER["Scale factor at natural origin",0.9996,
            SCALEUNIT["unity",1],
            ID["EPSG",8805]],
        PARAMETER["False easting",500000,
            LENGTHUNIT["metre",1],
            ID["EPSG",8806]],
        PARAMETER["False northing",0,
            LENGTHUNIT["metre",1],
            ID["EPSG",8807]]],
    CS[Cartesian,2],
        AXIS["(E)",east,
            ORDER[1],
            LENGTHUNIT["metre",1]],
        AXIS["(N)",north,
            ORDER[2],
            LENGTHUNIT["metre",1]],
    USAGE[
        SCOPE["unknown"],
        AREA["World - N hemisphere - 78°W to 72°W - by country"],
        BBOX[0,-78,84,-72]],
    ID["EPSG",32618]]
Data axis to CRS axis mapping: 1,2
Origin = (741266.144421043340117,2118702.452704703435302)
Pixel Size = (1.499920666749399,-1.499756303355074)
Metadata:
  AREA_OR_POINT=Area
  TIFFTAG_RESOLUTIONUNIT=1 (unitless)
  TIFFTAG_XRESOLUTION=1
  TIFFTAG_YRESOLUTION=1
Image Structure Metadata:
  INTERLEAVE=PIXEL
Corner Coordinates:
Upper Left  (  741266.144, 2118702.453) ( 72d42'22.11"W, 19d 8'50.01"N)
Lower Left  (  741266.144, 2115218.519) ( 72d42'23.67"W, 19d 6'56.75"N)
Upper Right (  744057.497, 2118702.453) ( 72d40'46.63"W, 19d 8'48.81"N)
Lower Right (  744057.497, 2115218.519) ( 72d40'48.21"W, 19d 6'55.56"N)
Center      (  742661.821, 2116960.486) ( 72d41'35.16"W, 19d 7'52.79"N)
Band 1 Block=1861x1 Type=Int32, ColorInterp=Gray
  NoData Value=0
Band 2 Block=1861x1 Type=Int32, ColorInterp=Alpha
  NoData Value=0
`

**Comment by tovogt** [comment]
As suspected, your topo data only covers a very small box close to 72°W / 19°N while your storm afffects a much larger region `(lon_min=-75.18, lat_min=14.11, lon_max=-66.11, lat_max=21.58)` (according to your log output above). Make sure that you provide a topo data set that is large enough. In particular, your topo data has to include ocean bathymetry information. If you want to combine topography data from different source make sure to merge them into a single raster file, e.g. using GDAL tools.

**Comment by wenlanzhang** [comment]
> As suspected, your topo data only covers a very small box close to 72°W / 19°N while your storm afffects a much larger region `(lon_min=-75.18, lat_min=14.11, lon_max=-66.11, lat_max=21.58)` (according to your log output above). Make sure that you provide a topo data set that is large enough. In particular, your topo data has to include ocean bathymetry information. If you want to combine topography data from several sources make sure to merge them into a single raster file, e.g. using GDAL tools (gdal_translate, gdalbuildvrt etc.)

Thank you very much for your answer and your patience! I will get large data!
