### ISSUE TITLE
Control fig and ax when using CLIMADA's plot functions

### ISSUE THREAD

**Issue by tovogt** [CLIMADA-project/climada_python#154]
@chahank hijacked issue #153 (https://github.com/CLIMADA-project/climada_python/issues/153#issuecomment-782849789) to report on the following problem:

> While doing some plotting, I realized that since CLIMADA functions only return the axis and not the figure, one does not have access to several plot handles because the axis are very directly linked to their figure. While before the change it was possible to do:
> ```
> fig, ax = u_plot.make_map()
> impact.plot_raster_eai_exposure(axis=ax)
> ax.set_title('my custom title')
> fig.save_fig('filename')
> ```
> this is not possible anymore, as the projection returned by u_plot.make_map() will be wrong.

Then, following a suggestion by @gabrielaznar:

> I just tried [to use `ax.get_figure()` to obtain the figure], but unfortunately 
> ```
> ax = imp.plot_raster_eai_exposure(label=xlabel)
> ax.set_title('my_title')
> fig = ax.get_figure()
> fig.savefig("my_fig.pn")
> ```
> does not work as intended. The figure seems not to be sized the same as the ax. Here is an example (most of the image is white):
> 
> ![Imp_FJI_year2020_rcp26](https://user-images.githubusercontent.com/7040169/108636772-c2a60800-7487-11eb-8bc2-dc14acd4ee9e.png)

After that, there was another suggestion by @gabrielaznar 

> I had this issue when saving, related to the savefig command. It usually worked using the option bbox_inches=‘tight’ of savefig, and also adding format= (with ‘pdf’ worked fine). I would give it a try!

This issue is to deal with @chahank's question of how to control figure and axes when using CLIMADA's plot functions.

**Comment by tovogt** [comment]
@chahank I tried to reproduce your issue with your example in https://github.com/CLIMADA-project/climada_python/pull/145#discussion_r576436680, and used @gabrielaznar suggested fix:
```
import numpy as np
import pandas as pd
from scipy import sparse as sparse
from climada.entity import Exposures, IFTropCyclone, ImpactFuncSet
from climada.hazard import Hazard
from climada.engine import Impact
from climada.util.plot import make_map

lon_list = np.append(np.arange(-160, -185, -1), np.arange(170, 185, 1))
lat_list = np.arange(-10, 10, 1)

df_exp = pd.DataFrame()
df_exp['latitude'] = np.repeat(lat_list, len(lon_list))
df_exp['longitude'] = np.repeat(lon_list, len(lat_list))
df_exp['value'] = 100
df_exp['if_TC'] = 1 
exp = Exposures(df_exp)
exp.set_geometry_points()
exp.check()

n_cen = len(exp.gdf.longitude) # number of centroids
n_ev = 10 # number of events
haz = Hazard('TC')
haz.centroids.set_lat_lon(exp.gdf.latitude, exp.gdf.longitude) # default crs used
haz.intensity = sparse.csr_matrix(np.random.random((n_ev, n_cen))*100)
haz.units = 'm'
haz.event_id = np.arange(n_ev, dtype=int)
haz.event_name = ['ev_12', 'ev_21', 'Maria', 'ev_35', 'Irma', 'ev_16', 'ev_15', 'Edgar', 'ev_1', 'ev_9']
haz.date = [721166, 734447, 734447, 734447, 721167, 721166, 721167, 721200, 721166, 721166]
haz.orig = np.zeros(n_ev, bool)
haz.frequency = np.ones(n_ev)/n_ev
haz.fraction = haz.intensity.copy()
haz.fraction.data.fill(1)
haz.check()

exp.assign_centroids(haz)

impf = IFTropCyclone()
impf.set_emanuel_usa()
impf_set= ImpactFuncSet()
impf_set.append(impf)

imp = Impact()
imp.calc(exp, impf_set, haz)

ax = imp.plot_raster_eai_exposure()
ax.set_title('my_title')
fig = ax.get_figure()
fig.savefig("my_fig.png", bbox_inches='tight')
```
The result looks fine to me:
![image](https://user-images.githubusercontent.com/57705593/108689148-038a3500-74f9-11eb-8039-db3036760a06.png)

Does this solve your issue? Or should we also support more complex figure/axes control? What exactly is the usecase you are trying to tackle? A user that wants to compile in one figure the plots generated by different plot functions? Force the plot function to use the provided axes even if the projection is not optimal and the result would look suboptimal?

**Comment by chahank** [comment]
Just a quick answer (a more detailed answer to your good questions will come later on): for me the option `bbox_inches='tight'` does not solve the issue (also not adding `format=pdf` or png).

**Comment by gabrielaznar** [comment]
Hi, just a last use case that was thought already in CLIMADA. Not sure if it helps you @chahank. 

fig, ax = climada.util.plot.make_map(project=what_you_want)
any_plot_function_climada(axis=ax)

should work.
Best wishes!

**Comment by chahank** [comment]
Dear @gabrielaznar, 
I am familiar with the `util.plot_make_map()` function. However, this will not work anymore with the update made to the handling of the antimeridian and the projections discussed in #153 (pull request #145).

**Comment by chahank** [comment]
@tovogt The only real difference I can see between your script and mine is that I save the impact and load.

```
imp = Impact()
imp.calc(exp, impf, haz)
imp.save_csv('file.csv')
imp2 = Impact()
imp2.read_csv('file.csv')
ax = imp2.plot_raster_eai_exposure(label='Dollars')
ax.set_title('my fancy title')
fig = ax.get_figure()
fig.savefig('plot.png', bbox_inches='tight')
```
Can I send you the impact data I am using to see whether the error is reproduced with your code?

Also, to be sure: which branch of CLIMADA are you using?

**Comment by tovogt** [comment]
I'm testing this on the most recent develop branch. And writing and reading the impacts doesn't change the result for me.

So, do you say that you get a different result when executing the exact same code that I posted above?

**Comment by chahank** [comment]
I finally found the time to execute the code you posted. The result is the same as when I was trying to plot my data: the full globe is shown. Maybe it is because I am using a different conda environment. I tested with the environment built from the release 1.5.1 and from the latest requirement file on the develop branch. Both failed. Any further idea what I could test?

![my_fig](https://user-images.githubusercontent.com/7040169/110338273-1a677600-8027-11eb-9227-c1af6a8c99dc.png)

**Comment by tovogt** [comment]
Okay, I notice now that I tested this in a conda environment with cartopy 0.18. I didn't notice the roll-back to 0.17 in October 2020: 7b19d392b263dd6e16cc652166537b3c0b875232 The problem you describe is a bug of cartopy 0.17 that has been fixed a year ago: https://github.com/SciTools/cartopy/issues/1446

**Comment by chahank** [comment]
Thanks for the quick problem finding. We have an issue here, since according to #161 we cannot upate to 0.18.
