### ISSUE TITLE
Update to geopandas 0.9

### ISSUE THREAD

**Issue by emanuel-schmid** [CLIMADA-project/climada_python#158]
Currently updating to geopandas 0.9 fails. 
One of the reasons is the necessity to have a `geometry` column in a `GeoDataFrame` before a `crs` can be assigned to it.

Therefore it is required to refactor `Exposures` (and any other module using `GeoDataFrames`) in a way that `crs` is assigned only with an existing `geometry` column.

**Comment by tovogt** [comment]
Fixed by #241
