### ISSUE TITLE
Conda Installation fails on Ubuntu due to missing libspatialindex library

### ISSUE THREAD

**Issue by emanuel-schmid** [CLIMADA-project/climada_python#159]
With the updated environment file of f0adbe7920ff90ae68f9ebce5e99dd976c9bd7c7 `make install_test` leads to `AttributeError: python: undefined symbol: Error_GetLastErrorNum`.

One workaround is to run `sudo apt install libspatialindex-dev`.

Perhaps there is a better solution that does not require messing with the core system or being sudo.

In any case, the steps to take must be documented in the installation instructions.

**Comment by tovogt** [comment]
There seems to be a bug in conda's Python 3.8.8 when looking up shared libraries. It will look in `$CONDA_PREFIX/lib/spatialindex_c`, but not in `$CONDA_PREFIX/lib/libspatialindex_c.so`. So, if you create a link `ln -s $CONDA_PREFIX/lib/libspatialindex_c.so $CONDA_PREFIX/lib/spatialindex_c`, the error will go away.

This error does NOT apply to any other version of Python from conda, I tested with 3.8.5 and 3.9.x. Furthermore, it also does NOT apply to the 3.8.8 build from conda-forge, i.e. installed using `conda install -c conda-forge python=3.8.8=hffdb5ce_0_cpython`.

**Comment by emanuel-schmid** [comment]
Thanks for looking into it!

With conda-forge as the primary channel given in `requirements/env_climada.yml` this problem does not occur anymore.

This was (re-)introduced with commit 95de399.
