### ISSUE TITLE
Update to cartopy 0.18 and matplotlib 3.3 inhibited

### ISSUE THREAD

**Issue by emanuel-schmid** [CLIMADA-project/climada_python#161]
The libraries cartopy (version 0.17) and matplotlib (3.2) cannot be upgraded to 0.18 and 3.3 respectively.
One method that fails after the update is `Exposures.plot_hexbin()`. Quite likely there are more.
The underlying problem must be identified and eventually fixed.

**Comment by tovogt** [comment]
Can you give an example of how Exposures.plot_hexbin fails after the update?

**Comment by emanuel-schmid** [comment]
@tovogt : No, I can't. The failure under cartopy 0.18 was seemingly just an artefact that came from a broken matplotlib installation.
There is definitely an issue with matplotlib 3.3 though. plot_hexbin() does not work under windows and the example would be the Exposures tutorial, cell 21.

**Comment by tovogt** [comment]
Would you please try to reproduce your problem with cell 21 using the most recent state of the develop branch? I apply a very small fix in commit https://github.com/CLIMADA-project/climada_python/commit/a67c65bae3e81a1b8e3e2e4ea471a133300526f8

**Comment by emanuel-schmid** [comment]
👍 Yes, that did the trick. Thanks a lot @tovogt !
