### ISSUE TITLE
Exposure.assign_centroids assumes that hazard.centroids.coord is in 'float64'

### ISSUE THREAD

**Issue by ThomasRoosli** [CLIMADA-project/climada_python#175]
In assign_centroids, the code assumes that the variable `hazard.centroids.coord` (a `numpy ndarray`) is of `dtype float64`. Now I fear, that if that is not the case there can either be an error or even a misinterpretation in this line:
`haz_coord_view = haz_coord.view(dtype='float64,float64').reshape(-1)`
[Link to code](https://github.com/CLIMADA-project/climada_python/blob/abfbe1b7124a8e49bda565261c9a358ce25d78ef/climada/entity/exposures/base.py#L312)

My solution would be make sure, that haz_coord is actually float64 beforehand, with:
`haz_coord = haz_coord.astype('float64')`

But I would appreciate if somebody who looked into that code recently could quickly confirm, if that is a good idea or not.

PS:
I just experienced the following error because `hazard.centroids.coord.dtype` was `float32`:
`File "C:\shortpaths\GitHub\climada_python\climada\entity\exposures\base.py", line 312, in assign_centroids
 haz_coord_view = haz_coord.view(dtype='float64,float64').reshape(-1)
ValueError: When changing to a larger dtype, its size must be a divisor of the total size in bytes of the last axis of the array.`

**Comment by tovogt** [comment]
Thanks, well spotted! You solution is perfect: `haz_coord = haz_coord.astype('float64')`. Create a PR and I will be happy to confirm. Would be good to have a regression test for this.
