### ISSUE TITLE
LitPop crashing when using WB data (i.e. most of times)

### ISSUE THREAD

**Issue by aleeciu** [CLIMADA-project/climada_python#178]
I was about to write the tutorial for a new module and I realized litpop is crashing and, as it is a very popular and widely used module I think it requires some attention. I have tried several countries, if you e.g. use Japan and do something like:
`
exp_lp = LitPop()
exp_lp.set_country(['JPN'], res_km=10)
`
it should crash giving an error:

> RemoteDataError: Unable to read URL: https://api.worldbank.org/v2/countries/JPN/indicators/NY.GDP.MKTP.CD?date=1960%3A2030&per_page=25000&format=json

and the URL is indeed inaccessible - it can be a temporary issue but if the WB changed its API website in some ways that can be a big deal for this module.

I think it is good if someone can:
1. check if you get the same
2. have a clue on how to fix it?

**Comment by aleeciu** [comment]
Link works now and so does LitPop; I leave this issue open only to ask wether it could perhaps be smart to have this data locally, to reduce dependency on such issues....

**Comment by ChrisFairless** [comment]
hopefully the Data API will eventually help with this, with LitPop querying a pre-calculated database for the most common queries
