### ISSUE TITLE
Problem to install climada

### ISSUE THREAD

**Issue by CarlBethuel** [CLIMADA-project/climada_python#197]
Hello I would like to use Google earth engine with python and the scripts use the line : `from climada.util import DEMO_DIR` I work on a virutel environment created for this project in python 3.7 and I installed climada_python with conda by cloning from git and installing the setup.py file. Then I install the add-ons (fiona, Pint,...) and when everything is done and I run the line : `from climada.util import DEMO_DIR`, I get : 
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\carlb\AppData\Local\Continuum\anaconda3\envs\env\lib\site-packages\climada-2.0.0-py3.7.egg\climada\__init__.py", line 25, in <module>
    from .util.constants import *
  File "C:\Users\carlb\AppData\Local\Continuum\anaconda3\envs\env\lib\site-packages\climada-2.0.0-py3.7.egg\climada\util\__init__.py", line 25, in <module>
    from .constants import *
  File "C:\Users\carlb\AppData\Local\Continuum\anaconda3\envs\env\lib\site-packages\climada-2.0.0-py3.7.egg\climada\util\constants.py", line 52, in <module>
    SYSTEM_DIR = CONFIG.local_data.system.dir(create=False)
AttributeError: 'Config' object has no attribute 'local_data'
```

So I'm blocked to use GEE with python and I don't know how to solve the problem. Any help ? Thanks.

**Comment by emanuel-schmid** [comment]
Hi. Though your installation was slightly different from the one proposed here: https://climada-python.readthedocs.io/en/latest/guide/Guide_Installation.html, I can't see why it shouldn't work.
Can you please post the output of the following:
```
from climada.util.config import SOURCE_DIR
SOURCE_DIR, [x.name for x in SOURCE_DIR.iterdir()]
```
?

**Comment by CarlBethuel** [comment]
Thanks for your answer. I run the code and I get : 
`(WindowsPath('C:/Users/carlb/AppData/Local/Continuum/anaconda3/envs/env/lib/site-packages/climada-2.0.0-py3.7.egg'), ['climada', 'data', 'EGG-INFO'])`

**Comment by emanuel-schmid** [comment]
Many thanks. That's already helpful. It pointed us to a [bug](https://github.com/CLIMADA-project/climada_python/issues/200) in `setup.py`. It will be fixed soon but until then the workaround is to copy the [climada.conf](https://github.com/CLIMADA-project/climada_python/blob/main/climada/conf/climada.conf) file from the repository to `C:\Users\carlb\AppData\Local\Continuum\anaconda3\envs\env\lib\site-packages\climada-2.0.0-py3.7.egg\climada\conf\climada.conf`. Once that's done you should come further.

**Comment by CarlBethuel** [comment]
Nice, it's working ! Thanks a lot ! When the bug will be fixe, can  install climada like I did ?

**Comment by emanuel-schmid** [comment]
Yes, that's the plan. 😃
