### ISSUE TITLE
Uncertainty Tutorial Failure

### ISSUE THREAD

**Issue by emanuel-schmid** [CLIMADA-project/climada_python#198]
error message:

notebook climada_engine_uncertainty.ipynb cell 18 failed with <class 'AttributeError'> 'UncVar' object has no attribute 'evaluate' 

Is this possibly due to a recent update in the module?

**Comment by chahank** [comment]
Yes, thanks for noticing. This was removed at the last minute from the module as it is redundant. Hence, the whole `UncVar.evaluate` can be removed from the tutorial.

**Comment by chahank** [comment]
Fixed in acf727f8a7f33b6369acdcff4539fa5f2001f8dd

**Comment by chahank** [comment]
This is solved right @emanuel-schmid ?
