### ISSUE TITLE
Pillow Security Vulnerability

### ISSUE THREAD

**Issue by emanuel-schmid** [CLIMADA-project/climada_python#20]
... found a vulnerable dependency in a repository you have security alert access to.
| CLIMADA-project/climada_python
Known moderate severity     security vulnerability detected in Pillow < 6.2.2 defined in setup.py.

**Comment by emanuel-schmid** [comment]
setup.py end climada_env list dependency pillow==6.2.2 since https://github.com/CLIMADA-project/climada_python/commit/61fc322d9ac960cdeac80e886670399d47add358.
But cartopy 0.17.0 requires pillow==6.2.1 and both versions are loaded into the conda environment
(confirmed under linux).

**Comment by emanuel-schmid** [comment]
The real solution is more or less in the hands of cartopy, a library that cannot be installed but through conda, where 0.17.0 is the highest version number at the moment.

**Comment by tovogt** [comment]
Does 245192bfee99c109d72cd0d725f08e4b72624bff solve this issue?
