### ISSUE TITLE
Out Of memory Rendering - Tutorial Windstorm

### ISSUE THREAD

**Issue by geohazard89** [CLIMADA-project/climada_python#218]
I have a memory issue rendering the tutorial of WindStorm - WISC. 

021-04-25 00:04:40,698 - climada.hazard.centroids.centr - INFO - Convert centroids to GeoSeries of Point shapes.
C:\Users\popos\anaconda3\envs\climada_env\lib\site-packages\pyproj\crs\crs.py:53: FutureWarning: '+init=<authority>:<code>' syntax is deprecated. '<authority>:<code>' is the preferred initialization method. When making the change, be mindful of axis order changes: https://pyproj4.github.io/pyproj/stable/gotchas.html#axis-order-changes-in-proj-6
  return _prepare_from_string(" ".join(pjargs))
2021-04-25 00:04:41,502 - climada.util.coordinates - INFO - Setting region_id 9944 points.
2021-04-25 00:04:42,710 - climada.hazard.storm_europe - INFO - Commencing probabilistic calculations
2021-04-25 00:04:42,803 - climada.hazard.storm_europe - INFO - Generating new StormEurope instance
C:\Users\popos\Desktop\Trabajo\climada_python-main\climada\util\coordinates.py:1065: UserWarning: Geometry is in a geographic CRS. Results from 'area' are likely incorrect. Use 'GeoSeries.to_crs()' to re-project geometries to a projected CRS before this operation.

  countries['area'] = countries.geometry.area
Wall time: 2.58 s
<GeoAxesSubplot:title={'center':'WS max intensity at each point'}>
---------------------------------------------------------------------------
MemoryError                               Traceback (most recent call last)
~\anaconda3\envs\climada_env\lib\site-packages\IPython\core\formatters.py in __call__(self, obj)
    339                 pass
    340             else:
--> 341                 return printer(obj)
    342             # Finally look for special method names
    343             method = get_real_method(obj, self.print_method)

~\anaconda3\envs\climada_env\lib\site-packages\IPython\core\pylabtools.py in <lambda>(fig)
    246 
    247     if 'png' in formats:
--> 248         png_formatter.for_type(Figure, lambda fig: print_figure(fig, 'png', **kwargs))
    249     if 'retina' in formats or 'png2x' in formats:
    250         png_formatter.for_type(Figure, lambda fig: retina_figure(fig, **kwargs))

~\anaconda3\envs\climada_env\lib\site-packages\IPython\core\pylabtools.py in print_figure(fig, fmt, bbox_inches, **kwargs)
    130         FigureCanvasBase(fig)
    131 
--> 132     fig.canvas.print_figure(bytes_io, **kw)
    133     data = bytes_io.getvalue()
    134     if fmt == 'svg':

~\anaconda3\envs\climada_env\lib\site-packages\matplotlib\backend_bases.py in print_figure(self, filename, dpi, facecolor, edgecolor, orientation, format, bbox_inches, pad_inches, bbox_extra_artists, backend, **kwargs)
   2253                 # force the figure dpi to 72), so we need to set it again here.
   2254                 with cbook._setattr_cm(self.figure, dpi=dpi):
-> 2255                     result = print_method(
   2256                         filename,
   2257                         facecolor=facecolor,

~\anaconda3\envs\climada_env\lib\site-packages\matplotlib\backend_bases.py in wrapper(*args, **kwargs)
   1667             kwargs.pop(arg)
   1668 
-> 1669         return func(*args, **kwargs)
   1670 
   1671     return wrapper

~\anaconda3\envs\climada_env\lib\site-packages\matplotlib\backends\backend_agg.py in print_png(self, filename_or_obj, metadata, pil_kwargs, *args)
    506             *metadata*, including the default 'Software' key.
    507         """
--> 508         FigureCanvasAgg.draw(self)
    509         mpl.image.imsave(
    510             filename_or_obj, self.buffer_rgba(), format="png", origin="upper",

~\anaconda3\envs\climada_env\lib\site-packages\matplotlib\backends\backend_agg.py in draw(self)
    399     def draw(self):
    400         # docstring inherited
--> 401         self.renderer = self.get_renderer(cleared=True)
    402         # Acquire a lock on the shared font cache.
    403         with RendererAgg.lock, \

~\anaconda3\envs\climada_env\lib\site-packages\matplotlib\backends\backend_agg.py in get_renderer(self, cleared)
    415                           and getattr(self, "_lastKey", None) == key)
    416         if not reuse_renderer:
--> 417             self.renderer = RendererAgg(w, h, self.figure.dpi)
    418             self._lastKey = key
    419         elif cleared:

~\anaconda3\envs\climada_env\lib\site-packages\matplotlib\backends\backend_agg.py in __init__(self, width, height, dpi)
     89         self.width = width
     90         self.height = height
---> 91         self._renderer = _RendererAgg(int(width), int(height), dpi)
     92         self._filter_renderers = []
     93 

MemoryError: In RendererAgg: Out of memory

<Figure size 648x936 with 2 Axes>

**Comment by ThomasRoosli** [comment]
Hi geohazard89,
I could not reproduce the issue on my computer. I assume you are talking about the following file: [https://github.com/CLIMADA-project/climada_python/blob/main/doc/tutorial/climada_hazard_StormEurope.ipynb](url). I am using the current main branch release 2.1.1 and on a Windows machine. Also the test on jenkins do not show any failure for that notebook: [https://ied-wcr-jenkins.ethz.ch/job/climada_notebooks/](url).
Can you provide us with more information, what branch you are using, on what operating system you are running CLIMADA and if you have tried to setup the environment from scratch exactly as described in this installation guide: [https://climada-python.readthedocs.io/en/latest/guide/Guide_Installation.html](url)?

**Comment by geohazard89** [comment]
Hi Thomas, 

I am using the current main branch release, Installed from scratch using .yml with Anaconda in Windows 10. 

I have run all the checks from the install and everything is OK, unless API download of IBTRACS it seems download link is down. 

I have moved the Tutorials to the main folder because they were not working from doc/tutorial. 

I am having the same error as yesterday. Maybe, I am running the scripts from the wrong folder? 
Error 1 & 2, tutorial windstorm, error 3 folder tree, error 4 wrong plot from Spyder - 

What can I do? 

Thank you a lot


![Spyder](https://user-images.githubusercontent.com/63537357/116000436-73e42e00-a5f0-11eb-88ca-252fe7fe004a.PNG)
 



![error1](https://user-images.githubusercontent.com/63537357/115999974-9412ed80-a5ee-11eb-8537-df7872ee2bfd.PNG)

![error2](https://user-images.githubusercontent.com/63537357/115999997-b0af2580-a5ee-11eb-87ac-1d9e66121e9b.PNG)

![error3](https://user-images.githubusercontent.com/63537357/116000000-b3aa1600-a5ee-11eb-87ed-a0ab7c8a839a.PNG)

**Comment by ThomasRoosli** [comment]
Hi again

The MemoryError is no longer showing up in the output that you have attached to your last message. So reinstalling the environment seems to have fixed the MemoryError issue. That is already good progress.
Now I think you there is another problem with the plotting. I assume that when you installed spyder and jupyter notebook within the newly created environment, there was a problem installing the required backend of matplotlib.
Can you: 
1) run the line `plt.get_backend()` within the python script that you showed in spyder and post the output here?
2) try to run any other CLIMADA tutorial that produces plots in jupyter notebook and also run the that code in spyder and report back if the plotting worked in those other tutorials?

If plotting is not working in general, you can try to fix that with installing the package "tk" in climada_env using anaconda and adding 
```
import matplotlib
matplotlib.use('TKAgg')
```
to the very beginning of your script in spyder.

**Comment by emanuel-schmid** [comment]
can this issue be closed?
