### ISSUE TITLE
util.files_handler.get_file_names with wildcards fails on Windows

### ISSUE THREAD

**Issue by emanuel-schmid** [CLIMADA-project/climada_python#225]
Underlying reason is that calling methods on `Path('string with *')` will raise an Exception about path not being valid.

Test: `climada.util.test.test_files.TestGetFileNames.test_globbing`

**Comment by tovogt** [comment]
Note that this has been fixed upstream for Python 3.8 and 3.9 in https://bugs.python.org/issue35306

A workaround would be to have a try-except block where the WinError code is checked:
```
    file_list = []
    for pattern in pattern_list:
        try:
            if pattern.exists():
                file_list.append(...)
                continue
            elif pattern.is_dir():
                file_list.extend(...)
                continue
        except OSError as err:
            # check for ERROR_INVALID_NAME on windows
            if not getattr(err, "winerror", None) == 123:
                raise
        # glob pattern
        file_list.extend(...)
```
I don't want to assign myself to this though, since I don't have any Windows system for testing.
