### ISSUE TITLE
The rainfield result of TCRain() changes if the time_step_h of the TCTracks() is different

### ISSUE THREAD

**Issue by dhli003** [CLIMADA-project/climada_python#235]
I used the TCRain().set_from_tracks(tracks, centroids) to calculate the intensity of the rainfall for tropical cyclone events. 
If I set TCTracks().equal_timestep(time_step_h=0.5) then the rainfall intensity for every single event is twice as large as that with time_step_h=1. 

In the line 180 of tc_rainfield.py (rainsum += _RCLIPER(track.max_sustained_wind.values[node], inreach, fradius_km)), the rainrate is summed up without multipling the time interval. 

I'm confused about how the unit of the result is changed from (mm/h) to (mm) in tc_rainfield.py

**Comment by aleeciu** [comment]
Hi,
thanks. So the module assumed that tracks have 1h time steps. In fact, this was better documented in the matlab version https://github.com/davidnbresch/climada_module_tropical_cyclone/blob/master/docs/submodule_tc_rain.pdf. 

I now applied a time step correction and should be soon published in develop. Can you work with develop or do you need help for a work around with the current main? Essentially, as you indicate, one needs to multiply the time step of the current track node to the calcualted node's rain rate.

**Comment by dhli003** [comment]
Thanks very much for the explanation and correction. The default 1h time step is actually good enough for me. I found it when I playing around with climada and thought it might be good to ask my question and study from the experts here.

**Comment by emanuel-schmid** [comment]
solved with PR #236
