### ISSUE TITLE
Geopandas object consistency

### ISSUE THREAD

**Issue by chahank** [CLIMADA-project/climada_python#24]
This many does not really qualifies as an issue, as it is related to how python works. There is an easy work-around, but I mention it so that it stays on the radar.

When an object from a class (e.g. Exposures) which inherits from GeoPandas is manipulated with functions from Pandas, the objects losses its CLIMADA class and reverts to a GeoPandas object. 

Here is an example with litpop. First we create an exposures from LitPop using the country USA and then setting the administration level 1.

`exp = LitPop()`
`countries_list = ['USA'] `
`exp.set_country(countries_list, admin1_calc = True, res_arcsec=300, reference_year=2014)`
`exposure_set_admin1(exp, res_arcsec=300)`

exp is an Exposure object here.

Second we select only those entries  from Florida as

`exp1 = exp[exp['admin1'] == 'Florida']`

exp1 is now a GeoPandas dataframe. 

It still contains all the relevant information, and thus can easily be reconverted into an Exposures by doing

`Exposures(exp1)`

**Comment by emanuel-schmid** [comment]
Another, arguably less elegant, way is to make use of the `loc` method, which returns an Exposures object:
`exp.loc[exp.admin1 == 'Florida'].index,:]`

**Comment by chahank** [comment]
This should not be an issue anymore as Exposures does not inherit from Geopadandas, but has the dataframe as an attribute.
