### ISSUE TITLE
exposure_set_admin1 in LitPop

### ISSUE THREAD

**Issue by simonameiler** [CLIMADA-project/climada_python#25]
There is a function called **exposure_set_admin1** in **litpop.py** which allows us to use state-level information to calculate exposures (if available; only for selected countries). I didn't write the function but I'm using it and noticed that the function should be made available for all exposures. I also saw that it is not correctly initiated (self is missing). 

What needs to be done with the function:
- place it in the exposures/base.py
- correctly initiate it
- write a unit test

**Comment by chahank** [comment]
@sameberenz : can we close this issue?

**Comment by sameberenz** [comment]
> @sameberenz : can we close this issue?

This is not currently worked at from my side. When a universal function for admin1 is written at some point it is probably easier to write it from skretch. But it could be worthwile having a look at the litpop code once for inspiration.

**Comment by chahank** [comment]
If this issue is not resolved, I propose to keep it open?

**Comment by sameberenz** [comment]
with regard to the proposed changes to the method in litpop: this is outdated, so I would keep it closed

**Comment by sameberenz** [comment]
(the current function calculating admin1 exposure for a country in litpop.py is `_calc_admin1_one_country`  https://github.com/CLIMADA-project/climada_python/blob/96c643c10bedbaafce047538e4041d5e83c3e310/climada/entity/exposures/litpop/litpop.py#L1120 )
