### ISSUE TITLE
Climate change impact on property value

### ISSUE THREAD

**Issue by raywong0910** [CLIMADA-project/climada_python#273]
It is noted that MDD, PAA and MDR can be for reference for the impact on property value.
But how can I obtain the impact for Hong Kong  by different districts or areas?

**Comment by chahank** [comment]
The exposures is described by a set of geographical points. You can apply any selection to this set of points. To obtain the impact for a district/area, you need first to define the region of interest (district/area), and sum over the `climada.impact.eai_exp()` points in that region.
