### ISSUE TITLE
Is it possible to plot damages with a user-defined damage function?

### ISSUE THREAD

**Issue by AMPlummer** [CLIMADA-project/climada_python#279]
I've built my own damage function for tropical cyclones. 

I'd like to use plot_hexbin() to plot the damages onto a map. 

However, what's plotted is the Emmanuel 2011 damage function. How can I tell plot_hexbin() to use my user-defined function, not the CLIMADA-provided function?

**Comment by chahank** [comment]
Could you please post a minimal working example of your code? It is always very difficult to answer these questions without a code snippet. 

You should first compute the impact using your impact function, then you can plot the result.

```
from climada.engine import Impact
imp = Impact()
imp.calc(my_exposure, my_impactfuncset, my_hazard)
imp.plot_hexbin()
