### ISSUE TITLE
URL error TCTracks

### ISSUE THREAD

**Issue by Alexouu1** [CLIMADA-project/climada_python#282]
Hello everyone,

I am facing an issue using Climada v2.2.0 and the TCTracks class.
It used to work just fine, but now I'm getting an `URLError: <urlopen error [Errno 110] Connection timed out>` error, for instance when running the following code snippet from Climada readthedocs:

`%matplotlib inline
from climada.hazard import TCTracks

tr_irma = TCTracks()
tr_irma.read_ibtracs_netcdf(provider='usa', storm_id='2017242N16333') # IRMA 2017
ax = tr_irma.plot()
ax.set_title('IRMA') 

from climada.hazard import TCTracks
sel_ibtracs = TCTracks()
sel_ibtracs.read_ibtracs_netcdf(provider='usa', year_range=(1993, 1994), basin='EP', correct_pres=False)
print('Number of tracks:', sel_ibtracs.size)
ax = sel_ibtracs.plot()
ax.get_legend()._loc = 2
ax.set_title('1993-1994, EP')

track1 = TCTracks()
track1.read_ibtracs_netcdf(provider='usa', storm_id='2007314N10093')
track2 = TCTracks()
track2.read_ibtracs_netcdf(provider='usa', storm_id='2016138N10081')
track1.append(track2.data) # put both tracks together
ax = track1.plot()
ax.get_legend()._loc = 2
ax.set_title('SIDR and ROANU');` 

I'm getting this error twice, one of which for the following line
`ax = tr_irma.plot()`

Does anyone know how to solve this? Thank you very much in advance !

PS: I'm running this code on Amazon Sagemaker, not locally

**Comment by chahank** [comment]
Dear @Alexouu1 ,
Could you please indicate at which line exactly do you get the error?

**Comment by Alexouu1** [comment]
For the first error, it doesn't say, but it has something to do with python3.8/urllib/request.py (all the way to python3.8/socket.py)
As for the second one, it's because of `ax = tr_irma.plot()` apparently (indirectly calling urllib/request.py)

**Comment by chahank** [comment]
Please, point to the exact line where the error is raised together with the exact error message. Otherwise, it will be difficult to diagnose. 

Since the error messages are mostly about connection issues, I suspect that the problem is not within CLIMADA, but with the cloud service.

**Comment by Alexouu1** [comment]
Hello @chahank,

The error is raised at the last code line below:

`%matplotlib inline
from climada.hazard import TCTracks

tr_irma = TCTracks()
tr_irma.read_ibtracs_netcdf(provider='usa', storm_id='2017242N16333')
ax = tr_irma.plot()`    #error raised here

I don't think the problem has something to do with Climada either, but I have absolutely no idea how to solve it !
Thank you for you help

**Comment by Alexouu1** [comment]
I believe the timeout has something to do with the url from cartopy/io/shapereader.py, where:
`url = self.url(format_dict)`

Maybe the url cannot be found anymore, hence the timeout of the request?

**Comment by emanuel-schmid** [comment]
Dear @Alexouu1

Would you mind to post the full error message, including stack-trace?

Many thanks in advance!

**Comment by Alexouu1** [comment]
Hello @emanuel-schmid,

Here's the stack-trace:

'URLError                                  Traceback (most recent call last)
<ipython-input-7-ce7a107d3fbd> in <module>
      4 tr_irma = TCTracks()
      5 tr_irma.read_ibtracs_netcdf(provider='usa', storm_id='2017242N16333') # IRMA 2017
----> 6 ax = tr_irma.plot()
      7 # ax.set_title('IRMA') # set title

~/SageMaker/efs/.persisted_conda/tmp/climada_python/climada/hazard/tc_tracks.py in plot(self, axis, figsize, legend, adapt_fontsize, **kwargs)
   1254             _, axis, fontsize = u_plot.make_map(proj=proj, figsize=figsize, adapt_fontsize=adapt_fontsize)
   1255         axis.set_extent(extent, crs=kwargs['transform'])
-> 1256         u_plot.add_shapes(axis)
   1257 
   1258         synth_flag = False

~/SageMaker/efs/.persisted_conda/tmp/climada_python/climada/util/plot.py in add_shapes(axis)
    543         The default is PlateCarree.
    544     """
--> 545     shp_file = shapereader.natural_earth(resolution='10m', category='cultural',
    546                                          name='admin_0_countries')
    547     shp = shapereader.Reader(shp_file)

~/SageMaker/efs/.persisted_conda/climada2_env/lib/python3.8/site-packages/cartopy/io/shapereader.py in natural_earth(resolution, category, name)
    293     format_dict = {'config': config, 'category': category,
    294                    'name': name, 'resolution': resolution}
--> 295     return ne_downloader.path(format_dict)
    296 
    297 

~/SageMaker/efs/.persisted_conda/climada2_env/lib/python3.8/site-packages/cartopy/io/__init__.py in path(self, format_dict)
    220         else:
    221             # we need to download the file
--> 222             result_path = self.acquire_resource(target_path, format_dict)
    223 
    224         return result_path

~/SageMaker/efs/.persisted_conda/climada2_env/lib/python3.8/site-packages/cartopy/io/shapereader.py in acquire_resource(self, target_path, format_dict)
    348         url = self.url(format_dict)
    349         print(f"url: {url}")
--> 350         shapefile_online = self._urlopen(url)
    351 
    352         zfh = ZipFile(six.BytesIO(shapefile_online.read()), 'r')

~/SageMaker/efs/.persisted_conda/climada2_env/lib/python3.8/site-packages/cartopy/io/__init__.py in _urlopen(self, url)
    259         """
    260         warnings.warn('Downloading: {}'.format(url), DownloadWarning)
--> 261         return urlopen(url, timeout = 300)
    262 
    263     @staticmethod

~/SageMaker/efs/.persisted_conda/climada2_env/lib/python3.8/urllib/request.py in urlopen(url, data, timeout, cafile, capath, cadefault, context)
    220     else:
    221         opener = _opener
--> 222     return opener.open(url, data, timeout)
    223 
    224 def install_opener(opener):

~/SageMaker/efs/.persisted_conda/climada2_env/lib/python3.8/urllib/request.py in open(self, fullurl, data, timeout)
    523 
    524         sys.audit('urllib.Request', req.full_url, req.data, req.headers, req.get_method())
--> 525         response = self._open(req, data)
    526 
    527         # post-process response

~/SageMaker/efs/.persisted_conda/climada2_env/lib/python3.8/urllib/request.py in _open(self, req, data)
    540 
    541         protocol = req.type
--> 542         result = self._call_chain(self.handle_open, protocol, protocol +
    543                                   '_open', req)
    544         if result:

~/SageMaker/efs/.persisted_conda/climada2_env/lib/python3.8/urllib/request.py in _call_chain(self, chain, kind, meth_name, *args)
    500         for handler in handlers:
    501             func = getattr(handler, meth_name)
--> 502             result = func(*args)
    503             if result is not None:
    504                 return result

~/SageMaker/efs/.persisted_conda/climada2_env/lib/python3.8/urllib/request.py in https_open(self, req)
   1395 
   1396         def https_open(self, req):
-> 1397             return self.do_open(http.client.HTTPSConnection, req,
   1398                 context=self._context, check_hostname=self._check_hostname)
   1399 

~/SageMaker/efs/.persisted_conda/climada2_env/lib/python3.8/urllib/request.py in do_open(self, http_class, req, **http_conn_args)
   1355                           encode_chunked=req.has_header('Transfer-encoding'))
   1356             except OSError as err: # timeout error
-> 1357                 raise URLError(err)
   1358             r = h.getresponse()
   1359         except:

URLError: <urlopen error [Errno 110] Connection timed out>'

**Comment by emanuel-schmid** [comment]
Thanks a lot. That was helpful. Now I could reproduce the failure. The problematic line is:

` shp_file = cartopy.io.shapereader.natural_earth(resolution='10m', category='cultural', name='admin_0_countries')`

This looks at some place in the home directory for a particular files: "ne_10m_admin_0_countries.shp".\
If it's present - fine. If not, it tries to download it from https://www.naturalearthdata.com/downloads/10m-cultural-vectors/.
For some reason this website is quite irresponsive currently. I guess it's overloaded with requests. This - I further guess - leads to the failing of the named `natural_earth` method.

You have some options:
- download the files manually from https://www.naturalearthdata.com/downloads/10m-cultural-vectors/ and place them in the proper place. (In Windows10 that would be '~/.local/share/cartopy/shapefiles/natural_earth', on a Mac I don't know.)
- wait until the server is up to speed again
- wait until the cartopy people have noticed and fixed the problem

**Comment by emanuel-schmid** [comment]
Ok. My guess was wrong. The reason is not being overloaded but that they changed the url to the actual download site (not the one that's mentioned above).
**Solution**:
Update cartopy! They don't have another release but when you update it nevertheless the url is fixed. Run this:
`conda update cartopy`

**Comment by emanuel-schmid** [comment]
moved to #284
