### ISSUE TITLE
LitPop exp.plot_scatter() return error in Downloading: https://naciscdn.org/naturalearth/50m/cultural/ne_50m_populated_places_simple.zip

### ISSUE THREAD

**Issue by salmiah-ls** [CLIMADA-project/climada_python#283]
Hi everyone,

I try to follow this LitPop tutorial https://climada-python.readthedocs.io/en/stable/tutorial/climada_entity_LitPop.html for country 'IDN', here is my code:

> `from climada.entity import LitPop`

> `exp` = `LitPop()`
> `try:`
>     `exp.set_countries(['IDN'])`
> `except FileExistsError as err:`
>     `print("Reason for error: The GPW population data has not been downloaded, c.f. section 'Input data' above.")`
>     `raise err`

but I got error when I run this code

> `exp.plot_scatter()`

the error is 
`C:\Users\user\anaconda3\envs\climada_env\lib\site-packages\cartopy\io\__init__.py:241: DownloadWarning: Downloading: https://naciscdn.org/naturalearth/50m/cultural/ne_50m_populated_places_simple.zip
  warnings.warn('Downloading: {}'.format(url), DownloadWarning)`

I tried to check the the requred url https://naciscdn.org/naturalearth/50m/cultural/ne_50m_populated_places_simple.zip, and it doesn't exist. How to solve this problem?

Thanks

**Comment by emanuel-schmid** [comment]
Thanks for the notification. They (naturalearth) changed the url to the download site, which is hardcoded in the cartopy.io.shapereader module.
**Solution**: Update cartopy! 
They don't have another release but when you update it nevertheless the url is fixed. Run this:
`conda update cartopy`
and confirm the changes.

**Comment by emanuel-schmid** [comment]
moved to #284
