### ISSUE TITLE
LitPop.set_custom_shape _from_country(): faulty error message & allowance of GeoSeries as input?

### ISSUE THREAD

**Issue by Evelyn-M** [CLIMADA-project/climada_python#287]
Currently the mentioned litpop method allows "only" for shape, polygon or multipolygon in the `shape` attribute.

I accidentally entered a geoseries (gdf.geometry) of polygons, and got hence the (wrong) error message 

> "LOGGER.warning('Could not write attribute meta, because exposure  has only 1 data point')"

triggered by the raised ValueError. I'd suggest putting a type-check for the shape input, or making the error statement more specific to really catching only the 1-data-point case.

This brings me to the second point of potentially extending the input types: In many use-cases one may like to assign LitPop-value estimates to several polygons in one go - cf the [lines_polygons_exposure tutorial](https://github.com/CLIMADA-project/climada_python/blob/feature/lines_polygons_exp/doc/tutorial/climada_entity_Exposures_polygons_lines.ipynb) (all provinces of the Netherlands), or the case where you have a larger dataframe with openstreetmap polygons, etc. 

Currently, this would work only via a loop over the `set_custom_shape _from_country()` method, which re-loads the entire exposure every time. Do you think an extension to GeoSeries would fit there, or should a manual wrapper (loading the exposure once, and then cutting out the polygons for each row in the GDF) be written where needed?

**Comment by Evelyn-M** [comment]
To the latter point: I'm using the `set_countries` and fill my gdf with polygons row-wise at the moment for the polygons-exposure valuation, which works fine as an implementation, too.

**Comment by sameberenz** [comment]
Hi Evelyn, thanks for pointing this out. For a wrapper method that accepts several polygons, – would you suggest that it accepts either a list of polygons or a geoseries object?

**Comment by Evelyn-M** [comment]
for convenience, as most applications are probably born out of the usage of gdfs, I'd say GeoSeries.
