### ISSUE TITLE
Wrong concatenation in `get_hazard`

### ISSUE THREAD

**Issue by emanuel-schmid** [CLIMADA-project/climada_python#295]
There is a a problem with the country combining method. Countries are taken separately and if there is e.g., the same tropical cyclone it will be two separate events. And this means that the results for example for the return period would be wrong.

A hotfix (v3.0.1) prevents concatenation of multiple hazard datasets by setting the default for max_datasets to 1.

The proper solution is to concatenate hazards along the centroids axis. To be done.

**Comment by peanutfun** [comment]
I cannot trace it back anymore, but `Hazard.concat` and `.append` now combine centroids *and* events.
