### ISSUE TITLE
potential bug when calling util.coordinates.get_country_code()

### ISSUE THREAD

**Issue by aleeciu** [CLIMADA-project/climada_python#296]
There is something weird going on with `util.coordinates.get_country_code()`. In particular, if one tries to pass Brazil's lats and lons to get, trivially, Brazil's ISO3 codes:

```
from climada_petals.entity.exposures import BlackMarble
import climada.util.coordinates as u_coord

bm = BlackMarble()
bm.set_countries(['Brazil'])

reg_id = u_coord.get_country_code(bm.gdf.latitude, bm.gdf.longitude)
```

she gets:

`raise LookupError(f'Unknown country identifier: {country}') from None LookupError: Unknown country identifier: Brazilian I.`

which i think is due to some _country.NAME_ taken from the _nat_earth_shape_ in `util.coordinates.get_country_geometries()` not being found by the _pycountry_ package called afterwards by `util.coordinates.country_to_code()`.

I discovered this issue by noticing that `test_crop_production.py` in `climada_petals.entitity.exposures.test` crashes on my machine, but not on @emanuel-schmid's nor Jenkins apparently.

- Can someone check if the above code runs?
- If yes, why can't I run it ? I am using a freshly installed climada-env
- If not, this should be fixed.

**Comment by tovogt** [comment]
Apparantly, the Natural Earth shape file has been updated recently: https://github.com/nvkelso/natural-earth-vector/issues/24 It now includes the disputed area "Brazilian I.". The quickest way to fix this would be to add an entry in the `NONISO_REGIONS` constant: https://github.com/CLIMADA-project/climada_python/blob/f67d4fd160b2bd0f43be63129832d20f4bf55250/climada/util/constants.py#L161-L185
