### ISSUE TITLE
upgrade to cartopy 0.20

### ISSUE THREAD

**Issue by emanuel-schmid** [CLIMADA-project/climada_python#320]
cartopy 0.20.0 omits the proj4_params in CRS, which is used to get their units

change the way we retrieve units.

run `climada.util.test.test_plot.TestFuncs.test_get_transform_3035_pass` for reproduction

**Comment by tovogt** [comment]
This is fixed in ea0954c7 (as part of #322)

**Comment by emanuel-schmid** [comment]
@tovogt : yes it is. Thanks a lot! 🙌
