### ISSUE TITLE
Conversion of ISO numeric-3 codes to FAO country code does not work for integers

### ISSUE THREAD

**Issue by CyrilWillimann** [CLIMADA-project/climada_python#328]
In climada_python/coordinates.py, the method _country_iso2faocode_ is supposed to accept both integers and arrays but currently only works for arrays. See screenshot below. Workaround with _fao_code = u_coord.country_iso2faocode(np.array([iso_code])_) works fine but maybe this could be improved.
![Screenshot 2021-11-22 at 13 44 09](https://user-images.githubusercontent.com/93337700/142864188-3d8bff0a-6407-4006-9d96-eefc2d6796d0.png)

**Comment by carmensteinmann** [comment]
@chahank I would suggest adapting the docstring and only allowing for arrays. Should I push that change to climada_python/develop?

**Comment by chahank** [comment]
I also think this is a good idea. Could you please do a branch and a pull request as usual?

**Comment by carmensteinmann** [comment]
Sure

**Comment by carmensteinmann** [comment]
Suggested changes: #329

**Comment by emanuel-schmid** [comment]
@CyrilWillimann : thank you for pointing this out. The pydoc string has been modified in the develop branch, so that it is not contradicting the method's signature anymore.
This also means that the workaround suggested by you is now the "official" way to handle single codes.
