### ISSUE TITLE
Build status in README.md refers to old CI 

### ISSUE THREAD

**Issue by mmyrte** [CLIMADA-project/climada_python#34]
Apparently, the "Build: Passing" badge in `README.md` is still referring to the old continuous integration builds. I guess @emanuel-schmid may be the one to have a look at this? Maybe we can also have a badge for the develop branch...

**Comment by emanuel-schmid** [comment]
That's the case for the master branch. 
It will resolve with the next release.
Meanwhile, change to the develop branch, please.
