### ISSUE TITLE
Can we have a one-line initialisation of `ImpactFuncSet`?

### ISSUE THREAD

**Issue by ChrisFairless** [CLIMADA-project/climada_python#342]
When I create an impact function set from some impact function `impf` I always do it with
```
impfset = ImpactFuncSet()
impfset.append(impf)
```

In the spirit of not initialising empty classes, I'd like to either
- write an `ImpactFuncSet.from_impf` method which initialises from a list of impact functions
- modify `ImpactFuncSet.__init__` to take a list of impact functions on initialisation

Is this a good idea? Any preferences?

**Comment by chahank** [comment]
Great point!

I would argue for making a good `__init__`. Ideally, all elements of the impact function set should be set at initialization.

**Comment by ChrisFairless** [comment]
Yeah a good `__init__` would be better. But would that mess with CLIMADA's, uh, 'style', where our `__init__` methods never take parameters, and instead initialise with `from_*` methods?

**Comment by chahank** [comment]
I agree, but we can try to improve in the future. Some classes already have it. 

I would propose to do the `__init__` as it does not hurt.

@emanuel-schmid : do you have any feedback here?

**Comment by peanutfun** [comment]
One-line initialization of `ImpactFuncSet` was implemented in #568
