### ISSUE TITLE
Cent.plot() returns AtrributeError error in tuturials

### ISSUE THREAD

**Issue by climeyG** [CLIMADA-project/climada_python#347]
When running the main and cyclone hazard tutorials the command `cent.plot()`  results in the error: AttributeError: 'PlateCarree' object has no attribute 'to_dict' as below on my side. With me not having programming background, I'm at a loss as to how to overcome it. 

from climada.hazard import Centroids
min_lat, max_lat, min_lon, max_lon = 17.5, 19.0, -68.0, -65.0
cent = Centroids.from_pnt_bounds((min_lon, min_lat, max_lon, max_lat), res=0.05)
cent.check()
cent.plot()

---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
~\AppData\Local\Temp/ipykernel_6440/4185815954.py in <module>
      6 cent.check()
      7 
----> 8 cent.plot()

c:\users\c0760525\program\climada_python\climada\hazard\centroids\centr.py in plot(self, axis, figsize, **kwargs)
   1037         pad = np.abs(u_coord.get_resolution(self.lat, self.lon)).min()
   1038 
-> 1039         proj_data, _ = u_plot.get_transformation(self.crs)
   1040         proj_plot = proj_data
   1041         if isinstance(proj_data, ccrs.PlateCarree):

c:\users\c0760525\program\climada_python\climada\util\plot.py in get_transformation(crs_in)
    734 
    735     try:
--> 736         units = crs_epsg.to_dict()['units']
    737     except KeyError:
    738         units = '°'

AttributeError: 'PlateCarree' object has no attribute 'to_dict'

**Comment by emanuel-schmid** [comment]
This may be related to recent changes of CLIMADA in the conda environment. Can you pull from develop branch and update the environment (e.g., `conda env update -n climada_env -f requirements/env_climada.yml`) then try again?

**Comment by climeyG** [comment]
Indeed. Problem resolved. 

The 'tracks.plot()' command is taking suspiciously long now... but I'll have a look at that seperately.
