### ISSUE TITLE
bug in river_flood

### ISSUE THREAD

**Issue by emanuel-schmid** [CLIMADA-project/climada_python#35]
In `river_flood.RiverFlood.set_from_nc` line 106 is opened and remains open over line 120, when `set_raster` is called, passing the same file as argument, leading to `rasterio.errors.RasterioIOError: '...' not recognized as a supported file format`.

Please, try and fix it in the develop branch.

**Comment by ingajsa** [comment]
When does this error emerge? I cannot find it in the Jenkins test results and I don't get it locally or on our cluster, either. 
Looking at the code, I see that in line 106 I actually use:
with file open as...:
to avoid errors or these kind...

**Comment by tovogt** [comment]
@emanuel-schmid Didn't you already fix this in  3fb36c8 ?

https://github.com/CLIMADA-project/climada_python/blob/3613833c1a89b71164978b2e2e670f3c2054b105/climada/hazard/river_flood.py#L106-L107

**Comment by scem** [comment]
Yes, but it's not supposed to be the final solution. In the current version, the file is opened, read and closed three times. twice in `set_from_nc` itselft, in lines 106 and 209.

**Comment by tovogt** [comment]
Okay, but that's not an issue, is it? There are thousands of places in the CLIMADA code that are inefficient in this or comparable ways. Having an open issue for each of these would be quite overwhelming. I suggest to use the "Issues" section only for things that either are actually broken or at least require an open discussion.

**Comment by ingajsa** [comment]
Ok, I see that I forgot to close it in the previous version. Thanks for fixing that, then. I have discussed this issue that the file needs to be opened twice at this point with Gabriela some time ago and we agreed upon this solution...
