### ISSUE TITLE
Unit test failures

### ISSUE THREAD

**Issue by bguillod** [CLIMADA-project/climada_python#354]
I've just installed climada_python from scratch following the instructions at [https://climada-python.readthedocs.io/en/latest/guide/Guide_Installation.html](https://climada-python.readthedocs.io/en/latest/guide/Guide_Installation.html), from the develop branch. Since I could not install the environment for climada_petals (see [https://github.com/CLIMADA-project/climada_petals/issues/18](https://github.com/CLIMADA-project/climada_petals/issues/18)) my installation is only with climada core.

However the unit tests fails as follows:

1. `python -m unittest climada.engine.test.test_impact` failed as follows (but was solved with `python -c 'import climada; climada.setup_climada_data(reload=True)')`:

```
/Users/bguillod/miniconda3/envs/climada_env/lib/python3.8/site-packages/statsmodels/compat/pandas.py:65: FutureWarning: pandas.Int64Index is deprecated and will be removed from pandas in a future version. Use pandas.Index with the appropriate dtype instead.
  from pandas import Int64Index as NumericIndex
.F.........E............2022-01-24 14:15:39,674 - climada.engine.impact - WARNING - No event matches the selection.
.
======================================================================
ERROR: test_ref_value_insure_pass (climada.engine.test.test_impact.TestOneExposure)
Test result against reference value
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/bguillod/Documents/work/CelsiusPro/code/CLIMADA/climada_python/climada/engine/test/test_impact.py", line 138, in test_ref_value_insure_pass
    imp_id = ent.exposures.gdf.impf_TC[iexp]
  File "/Users/bguillod/miniconda3/envs/climada_env/lib/python3.8/site-packages/pandas/core/generic.py", line 5583, in __getattr__
    return object.__getattribute__(self, name)
AttributeError: 'GeoDataFrame' object has no attribute 'impf_TC'

======================================================================
FAIL: test_calc_impf_pass (climada.engine.test.test_impact.TestCalc)
Execute when no impf_HAZ present, but only impf_
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/bguillod/Documents/work/CelsiusPro/code/CLIMADA/climada_python/climada/engine/test/test_impact.py", line 244, in test_calc_impf_pass
    self.assertTrue('impf_TC' in ent.exposures.gdf.columns)
AssertionError: False is not true

----------------------------------------------------------------------
Ran 25 tests in 6.924s

FAILED (failures=1, errors=1)
```

Should any file be updated in the repository to avoid the extra step of running `python -c 'import climada; climada.setup_climada_data(reload=True)`?

2. And, more problematic, `python -m unittest climada.engine.test.test_cost_benfit` fails as follows (not solved):

```
/Users/bguillod/miniconda3/envs/climada_env/lib/python3.8/site-packages/statsmodels/compat/pandas.py:65: FutureWarning: pandas.Int64Index is deprecated and will be removed from pandas in a future version. Use pandas.Index with the appropriate dtype instead.
  from pandas import Int64Index as NumericIndex
E======================================================================
ERROR: test_cost_benfit (unittest.loader._FailedTest)
----------------------------------------------------------------------
ImportError: Failed to import test module: test_cost_benfit
Traceback (most recent call last):
  File "/Users/bguillod/miniconda3/envs/climada_env/lib/python3.8/unittest/loader.py", line 154, in loadTestsFromName
    module = __import__(module_name)
ModuleNotFoundError: No module named 'climada.engine.test.test_cost_benfit'


----------------------------------------------------------------------
Ran 1 test in 0.001s

FAILED (errors=1)
```

Is there any obvious reason why this second one fails? How can I solve this?

Also, why are these two tests recommended in the installation guide? Do these replace the old `python tests_install.py` (which works and ends with "OK" with my installation), and why?

**Comment by davidnbresch** [comment]
I can run the first test, i.e.

```
python -m unittest climada.engine.test.test_impact
...
Ran 25 tests in 6.115s
```
but the second does fail, too:

```
python -m unittest climada.engine.test.test_cost_benfit
E
======================================================================
ERROR: test_cost_benfit (unittest.loader._FailedTest)
----------------------------------------------------------------------
ImportError: Failed to import test module: test_cost_benfit
Traceback (most recent call last):
  File "/Users/bresch/opt/anaconda3/envs/climada_env/lib/python3.8/unittest/loader.py", line 154, in loadTestsFromName
    module = __import__(module_name)
ModuleNotFoundError: No module named 'climada.engine.test.test_cost_benfit'


----------------------------------------------------------------------
Ran 1 test in 0.000s

FAILED (errors=1)
```
help appreciated!

**Comment by emanuel-schmid** [comment]
@bguillod 

> Also, why are these two tests recommended in the installation guide? Do these replace the old python tests_install.py (which works and ends with "OK" with my installation), and why?

Yes, this are exactly the tests that are executed by the `make install_test` command. They were replaced because `make install_test` doesn't work 
- when climada is directly installed from pip (PyPi installation): missing tests_install.py file
- on Windows: missing `make` (although `conda install make` solves this problem)

But you can still just run `make install_test`. If the the statement above is correct you should get the very same result.

**Comment by davidnbresch** [comment]
Yet if I run `climada.engine.test.test_cost_benfit` in spyder (open the test, execute with run), it all works fine:

```
Ran 22 tests in 16.051s
```

Hence strange it finds climada.engine.test.test_impact, but not climada.engine.test.test_cost_benfit, as they are in the same folder.

**Comment by emanuel-schmid** [comment]
Yes, strange indeed. Let me check...

**Comment by emanuel-schmid** [comment]
Oops! Very sorry but there is a typo in the installation guide: it should say climada.engine.test.test_cost_ben**e**fit.

**Comment by bguillod** [comment]
> Oops! Very sorry but there is a typo in the installation guide: it should say climada.engine.test.test_cost_ben**e**fit.

Aaah yes, we should have noticed that one! Works fine now indeed!
