### ISSUE TITLE
bug in cropyield_isimip

### ISSUE THREAD

**Issue by emanuel-schmid** [CLIMADA-project/climada_python#36]
in `CropYieldIsimip.set_from_single_run`, lines 273 and 279 the variable self._metadata is modified.

```
        (self._metadata).append('crop')

        #Method set_to_usd() is called to compute the exposure in USD/y (per centroid)
        #the exposure in t/y is saved as 'value_tonnes'
        if unit == 'USD':
            self['value_tonnes'] = self['value']
            (self._metadata).append('value_tonnes')
            self.set_to_usd(dir_fao=os.path.join(input_dir, 'FAO'))
```

That is problematic and leads to errors in the Unit test run.
There are two problems. One is the old, infamous Python pitfall. `_metadata` is a class variable:

```
class Exposures(GeoDataFrame):
    _metadata = GeoDataFrame._metadata + ['tag', 'ref_year', 'value_unit',
                                          'meta']
    
    ...

    def __init__(self, *args, **kwargs):
        if len(args):
            for var_meta in self._metadata:
                try:
                    val_meta = getattr(args[0], var_meta)
                    setattr(self, var_meta, val_meta)
                except AttributeError:
                    pass
        super(Exposures, self).__init__(*args, **kwargs)
 ```
In Python variable initialisation in the class body implicitly creates class variables. (That's different from Java where it doesn't matter whether variables are initialised in the constructor or in the class body.) Object Variables must be assigned with at `self` reference, i.e. in the constructor or another method.

The other problem is the leading underscore of `_metadata`. This is a request for privacy and indicates that the variable is meant for internal use. One _can_ manipulate such variables, but in general - and in particular! - it is not advisable.

#### Quick and dirty solution
Override the `Exposures._metatdata` in `CropYieldIsimip`.
Assign `self.crop` and `self.value_tonnes`.
```
class CropyieldIsimip(Exposures):

    _metadata = Exposures._metadata + ['crop', 'value_tonnes']
    ...
    def set_from_single_run(...):
        ...

        #Method set_to_usd() is called to compute the exposure in USD/y (per centroid)
        #the exposure in t/y is saved as 'value_tonnes'
        if unit == 'USD':
            self.value_tonnes = self['value']
            self.set_to_usd(dir_fao=os.path.join(input_dir, 'FAO'))
        else:
            self.value_tonnes = None
        ...
```
#### TODO
Re-evaluate options to implement CropYieldIsimip without overriding _metadata.

**Comment by emanuel-schmid** [comment]
commit 7a85c4d78941687459c1eedb8230411ab90148c6 implements above solution

**Comment by sameberenz** [comment]
Hi Emanuel

Thanks for pointing out the problem and implementing the quick fix.

I am not sure what another soultion could look like.

When saving an exposure instance to a file, only variables listed in _metadata are actually written:

C.f. write_hdf5() in [exposures.base](https://github.com/CLIMADA-project/climada_python/blob/develop/climada/entity/exposures/base.py):
```    
def write_hdf5(self, file_name):
        """Write data frame and metadata in hdf5 format"""
        LOGGER.info('Writting %s', file_name)
        store = pd.HDFStore(file_name)
        store.put('exposures', pd.DataFrame(self))

        var_meta = {}
        for var in self._metadata:
            var_meta[var] = getattr(self, var)

        store.get_storer('exposures').attrs.metadata = var_meta
        store.close()
```

If we want to save the attributes specific to the class **CropYieldIsimip** ('crop', 'value_tonnes') as well, how could we implement this without overriding __metadata_?

**Comment by sameberenz** [comment]
With the following two commits, I have changed it based on the example of how the Exposures class expands the _metadata.
This means, I added 'crop' to _metadata in the same fashion as it is done in Exposures() and 'value_tonnes' as column to the underlying dataframe. Like this, it is consistent with Exposures() and the exposure data can be saved for hdf5 without losing the information on "crop" and "value_tonnes"


change: https://github.com/CLIMADA-project/climada_python/commit/b33e60d45cc04a4eb4ffb851fb8404f91e3b2850
clean up: https://github.com/CLIMADA-project/climada_python/commit/3613833c1a89b71164978b2e2e670f3c2054b105

**Comment by sameberenz** [comment]
PS:
self['value_tonnes'] = self['value'] is required in this form so that value_tonnes is written to hdf5 or csv as a column of the dataframe underlying the exposure object.
