### ISSUE TITLE
Docs for ImpfSetTropCyclone in read-the-docs

### ISSUE THREAD

**Issue by tovogt** [CLIMADA-project/climada_python#364]
The quite useful class ImpfSetTropCyclone is missing from the docs on read-the-docs (https://climada-python.readthedocs.io/en/stable/climada/climada.entity.impact_funcs.html#module-climada.entity.impact_funcs.trop_cyclone):
https://github.com/CLIMADA-project/climada_python/blob/7d2d7c6695f19e046549aa7d1f4ff2b9530f0189/climada/entity/impact_funcs/trop_cyclone.py#L102-L103
I guess that the reason might be that this class is not explicitly exported:
https://github.com/CLIMADA-project/climada_python/blob/7d2d7c6695f19e046549aa7d1f4ff2b9530f0189/climada/entity/impact_funcs/trop_cyclone.py#L22
So, there are two questions:
1) Why isn't this class listed in `__all__`? It's really useful.
2) If it's not in `__all__` for a reason, can we at least enforce somehow that it's still listed in read-the-docs?

**Comment by emanuel-schmid** [comment]
Thanks for the notification!

1, Don't know for sure but suspect it simply got forgotten.
2. Don't know either.

Wasn't aware of this rule that only exported classes will be documented. If it holds, the problem will be solved soon, for I've just pushed a fix to develop.

**Comment by tovogt** [comment]
Great, seems to work: https://climada-python.readthedocs.io/en/latest/climada/climada.entity.impact_funcs.html#climada.entity.impact_funcs.trop_cyclone.ImpfSetTropCyclone

Issue solved :)
