### ISSUE TITLE
UnidentifiedImageError in the tutorial 1_main_climada

### ISSUE THREAD

**Issue by frqqyy** [CLIMADA-project/climada_python#376]
Hello everyone,

I ran the code blocks in the first tutorial one after another, and the block of the code "imp.plot_basemap_eai_exposure(buffer=0.1);" showed an error. The screenshots of the error are attached here.
![tutorial1 1](https://user-images.githubusercontent.com/71314575/157524046-ee02dcfc-2952-4ada-9a11-a71384826f55.png)
![tutorial1 2](https://user-images.githubusercontent.com/71314575/157524162-23415328-fb51-459e-bc0e-3edefae9f330.png)
![tutorial1 3](https://user-images.githubusercontent.com/71314575/157524174-df9aa3d6-affa-4b55-9c77-ea598210c8a1.png)
![tutorial1 4](https://user-images.githubusercontent.com/71314575/157524178-d075ff6d-8369-4bc6-b669-7eb87d53105e.png)

Do you have an idea how I can fix it?
Thank you very much in advance!

**Comment by chahank** [comment]
I cannot reproduce the error. Could you please have a look @emanuel-schmid ?

**Comment by emanuel-schmid** [comment]
Me neither. 
![image](https://user-images.githubusercontent.com/51439563/158204202-2b3d4b43-b2ea-42a4-85f5-c0bbf3a3b908.png)

Perhaps a dependency issue?
Can you run `conda list` and paste the result, please?

**Comment by emanuel-schmid** [comment]
Thanks! That's almost what I wanted, but can you post the output as text instead of images, so I can compare it with the supposed  result?

**Comment by frqqyy** [comment]
> Thanks! That's almost what I wanted, but can you post the output as text instead of images, so I can compare it with the supposed result?

Oh I'm so sorry.

# packages in environment at C:\Users\yyljy\.conda\envs\climada_env:
#
# Name                    Version                   Build  Channel
affine                    2.3.0                      py_0    conda-forge
alabaster                 0.7.12                     py_0    conda-forge
argon2-cffi               20.1.0           py38h2bbff1b_1  
astroid                   2.5                      pypi_0    pypi
asttokens                 2.0.5              pyhd8ed1ab_0    conda-forge
attrs                     21.2.0             pyhd8ed1ab_0    conda-forge
babel                     2.9.1              pyh44b312d_0    conda-forge
backcall                  0.2.0              pyh9f0ad1d_0    conda-forge
backports                 1.0                        py_2    conda-forge
backports.functools_lru_cache 1.6.4              pyhd8ed1ab_0    conda-forge
bitstring                 3.1.9                    pypi_0    pypi
black                     21.12b0            pyhd8ed1ab_0    conda-forge
bleach                    4.1.0              pyhd3eb1b0_0  
blosc                     1.21.0               h0e60522_0    conda-forge
bokeh                     2.4.0            py38haa244fe_0    conda-forge
boost-cpp                 1.74.0               h5b4e17d_4    conda-forge
bottleneck                1.3.4            py38h6f4d8f0_0    conda-forge
brotlipy                  0.7.0           py38h294d835_1001    conda-forge
bzip2                     1.0.8                h8ffe710_4    conda-forge
ca-certificates           2022.2.1             haa95532_0  
cached-property           1.5.2                hd8ed1ab_1    conda-forge
cached_property           1.5.2              pyha770c72_1    conda-forge
cairo                     1.16.0            hb19e0ff_1008    conda-forge
cartopy                   0.20.0           py38h984f1da_0    conda-forge
certifi                   2021.10.8        py38haa95532_2  
cffi                      1.14.6           py38hd8c33c5_1    conda-forge
cfgrib                    0.9.10.0           pyhd8ed1ab_0    conda-forge
cfitsio                   3.470                h0af3d06_7    conda-forge
cftime                    1.5.1            py38h6f4d8f0_0    conda-forge
chardet                   4.0.0            py38haa244fe_1    conda-forge
charset-normalizer        2.0.0              pyhd8ed1ab_0    conda-forge
click                     7.1.2              pyh9f0ad1d_0    conda-forge
click-plugins             1.1.1                      py_0    conda-forge
cligj                     0.7.2              pyhd8ed1ab_0    conda-forge
climada                   3.1.1                    pypi_0    pypi
climada-petals            3.1.1.dev0                dev_0    <develop>
cloudpickle               2.0.0              pyhd8ed1ab_0    conda-forge
colorama                  0.4.4              pyh9f0ad1d_0    conda-forge
contextily                1.2.0              pyhd8ed1ab_0    conda-forge
coverage                  6.3.2                    pypi_0    pypi
cryptography              3.4.7            py38hd7da0ea_0    conda-forge
curl                      7.79.1               h789b8ee_1    conda-forge
cycler                    0.10.0                     py_2    conda-forge
cytoolz                   0.11.0           py38h294d835_3    conda-forge
dask                      2021.9.1           pyhd8ed1ab_0    conda-forge
dask-core                 2021.9.1           pyhd8ed1ab_0    conda-forge
dataclasses               0.8                pyhc8e2a94_3    conda-forge
debugpy                   1.5.1            py38hd77b12b_0  
decorator                 5.1.1              pyhd8ed1ab_0    conda-forge
defusedxml                0.7.1              pyhd3eb1b0_0  
deprecated                1.2.12             pyh44b312d_0    conda-forge
deprecation               2.1.0                    pypi_0    pypi
descartes                 1.1.0                    pypi_0    pypi
dill                      0.3.4              pyhd8ed1ab_0    conda-forge
distributed               2021.9.1         py38haa244fe_0    conda-forge
docutils                  0.17.1           py38haa244fe_1    conda-forge
eccodes                   2.23.0               hb57a5e5_2    conda-forge
entrypoints               0.3                      py38_0  
et_xmlfile                1.0.1                   py_1001    conda-forge
executing                 0.8.3              pyhd8ed1ab_0    conda-forge
expat                     2.4.1                h39d44d4_0    conda-forge
fiona                     1.8.20           py38hbf36ab5_1    conda-forge
font-ttf-dejavu-sans-mono 2.37                 hab24e00_0    conda-forge
font-ttf-inconsolata      3.000                h77eed37_0    conda-forge
font-ttf-source-code-pro  2.038                h77eed37_0    conda-forge
font-ttf-ubuntu           0.83                 hab24e00_0    conda-forge
fontconfig                2.13.1            h1989441_1005    conda-forge
fonts-conda-ecosystem     1                             0    conda-forge
fonts-conda-forge         1                             0    conda-forge
freetype                  2.10.4               h546665d_1    conda-forge
freexl                    1.0.6                ha8e266a_0    conda-forge
fsspec                    2021.9.0           pyhd8ed1ab_0    conda-forge
gdal                      3.3.2            py38hc3a09ef_2    conda-forge
geographiclib             1.52               pyhd8ed1ab_0    conda-forge
geopandas                 0.9.0              pyhd8ed1ab_1    conda-forge
geopandas-base            0.9.0              pyhd8ed1ab_1    conda-forge
geopy                     2.2.0              pyhd8ed1ab_0    conda-forge
geos                      3.9.1                h39d44d4_2    conda-forge
geotiff                   1.7.0                ha8a8a2d_0    conda-forge
gettext                   0.19.8.1          ha2e2712_1008    conda-forge
h5py                      3.6.0           nompi_py38hde0384b_100    conda-forge
haversine                 2.5.1              pyhd8ed1ab_0    conda-forge
hdf4                      4.2.15               h0e5069d_3    conda-forge
hdf5                      1.12.1          nompi_h2a0e4a3_100    conda-forge
heapdict                  1.0.1                      py_0    conda-forge
icu                       68.1                 h0e60522_0    conda-forge
idna                      3.1                pyhd3deb0d_0    conda-forge
imagesize                 1.3.0              pyhd8ed1ab_0    conda-forge
importlib-metadata        4.8.1            py38haa244fe_0    conda-forge
importlib_metadata        4.8.1                hd8ed1ab_0    conda-forge
importlib_resources       5.2.2              pyhd8ed1ab_0    conda-forge
intel-openmp              2021.3.0          h57928b3_3372    conda-forge
ipykernel                 6.4.1            py38haa95532_1  
ipython                   7.31.1           py38haa95532_0  
ipython_genutils          0.2.0              pyhd3eb1b0_1  
isort                     5.10.1                   pypi_0    pypi
jbig                      2.1               h8d14728_2003    conda-forge
jedi                      0.18.1           py38haa244fe_0    conda-forge
jinja2                    3.0.1              pyhd8ed1ab_0    conda-forge
joblib                    1.0.1              pyhd8ed1ab_0    conda-forge
jpeg                      9d                   h8ffe710_0    conda-forge
jsonschema                4.4.0                    pypi_0    pypi
jupyter-core              4.9.2                    pypi_0    pypi
jupyter_client            7.1.2              pyhd3eb1b0_0  
jupyter_core              4.9.1            py38haa95532_0  
jupyterlab_pygments       0.1.2                      py_0  
kealib                    1.4.14               h8995ca9_3    conda-forge
kiwisolver                1.3.2            py38hbd9d945_0    conda-forge
krb5                      1.19.2               hbae68bd_1    conda-forge
lazy-object-proxy         1.7.1                    pypi_0    pypi
lcms2                     2.12                 h2a16943_0    conda-forge
lerc                      2.2.1                h0e60522_0    conda-forge
libblas                   3.9.0              11_win64_mkl    conda-forge
libcblas                  3.9.0              11_win64_mkl    conda-forge
libclang                  11.1.0          default_h5c34c98_1    conda-forge
libcurl                   7.79.1               h789b8ee_1    conda-forge
libdeflate                1.7                  h8ffe710_5    conda-forge
libffi                    3.4.2                h0e60522_4    conda-forge
libgdal                   3.3.2                hfb14b67_2    conda-forge
Note: you may need to restart the kernel to use updated packages.
libglib                   2.68.4               h3be07f2_1    conda-forge
libiconv                  1.16                 he774522_0    conda-forge
libkml                    1.3.0             h9859afa_1014    conda-forge
liblapack                 3.9.0              11_win64_mkl    conda-forge
libnetcdf                 4.8.1           nompi_h1cc8e9d_101    conda-forge
libpng                    1.6.37               h1d00b33_2    conda-forge
libpq                     13.3                 hfcc5ef8_0    conda-forge
librttopo                 1.1.0                hb340de5_6    conda-forge
libspatialindex           1.9.3                h39d44d4_4    conda-forge
libspatialite             5.0.1                h762a7f4_6    conda-forge
libssh2                   1.10.0               h680486a_2    conda-forge
libtiff                   4.3.0                h0c97f57_1    conda-forge
libwebp-base              1.2.1                h8ffe710_0    conda-forge
libxml2                   2.9.12               hf5bbc77_0    conda-forge
libxslt                   1.1.33               h65864e5_2    conda-forge
libzip                    1.8.0                hfed4ece_1    conda-forge
llvmlite                  0.37.0           py38h57a6900_0    conda-forge
locket                    0.2.0                      py_2    conda-forge
lxml                      4.6.3            py38h292cb97_0    conda-forge
lz4-c                     1.9.3                h8ffe710_1    conda-forge
m2w64-gcc-libgfortran     5.3.0                         6    conda-forge
m2w64-gcc-libs            5.3.0                         7    conda-forge
m2w64-gcc-libs-core       5.3.0                         7    conda-forge
m2w64-gmp                 6.1.0                         2    conda-forge
m2w64-libwinpthread-git   5.0.0.4634.697f757               2    conda-forge
mapclassify               2.2.0                      py_0    conda-forge
markupsafe                2.0.1            py38h294d835_0    conda-forge
matplotlib                3.4.3            py38haa244fe_2    conda-forge
matplotlib-base           3.4.3            py38h1f000d6_1    conda-forge
matplotlib-inline         0.1.3              pyhd8ed1ab_0    conda-forge
mccabe                    0.6.1                    pypi_0    pypi
memory-profiler           0.60.0                   pypi_0    pypi
mercantile                1.2.1              pyhd8ed1ab_0    conda-forge
mistune                   0.8.4           py38he774522_1000  
mkl                       2021.3.0           hb70f87d_564    conda-forge
mock                      4.0.3            py38haa244fe_1    conda-forge
msgpack-python            1.0.2            py38hbd9d945_1    conda-forge
msys2-conda-epoch         20160418                      1    conda-forge
multiprocess              0.70.12.2        py38h294d835_0    conda-forge
munch                     2.5.0                      py_0    conda-forge
mypy_extensions           0.4.3            py38haa244fe_4    conda-forge
nbclient                  0.5.11             pyhd3eb1b0_0  
nbconvert                 6.1.0            py38haa95532_0  
nbformat                  5.1.3              pyhd3eb1b0_0  
nest-asyncio              1.5.1              pyhd3eb1b0_0  
netcdf4                   1.5.8           nompi_py38h0500770_101    conda-forge

notebook                  6.4.8            py38haa95532_0  
numba                     0.54.1           py38h5858985_0    conda-forge
numexpr                   2.7.3            py38h4c96930_0    conda-forge
numpy                     1.20.3           py38h09042cb_0    conda-forge
olefile                   0.46               pyh9f0ad1d_1    conda-forge
openjpeg                  2.4.0                hb211442_1    conda-forge
openpyxl                  3.0.9              pyhd8ed1ab_0    conda-forge
openssl                   1.1.1m               h2bbff1b_0  
overpy                    0.6                      pypi_0    pypi
packaging                 21.3                     pypi_0    pypi
pandas                    1.3.3            py38h5d928e2_0    conda-forge
pandas-datareader         0.10.0             pyh6c4a22f_0    conda-forge
pandocfilters             1.5.0              pyhd3eb1b0_0  
parso                     0.8.3              pyhd8ed1ab_0    conda-forge
partd                     1.2.0              pyhd8ed1ab_0    conda-forge
pathos                    0.2.8              pyhd8ed1ab_0    conda-forge
pathspec                  0.9.0              pyhd8ed1ab_0    conda-forge
patsy                     0.5.2              pyhd8ed1ab_0    conda-forge
pcre                      8.45                 h0e60522_0    conda-forge
peewee                    3.14.9                   pypi_0    pypi
pickleshare               0.7.5                   py_1003    conda-forge
pillow                    8.3.2            py38h794f750_0    conda-forge
pint                      0.18               pyhd8ed1ab_0    conda-forge
pip                       22.0.3             pyhd8ed1ab_0    conda-forge
pixman                    0.40.0               h8ffe710_0    conda-forge
platformdirs              2.5.1              pyhd8ed1ab_0    conda-forge
poppler                   21.09.0              h24fffdf_2    conda-forge
poppler-data              0.4.11               hd8ed1ab_0    conda-forge
postgresql                13.3                 h1c22c4f_0    conda-forge
pox                       0.3.0              pyhd8ed1ab_0    conda-forge
ppft                      1.6.6.4            pyhd8ed1ab_0    conda-forge
proj                      8.0.1                h1cfcee9_0    conda-forge
prometheus_client         0.13.1             pyhd3eb1b0_0  
prompt-toolkit            3.0.27             pyha770c72_0    conda-forge
psutil                    5.8.0            py38h294d835_1    conda-forge
pure_eval                 0.2.2              pyhd8ed1ab_0    conda-forge
pybufrkit                 0.2.19                   pypi_0    pypi
pycountry                 20.7.3             pyh9f0ad1d_0    conda-forge
pycparser                 2.20               pyh9f0ad1d_2    conda-forge
pyepsg                    0.4.0                      py_0    conda-forge
pygments                  2.11.2             pyhd8ed1ab_0    conda-forge
pylint                    2.7.1                    pypi_0    pypi
pyopenssl                 20.0.1             pyhd8ed1ab_0    conda-forge
pyparsing                 2.4.7              pyh9f0ad1d_0    conda-forge
pyproj                    3.2.1            py38habcafb0_1    conda-forge
pyqt                      5.12.3           py38haa244fe_7    conda-forge
pyqt-impl                 5.12.3           py38h885f38d_7    conda-forge
pyqt5-sip                 4.19.18          py38h885f38d_7    conda-forge
pyqtchart                 5.12             py38h885f38d_7    conda-forge
pyqtwebengine             5.12.1           py38h885f38d_7    conda-forge
pyrsistent                0.18.1                   pypi_0    pypi
pyshp                     2.1.3              pyh44b312d_0    conda-forge
pysocks                   1.7.1            py38haa244fe_3    conda-forge
pytables                  3.6.1            py38h7deab4d_4    conda-forge
python                    3.8.12          h7840368_2_cpython    conda-forge
python-dateutil           2.8.2              pyhd8ed1ab_0    conda-forge
python-eccodes            2021.03.0        py38hcb5f9af_1    conda-forge
python_abi                3.8                      2_cp38    conda-forge
pytz                      2021.1             pyhd8ed1ab_0    conda-forge
pywin32                   303                      pypi_0    pypi
pywinpty                  2.0.2            py38h5da7b33_0  
pyxlsb                    1.0.9              pyhd8ed1ab_0    conda-forge
pyyaml                    5.4.1            py38h294d835_1    conda-forge
pyzmq                     22.3.0           py38hd77b12b_2  
qt                        5.12.9               h5909a2a_4    conda-forge
rasterio                  1.2.8            py38h3c78ccf_0    conda-forge
readthedocs-sphinx-ext    2.1.4                    pypi_0    pypi
requests                  2.27.1             pyhd8ed1ab_0    conda-forge
rtree                     0.9.7            py38h8b54edf_2    conda-forge
salib                     1.3.12                   pypi_0    pypi
scikit-learn              1.0.2            py38hb60ee80_0    conda-forge
scipy                     1.8.0            py38ha1292f7_1    conda-forge
send2trash                1.8.0              pyhd3eb1b0_1  
setuptools                58.0.4           py38haa244fe_2    conda-forge
shapely                   1.7.1            py38h127f298_5    conda-forge
six                       1.16.0             pyh6c4a22f_0    conda-forge
snowballstemmer           2.2.0              pyhd8ed1ab_0    conda-forge
snuggs                    1.4.7                      py_0    conda-forge
sortedcontainers          2.4.0              pyhd8ed1ab_0    conda-forge
sphinx                    4.4.0              pyh6c4a22f_1    conda-forge
sphinxcontrib-applehelp   1.0.2                      py_0    conda-forge
sphinxcontrib-devhelp     1.0.2                      py_0    conda-forge
sphinxcontrib-htmlhelp    2.0.0              pyhd8ed1ab_0    conda-forge
sphinxcontrib-jsmath      1.0.1                      py_0    conda-forge
sphinxcontrib-qthelp      1.0.3                      py_0    conda-forge
sphinxcontrib-serializinghtml 1.1.5              pyhd8ed1ab_1    conda-forge
sqlite                    3.36.0               h8ffe710_2    conda-forge
stack_data                0.2.0              pyhd8ed1ab_0    conda-forge
statsmodels               0.13.2           py38h6f4d8f0_0    conda-forge
tabulate                  0.8.9              pyhd8ed1ab_0    conda-forge
tbb                       2021.3.0             h2d74725_0    conda-forge
tblib                     1.7.0              pyhd8ed1ab_0    conda-forge
terminado                 0.13.1           py38haa95532_0  
testpath                  0.5.0              pyhd3eb1b0_0  
threadpoolctl             2.2.0              pyh8a188c0_0    conda-forge
tiledb                    2.3.4                h78dabda_0    conda-forge
tk                        8.6.11               h8ffe710_1    conda-forge
toml                      0.10.2                   pypi_0    pypi
tomli                     1.2.2              pyhd8ed1ab_0    conda-forge
toolz                     0.11.1                     py_0    conda-forge
tornado                   6.1              py38h294d835_1    conda-forge
tqdm                      4.63.0             pyhd8ed1ab_0    conda-forge
traitlets                 5.1.1              pyhd8ed1ab_0    conda-forge
typed-ast                 1.5.2            py38h294d835_0    conda-forge
typing_extensions         3.10.0.2           pyha770c72_0    conda-forge
ucrt                      10.0.20348.0         h57928b3_0    conda-forge
urllib3                   1.26.7             pyhd8ed1ab_0    conda-forge
vc                        14.2                 hb210afc_5    conda-forge
vs2015_runtime            14.29.30037          h902a5da_5    conda-forge
wcwidth                   0.2.5              pyh9f0ad1d_2    conda-forge
webencodings              0.5.1                    py38_1  
wheel                     0.37.0             pyhd8ed1ab_1    conda-forge
win_inet_pton             1.1.0            py38haa244fe_2    conda-forge
winpty                    0.4.3                         4  
wrapt                     1.12.1           py38h294d835_3    conda-forge
xarray                    0.21.1             pyhd8ed1ab_0    conda-forge
xerces-c                  3.2.3                h0e60522_2    conda-forge
xlrd                      2.0.1              pyhd8ed1ab_3    conda-forge
xlsxwriter                3.0.3              pyhd8ed1ab_0    conda-forge
xmlrunner                 1.7.7                      py_0    conda-forge
xyzservices               2022.2.0           pyhd8ed1ab_0    conda-forge
xz                        5.2.5                h62dcd97_1    conda-forge
yaml                      0.2.5                he774522_0    conda-forge
zict                      2.0.0                      py_0    conda-forge
zipp                      3.5.0              pyhd8ed1ab_0    conda-forge
zlib                      1.2.11            h62dcd97_1010    conda-forge
zstd                      1.5.0                h6255e5f_0    conda-forge

**Comment by emanuel-schmid** [comment]
Thanks!

I see that you have contextily 1.2 installed. There is an issue with this version anyway, it clashes with our nested use of `contextily.sources`. That's why we have set
```yaml
  - contextily>=1.0,<1.2  # 1.2 has removed the deprecated contextily.sources
```
in requirements/env_climada.yml file.
I suggest you run `conda env update -n climada_env -f requirements/env_climada.yml` and try again.
Although the problem won't be solved then, at least it may be postponed until we are able to upgrade to contextily 1.2.
