### ISSUE TITLE
unit test failure emerging with update to proj 9.0

### ISSUE THREAD

**Issue by emanuel-schmid** [CLIMADA-project/climada_python#381]
7 new failures in https://ied-wcr-jenkins.ethz.ch/job/climada_ci_night/30/

**Comment by petermkr** [comment]
@emanuel-schmid Just came across this issue. Potentially this is done by the recent changes on develop?

**Comment by emanuel-schmid** [comment]
Right, recent changes made this issue obsolete.
@petermkr thanks for pointing this out!
