### ISSUE TITLE
Saving wildfire hazard to hdf5 fails

### ISSUE THREAD

**Issue by carmensteinmann** [CLIMADA-project/climada_python#383]
When trying to save wildfire hazards to hdf5, I encounter the error shown below. I believe it occurs due to the two objects FirmsParams and ProbaParams that form part of the hazard. @chahank as briefly discussed, this might be something that could also pop up with other hazards.

  File "/var/folders/6f/8lfkg8494szgv05jjgwdpkt80000gn/T/ipykernel_90973/184420265.py", line 1, in <module>
    haz_his.write_hdf5(output_path+filename_his)

  File "/Users/carmensteinmann/Documents/CLIMADA/climada_python/climada/hazard/base.py", line 1183, in write_hdf5
    hf_data.create_dataset(var_name, data=var_val)

  File "/Users/carmensteinmann/opt/anaconda3/envs/climada_env/lib/python3.8/site-packages/h5py/_hl/group.py", line 149, in create_dataset
    dsid = dataset.make_new_dset(group, shape, dtype, data, name, **kwds)

  File "/Users/carmensteinmann/opt/anaconda3/envs/climada_env/lib/python3.8/site-packages/h5py/_hl/dataset.py", line 89, in make_new_dset
    tid = h5t.py_create(dtype, logical=1)

  File "h5py/h5t.pyx", line 1663, in h5py.h5t.py_create

  File "h5py/h5t.pyx", line 1687, in h5py.h5t.py_create

  File "h5py/h5t.pyx", line 1747, in h5py.h5t.py_create

TypeError: Object dtype dtype('O') has no native HDF5 equivalent

**Comment by carmensteinmann** [comment]
Changing the respective line in the hazard base at least allows the code to run through:
            elif var_val is not None and var_name != 'pool':
                try:
                    hf_data.create_dataset(var_name, data=var_val)
                except:
                    LOGGER.info('Variable %s not compatible with hdf5', var_val)

**Comment by chahank** [comment]
So could this be an issue with the `pool`?

As a side remark: if you use `try...exepct...`, you must handle the exception correctly. Also, you should not just catch any exception. Finally, you should not use the `LOGGER` to handle exceptions. Please see https://github.com/CLIMADA-project/climada_python/blob/main/doc/guide/Guide_PythonDos-n-Donts.ipynb

**Comment by carmensteinmann** [comment]
@emanuel-schmid Sam mentioned yesterday, that you had advised him to introduce the additional data classes (FirmsParams and ProbaParams) in the wildfire module - do you have an idea how we could still save the hazard in .hdf5 format?

**Comment by emanuel-schmid** [comment]
@carmensteinmann : thanks for raising the issue.
Could you perhaps provide a [minimal reproducible example](https://en.wikipedia.org/wiki/Minimal_reproducible_example)?

**Comment by simonameiler** [comment]
> 

@carmensteinmann have you solved this problem? I obtain the same error when trying to save a TropCyclone hazard file. My issue arises when I concatenate several hazards to a single big hazard object. I paste my code and the error below. My guess, it's related to the centroids...I had to set hazard.centroids.set_meta_to_lat_lon() to use the Hazard.concat() function. 
<img width="488" alt="Screenshot 2022-04-11 at 09 48 21" src="https://user-images.githubusercontent.com/47355042/162689882-01a39f2b-d655-4475-b8d2-7f913156a2dd.png">

<img width="584" alt="Screenshot 2022-04-11 at 09 48 37" src="https://user-images.githubusercontent.com/47355042/162689753-d8d7a466-c5d9-4b59-a22f-34c76a78eab5.png">

**Comment by carmensteinmann** [comment]
@emanuel-schmid here an example for wildfires (using the integration test data in climada_petals/test): [WF_FIRMS.csv](https://github.com/CLIMADA-project/climada_python/files/8463103/WF_FIRMS.csv)

from pathlib import Path
import pandas as pd
from climada_petals.hazard import WildFire

DATA_DIR = (Path(__file__).parent).joinpath('../test/data')
TEST_FIRMS = pd.read_csv(Path.joinpath(DATA_DIR, "WF_FIRMS.csv"))

wf = WildFire()
wf.set_hist_fire_FIRMS(TEST_FIRMS)

filename_fm_out = 'test.hdf5'
wf.write_hdf5(filename_fm_out)

**Comment by emanuel-schmid** [comment]
@carmensteinmann: 👍  thanks!

**Comment by emanuel-schmid** [comment]
PR #419 solves this issue on the level of TypeError exception. But it doesn't solve the problem that class members get lost by writing/reading to/from files. Which probably must be addressed more generally in a consistent way also for other Climada entities and more output/input methods (hdf5, raster, excel?, matlab?, data_api)
