### ISSUE TITLE
LitPop World Bank API link failure

### ISSUE THREAD

**Issue by Sam-Herefordian** [CLIMADA-project/climada_python#399]
Hi all - apologies if this is a very simple fix, but it's a problem with the actual tutorial code which I can't seem to fix.

I think that there's something wrong with the World Bank API that the LitPop function tries to access for some reason.

This is the code I'm using (following Page 28 of the tutorial in the documentation):

from climada.entity import Entity
from climada.entity.exposures import LitPop
#imports the entity class, enabling its usage in this code
#imports LitPop, enabling its use in the exposures part of an entity

Nagasaki_entity = Entity()
#sets up Nagasaki_entity as an entity variable
#ready to have exposures, impact functions (vulnerability curves),
#discount rates and adaption measures added to it

exp_litpop = LitPop.from_countries('Japan', res_arcsec = 120)
exp_litpop.set_geometry_points()

Nagasaki_entity.exposures = exp_litpop

exp_litpop.plot_hexbin(pop_name=True, linewidth=4, buffer=0.1)

It generates a whole long list of errors (repeated instances of this below):
c:\users\sam.gardner\climada_python\climada\entity\exposures\litpop\litpop.py:621: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.

Then it finally gives a RemoteDataError (fully copied and pasted in the attached file
[World Bank URL RemoteDataError Message.txt](https://github.com/CLIMADA-project/climada_python/files/8408935/World.Bank.URL.RemoteDataError.Message.txt)
) - it's unable to read this World Bank URL:
https://api.worldbank.org/v2/countries/JPN/indicators/NY.GDP.MKTP.CD?date=1960%3A2030&per_page=25000&format=json

I'm guessing this URL is used in the underlying Climada code (so it's not an error on my part - apologies if this is misplaced), which is why I wanted to raise it here, in case other people have the same issue in the future.

Hoping someone can help! Thanks in advance 👍 

[World Bank URL RemoteDataError Message.txt](https://github.com/CLIMADA-project/climada_python/files/8408937/World.Bank.URL.RemoteDataError.Message.txt)

**Comment by Sam-Herefordian** [comment]
For context - that exact same code had been working fine last Friday, which is why I'm guessing that the World Bank API has changed and the underlying Climada code hasn't been updated yet?

Again, many many apologies if any of my assertations here are incorrect. I'm not the most experienced coder, so it's entirely possible that I may have got some stuff wrong.

**Comment by frqqyy** [comment]
> For context - that exact same code had been working fine last Friday, which is why I'm guessing that the World Bank API has changed and the underlying Climada code hasn't been updated yet?
> 
> Again, many many apologies if any of my assertations here are incorrect. I'm not the most experienced coder, so it's entirely possible that I may have got some stuff wrong.

I had exactly the same situation: Last Friday, (almost) everything in the Litpop tutorial (https://github.com/CLIMADA-project/climada_python/blob/main/doc/tutorial/climada_entity_LitPop.ipynb) was still working very well, but today, at least the function LitPop.from_countries() doesn't work anymore. I also suppose that the World Bank API has changed.

**Comment by Sam-Herefordian** [comment]
> > For context - that exact same code had been working fine last Friday, which is why I'm guessing that the World Bank API has changed and the underlying Climada code hasn't been updated yet?
> > Again, many many apologies if any of my assertations here are incorrect. I'm not the most experienced coder, so it's entirely possible that I may have got some stuff wrong.
> 
> I had exactly the same situation: Last Friday, (almost) everything in the Litpop tutorial (https://github.com/CLIMADA-project/climada_python/blob/main/doc/tutorial/climada_entity_LitPop.ipynb) was still working very well, but today, at least the function LitPop.from_countries() doesn't work anymore. I also suppose that the World Bank API has changed.

Good to hear that I'm not the only one - was afraid that I'd done something very badly wrong!

**Comment by emanuel-schmid** [comment]
Thanks for the notification.
The problem is rooted in the recent inability of the world bank API to provide GDP data. The according index has been removed mysteriously.
For now, I assume that this is a technical issue which will be fixed soon. If not we'll take measures.

**Comment by emanuel-schmid** [comment]
For the time being, the problem has evaporated. The world bank API provides [GDP data](http://api.worldbank.org/v2/countries/CHE/indicators/NY.GDP.MKTP.CD) again.

**Comment by Sam-Herefordian** [comment]
> For the time being, the problem has evaporated. The world bank API provides [GDP data](http://api.worldbank.org/v2/countries/CHE/indicators/NY.GDP.MKTP.CD) again.

Awesome to see, cheers! Thanks for the help.
