### ISSUE TITLE
comments on merge

### ISSUE THREAD

**Issue by gabrielaznar** [CLIMADA-project/climada_python#4]
Hi Jan,

very nice job! I was having a look to your merge and I have two comments:

- In StormEurope.read_footprints():
  if you have the same centroids for all events, you can consider using the Hazard method _append_all() after having generated the list of new hazards. This will improve performance considerably. As example, this has been implemented in TropCyclone.set_from_tracks().

- Centroids base:
  -  I like the new properties and methods! Could you add some tests to its corresponding test file?
  - the resolution setter could set the _resolution parameter without inputs, just computing the distance between the first two consecutive coordinates (for regular grids this does the job). This way it does not look like you are modifying the coordinates to resample them to the provided resolution.
 
Best,
Gabriela

**Comment by mmyrte** [comment]
Hi Gabriela,

I have finally gotten around to implementing the probabilistic part of the WISC class. I have also written a few test for `hazard.centroids.base`, as well as for a new function in `util.coordinates`. 

- If Thomas agrees to it, I could implement your `_append_all()` method for my reader.
- I will definitely change the resolution setter, that shouldn't take long at all.

best

Jan

**Comment by gabrielaznar** [comment]
Hi Jan,

one question regarding the new function in coordinates get_country_geometries. Isn't it a little redundant with respect to get_land_geometry function? Do we really need both of them? If yes, the first one could probably make use of the last one. Feel free to improve get_land_geometry if necessary.

I see in Jenkins that there's some static code analysis to do to what you submitted. Could you check that?

Thanks!

**Comment by mmyrte** [comment]
I tried _append_all(), but it actually increased processing time by a factor of 5; apparently, it disables some implicit parallelisation. The resolution attribute now simply infers the resolution from the distance between the first two unique values in lat/lan. (In my local branch that is. Not yet ready for primetime.)

I'm closing this issue, we can open a new one if we want for the centroids deriving from geopandas if something comes up. 🙂

**Comment by gabrielaznar** [comment]
Perfect!
