### ISSUE TITLE
Tests fail in impact_funcs

### ISSUE THREAD

**Issue by emanuel-schmid** [CLIMADA-project/climada_python#40]
Three tests fail in develop:
climada.entity.impact_funcs.test.test_imp_fun_set.TestExtend.test_extend_different_extend
climada.entity.impact_funcs.test.test_imp_fun_set.TestExtend.test_extend_equal_same
climada.entity.impact_funcs.test.test_imp_fun_set.TestExtend.test_extend_to_empty_same

**Comment by tovogt** [comment]
Develop is blue! :+1:
