### ISSUE TITLE
Repeated FutureWarning and no output in the 5. block of the Litpop tutorial

### ISSUE THREAD

**Issue by frqqyy** [CLIMADA-project/climada_python#402]
Hello everyone,

In the fifth block of the Litpop tutorial, if the second line is changed to "country = 'MEX'", then the execution of the fifth line "exp_nightlights = LitPop.from_nightlight_intensity(countries=country, res_arcsec=res)" (to get the nightlight intensity) will cause a repeated future warning and no output will be shown.
![litpop MEX 1](https://user-images.githubusercontent.com/71314575/161540478-f8b4b7de-2b43-4891-b07b-94da3c04ce0d.png)
![litpop MEX 2](https://user-images.githubusercontent.com/71314575/161540485-1374f11f-4751-41ea-8843-3a5bd622011a.png)
<img width="715" alt="image" src="https://user-images.githubusercontent.com/71314575/161540569-b76fffdc-bf3b-4584-ac86-5da20af06feb.png">

**Comment by peanutfun** [comment]
The FutureWarning should have been fixed in #443. Is the output still missing?

**Comment by frqqyy** [comment]
> The FutureWarning should have been fixed in #443. Is the output still missing?

The FutureWarning has been fixed indeed. But there is still no output... Should this block last a very long time? (Like more than an hour?)

**Comment by peanutfun** [comment]
It could be that your kernel crashes when executing the block because `LitPop.from_population` may require a too large amount of RAM. I reported a similar issue in #426. Could you check your RAM usage when executing the block? Try reducing the resolution, e.g., set `res` in the beginning of the block to `res = 100`, or even larger.

**Comment by peanutfun** [comment]
Yes, I think that's a good idea

**Comment by peanutfun** [comment]
I opened a new issue discussing a possible memory footprint reduction of the method here: #444
