### ISSUE TITLE
Concat/append function for Hazard yields IndexError

### ISSUE THREAD

**Issue by simonameiler** [CLIMADA-project/climada_python#405]
The attempt to concatenate single hazard objects to one new hazard fails. I wrote the following function that reads in raster files of single TC wind fields and should concatenate them to one big hazard object. I tried to set all obligatory variables but I still obtain an IndexError.

Can anyone check the append hazard function?

<img width="484" alt="Screenshot 2022-04-08 at 15 59 19" src="https://user-images.githubusercontent.com/47355042/162451108-64f36c7e-ddbe-44c0-b3fd-8a5a3c920def.png">

The Error output is the following:
<img width="827" alt="Screenshot 2022-04-08 at 15 57 46" src="https://user-images.githubusercontent.com/47355042/162450795-9ac06d5e-f510-4bca-862b-b9b4fc4dbb33.png">

**Comment by ChrisFairless** [comment]
this might be something to do with centroids not being set. do you still get the error if you run `hazard.centroids.set_meta_to_lat_lon()` on each hazard?

**Comment by simonameiler** [comment]
this solves the problem! Thank you @ChrisFairless
