### ISSUE TITLE
A future warning about geopandas in the tutorial for exposures

### ISSUE THREAD

**Issue by frqqyy** [CLIMADA-project/climada_python#408]
My version of pandas: 1.4.1
![2](https://user-images.githubusercontent.com/71314575/162749523-4c356f71-8dc1-4c6d-b8e1-ed6629e29f7e.png)

**Comment by frqqyy** [comment]
My version of geopandas: 0.10.2
My version of geopandas-base: 0.10.2

**Comment by peanutfun** [comment]
This is an issue in the geopandas code base. There is nothing we can do, other than report this issue to them, similar to #412
