### ISSUE TITLE
A user warning in the tutorial for exposures

### ISSUE THREAD

**Issue by frqqyy** [CLIMADA-project/climada_python#409]
Although the picture is the same as in another issue, but this issue is especially for the second warning: The UserWarning
![2](https://user-images.githubusercontent.com/71314575/162749799-a221c7e7-b446-4f50-8134-1af9e1b90815.png)

**Comment by peanutfun** [comment]
Again, this warning is caused by a GeoPandas internal function. Try updating GeoPandas.

**Comment by emanuel-schmid** [comment]
The recent version of GeoPandas is 0.12, which still has a problem with column names longer than 10 characters.

The offending column is `category_id`, one of the optional, yet dedicated, variables of an Exposures' data frame.
As it is belongs to the data and is written to files we cannot simple make up another name without adapting read/write methods.

What we could do though: remove the two lines from the tutorial. No need to guide people to actions that raise warnings when the actions' results are never consumed.

**Comment by emanuel-schmid** [comment]
Removed warning and offensive lines with c9892d7
