### ISSUE TITLE
A performance warning in the tutorial for exposures

### ISSUE THREAD

**Issue by frqqyy** [CLIMADA-project/climada_python#410]
![3](https://user-images.githubusercontent.com/71314575/162750025-c6345c9d-b7b6-4f7f-9059-27d0d2e561ac.png)

**Comment by peanutfun** [comment]
The Exposure contains an attribute that has no C-type equivalent and therefore cannot be stored efficiently. I think there is nothing that can be done from the CLIMADA side other than suppressing this warning. It just indicates that writing the file might take a bit longer.

**Comment by frqqyy** [comment]
> The Exposure contains an attribute that has no C-type equivalent and therefore cannot be stored efficiently. I think there is nothing that can be done from the CLIMADA side other than suppressing this warning. It just indicates that writing the file might take a bit longer.

Thank you! I'll suppress the warnings.

**Comment by emanuel-schmid** [comment]
Since there is nothing that can be done about it - wouldn't it be more appropriate to suppress it where it's raised?

Something along these lines in the exposures.base module:
```python
import warnings
with warnings.catch_warnings():
    warnings.simplefilter('ignore')
    # code that produces a warning
```
(from https://stackoverflow.com/questions/54768539/suppress-a-python-warning)
