### ISSUE TITLE
Repeated Shapely Deprecation Warnings in the tutorial for exposures

### ISSUE THREAD

**Issue by frqqyy** [CLIMADA-project/climada_python#412]
Although the pictures are the same as in another issue, this issue is especially for the repeated ShapelyDeprecationWarnings.
My version of pandas: 1.4.1
I get the following outputs and warnings if I run this block:
![4 1](https://user-images.githubusercontent.com/71314575/162751594-1b3f9003-5c09-4e85-8f04-f03c969f9ea9.png)
![4 2](https://user-images.githubusercontent.com/71314575/162751610-f44f842b-3813-4790-8c80-7929840d52c9.png)

**Comment by frqqyy** [comment]
> These warnings are due to some type castings within GeoPandas. It is (as far as I can tell) unrelated to the CLIMADA code that causes it in [`set_df_geometry_points()`](https://github.com/CLIMADA-project/climada_python/blob/main/climada/util/coordinates.py#L2377). Updating GeoPandas might fix the issue.

Thank you! I had a look at my geopandas version, it's 0.10.2 and it's apparently the newest version now... Or do you mean that a new version in the future will solve the problem?

**Comment by peanutfun** [comment]
Oops, I did not realise that. I thought a new version might already have fixed the issue because I found no such report in the [GeoPandas repo](https://github.com/geopandas/geopandas). Seems like nobody has reported it yet! From my perception, it's a compatibility issue between GeoPandas and Shapely, and it should be reported in the GeoPandas repository.

**Comment by emanuel-schmid** [comment]
Rumors have it this will disappear with Shapely 2.0: [stackexchange](https://gis.stackexchange.com/questions/433401/shapely-2-0-warning-convert-the-coords-to-a-numpy-array-instead-related-to-ap)
🤞

**Comment by peanutfun** [comment]
Resolved by upgrading to shapely v2
