### ISSUE TITLE
A user warning in the litpop tutorial: Geometry is in a geographic CRS.

### ISSUE THREAD

**Issue by frqqyy** [CLIMADA-project/climada_python#415]
Although multiple user warnings are shown in the screenshots, only the first one should be focused here.
I get the following outputs and warnings if I run this block:
![litpop 1 1](https://user-images.githubusercontent.com/71314575/162840249-2e9e53b9-8f8d-426c-b4bf-c552bb5a9a55.png)
![litpop 1 2](https://user-images.githubusercontent.com/71314575/162840258-63506f12-3050-4c3c-b14e-e9d81de16200.png)

**Comment by frqqyy** [comment]
![litpop 1 3](https://user-images.githubusercontent.com/71314575/162840289-6d29dc96-be36-46b7-96ee-44330fc35aa4.png)

**Comment by frqqyy** [comment]
Although this particular user warning has not been resolved yet, another user warning (You will likely lose important information) has already been suppressed by PR #459

**Comment by peanutfun** [comment]
@emanuel-schmid What's the use of the "fixed" label? Can we close this issue?
