### ISSUE TITLE
Selecting a single TC Track from a TCTracks object containing multiple tropical cyclone paths

### ISSUE THREAD

**Issue by Sam-Herefordian** [CLIMADA-project/climada_python#420]
Quick query since I can't work it out for the life of me:

I've generated 5 synth tracks for Hurricane Sandy and would like to be able to use each of them in isolation of each other (e.g. to use apply_climate_scenario_knu on each of them), but I can't work out for the life of me how to extract single paths from the

```python
tc_ibtracs_id = '2012296N14283'
tc_basin = 'NA'
nb_PT_tracks = 5

tc_actual_PT = TCTracks.from_ibtracs_netcdf(provider='usa', storm_id = tc_ibtracs_id, basin = tc_basin)
tc_actual_PT.equal_timestep()
tc_actual_PT.calc_perturbed_trajectories(nb_synth_tracks = nb_PT_tracks)
tc_actual_PT.plot()
```

This code works fine, it prints all 6 (original + 5 synth) tracks. How do I print and use single tracks from the tc_actual_PT object?

I've tried:

```python
tc_actual_PT(1).plot()
tc_actual_PT[1].plot()
```

Using various while and for loops

I'm able to print the properties of individual tracks with this code (changing the 1 to other numbers from 0-5 of course):
```python
xarr_tc_actual_PT = tc_actual_PT.get_track()
xarr_tc_actual_PT[1]
```

Hoping there's something quite simple that my relative inexperience is hiding from me!

**Comment by tovogt** [comment]
I don't think there is a perfectly elegant solution, but here are two possible solutions to get a list of `TCTracks` objects that only contain a single track each:

```python
single_track_objects = []
for xarr_tr in tc_actual_PT.data:
    track_obj = TCTracks()
    track_obj.data = [xarr_tr]
    single_track_objects.append(track_obj)
```

```python
single_track_objects = [
    tc_actual_PT.subset(dict(name=xarr_tr.name))
    for xarr_tr in tc_actual_PT.data
]
```

**Comment by chahank** [comment]
@Sam-Herefordian : did this solve your issue?

**Comment by Sam-Herefordian** [comment]
> @Sam-Herefordian : did this solve your issue?

Yep it did! Thanks so much. Apologies for the delay, personal and professional life events rather intruded and stole my attention for a fair while.
