### ISSUE TITLE
A future warning in the impact_data tutorial

### ISSUE THREAD

**Issue by frqqyy** [CLIMADA-project/climada_python#423]
My version of pandas (if it's useful): 1.4.1
I was running the following code block and got this warning:
![impact_data 2 1](https://user-images.githubusercontent.com/71314575/163278077-69f88879-3107-42d6-aa09-81847fe6b953.png)
![impact_data 2 2](https://user-images.githubusercontent.com/71314575/163278083-a278a0e7-281d-4592-a93b-b54db2932bce.png)
![impact_data 2 3](https://user-images.githubusercontent.com/71314575/163278088-5dce70b3-8067-4326-bec9-91251b0f0eb1.png)

**Comment by peanutfun** [comment]
@frqqyy The FutureWarning should have been fixed by #443. Could you confirm that?

**Comment by frqqyy** [comment]
> @frqqyy The FutureWarning should have been fixed by #443. Could you confirm that?

Yes :)
