### ISSUE TITLE
LitPop: Suggest using data API wrapper instead of `from_countries`

### ISSUE THREAD

**Issue by peanutfun** [CLIMADA-project/climada_python#426]
On my system, the following code causes a slow memory overflow over several minutes although not much data is pulled from the internet. The process cannot be aborted via keyboard interrupt and is only killed by the OS once the RAM is full.
```python
from climada.entity import LitPop
lp = LitPop.from_countries(["BRA"], fin_mode="pc")
```
Can somebody replicate this behavior? Here's a screenshot from my system (note the slow memory increase and basically no network data exchange):
![Screenshot from 2022-04-19 12-08-50](https://user-images.githubusercontent.com/34276446/163983371-4c7eaf0d-fdd5-45a9-a37b-7f994b2a83a4.png)

**Comment by emanuel-schmid** [comment]
Yes, I can confirm that Litpop Brazil uses about 12G of memory when being created through the `from_countries` method, though it occupies "only" 466M when done,

**Comment by peanutfun** [comment]
Thanks! I was able to load the default LitPop data instead with
```python
from climada.util.api_client import Client
client = Client()
exp = client.get_litpop_default(country=["BRA"])
```
Now the question remains if this issue should be reflected in the documentation. The Exposures documentation [mentions](https://climada-python.readthedocs.io/en/stable/tutorial/climada_entity_LitPop.html#Downloading-existing-LitPop-asset-exposure-data) that existing LitPop data can be downloaded, but this is a manual task and involves downloading ca. 10 GB. The docs do not reference the [API Client wrapper function](https://climada-python.readthedocs.io/en/stable/tutorial/climada_util_api_client.html#The-wrapper-functions-client.get_litpop_default()) that achieves the same task for specific countries automatically. I could write that up and open a PR.

Secondly, it's odd that Python does not respond to the keyboard interrupt when executing `LitPop.from_countries`. Is there any way to enable that?

**Comment by emanuel-schmid** [comment]
> Secondly, it's odd that Python does not respond to the keyboard interrupt when executing LitPop.from_countries. Is there any way to enable that?

I find that odd too. Even more so since I cannot reproduce it. With me, it stops nicely after a second or two.
How did you run the snippet. In an interactive shell? Did you try to stop the process with `kill` as well, or did you just enter ctrl-c?
