### ISSUE TITLE
Pipeline check reports from Jenkins on GitHub

### ISSUE THREAD

**Issue by peanutfun** [CLIMADA-project/climada_python#435]
This issue documents the new features of the Jenkins/GitHub integration and is intended to serve as basis of discussion for improving the reports.

### Overview

We run a [Jenkins](https://www.jenkins.io/) instance which automatically runs tests as soon as new commits are pushed to the Climada respositories (both core and petals) or a PR is created. These tests verify that all code works as expected. The basic tests for each branch include:
* All unit tests
* Linter code analysis

Reporting the results of these tests back to GitHub gives immediate feedback on the code state and compatibility. This is especially for PRs, where passing tests should be a requirement for merging.

### Current Reports (2022-04-29)

When pushing new commits to an existing PR, you will see a new field about the checks popping up at the bottom of the PR view.

First, a new build is queued:
<img width="924" alt="Screenshot 2022-04-28 at 18 03 54" src="https://user-images.githubusercontent.com/34276446/165915663-2a16612d-5822-4703-a504-afe45b2ee1bc.png">

Then, it is executed:
<img width="919" alt="Screenshot 2022-04-28 at 18 09 05" src="https://user-images.githubusercontent.com/34276446/165915890-dcd044ad-77cc-4582-9efd-acb83392a252.png">

If a build succeeds, this will be clearly displayed. Due to the current pipeline configuration, two more check results pop up; the Linter result and the build postprocessing result. If the Linter finds new issues, it will report them as shown below. However, the check is still marked as "Passed".
<img width="923" alt="Screenshot 2022-04-29 at 10 08 13" src="https://user-images.githubusercontent.com/34276446/165916015-24eec6c4-99cd-4560-9b23-ac4efbd11d6f.png">

If unit tests fail, both the main test check and the postprocessing check will be marked as "Failed". The postprocessing check will hint at which test(s) failed:
<img width="921" alt="Screenshot 2022-04-29 at 11 10 18" src="https://user-images.githubusercontent.com/34276446/165916519-ac0b3617-40e4-4dca-8548-24042fd4b04b.png">

In the "Details" view of a check, you can see some more information on why it failed. You will also be directed to the full build information on the Jenkins instance.
<img width="922" alt="Screenshot 2022-04-29 at 11 13 02" src="https://user-images.githubusercontent.com/34276446/165916956-0c539cee-2f3f-4a4b-bdbe-a32e221b9655.png">

Finally, build results are also displayed in PR (and branch) overviews as small icons:

<img width="657" alt="Screenshot 2022-04-29 at 10 14 51" src="https://user-images.githubusercontent.com/34276446/165917048-eb49f7b5-6fce-4d1b-970f-15a0719b45fb.png">

### Open Questions/Issues

* In the current pipeline configuration, the postprocessing task is set up to report which unit tests failed (if any). The report of this is a bit confusing because it is added as a separate check. It might be possible to improve that through the pipeline configuration
* The linter check always succeeds. Should it instead fail if new linter issues are detected?
* Do we also want the results of nightly/installation/dataAPI/notebook checks to be reported on GitHub?

**Comment by chahank** [comment]
> The linter check always succeeds. Should it instead fail if new linter issues are detected?

Maybe if the lint issue is 'high' but not below? Although it might be a bit useless as long as not all the linter issues in the CLIMADA main code-base are resolved.

**Comment by peanutfun** [comment]
I don't think it's necessary to resolve all current issues first, because the linter compares the issues to previous builds. So in my perspective, adding new linter issues should be a (literal) red flag, but simply retaining old ones is of no particular interest for a PR. I like your suggestion to make it dependent on the issue severity. That should be possible.

**Comment by peanutfun** [comment]
@emanuel-schmid Good point! I found it: The warnings plugin requires a defintion of a [reference/baseline build](https://github.com/jenkinsci/warnings-ng-plugin/blob/master/doc/Documentation.md#configure-the-selection-of-the-reference-build-baseline). Specifically, we have to follow instructions to [select a baseline in the target job](https://github.com/jenkinsci/warnings-ng-plugin/blob/master/doc/Documentation.md#selecting-a-baseline-in-the-target-job). This, in turn, is managed by the [Git Forensics](https://plugins.jenkins.io/git-forensics/) plugin which lets you define such a [reference build](https://plugins.jenkins.io/git-forensics/#plugin-content-reference-build).

**Comment by emanuel-schmid** [comment]
Thanks a lot for pointing to the instructions!\
It's installed now an works like it's supposed to, afaic.\
This Jenkins integration really brought our CI one or two levels up! Very nice. 🎉

**Comment by peanutfun** [comment]
Unit test and linter reports seem to be working fine. Closing this issue
