### ISSUE TITLE
Reduce memory footprint of `LitPop.from_countries`

### ISSUE THREAD

**Issue by peanutfun** [CLIMADA-project/climada_python#444]
`LitPop.from_countries` may require a large amount of RAM, depending on the requested resolution and the physical extent of the country. With limited available RAM on a system, this can make certain combinations impossible to compute. Two recent issues reported related problems:
* `from_countries("BRA")` unexpectedly failed #426
* LitPop tutorial not working #401

Is there a way to reduce the memory footprint of the method? My suggestion would be writing intermediate data to an H5 file in the `$HOME/climada/data` directory and then loading the entire file once the computation is finished. Is that feasible?

I have not profiled the memory consumption yet, so I'm not exactly sure what objects cause the heavy RAM load.

**Comment by spjuhel** [comment]
Most of the footprint seems to come from the geopandas.points_from_xy() method.

![Screenshot from 2024-06-25 17-56-13](https://github.com/CLIMADA-project/climada_python/assets/10011382/9b85a713-0b26-45c1-98ab-cead51132fda)

**Comment by peanutfun** [comment]
Thanks for digging into this! Then maybe the issue is not as pronounced as it was when I first reported it. `points_from_xy` benefited a lot from the upgrade to Shapely 2.0. How much was the total amount of RAM used for `from_countries("BRA")`?

**Comment by spjuhel** [comment]
5.6 Go, and 3.1Go from points_from_xy

**Comment by peanutfun** [comment]
Will close this as it is seemingly outdated
