### ISSUE TITLE
Problem with updated data API Haiti hazard?

### ISSUE THREAD

**Issue by ChrisFairless** [CLIMADA-project/climada_python#450]
I downloaded and plotted the TC hazard for Haiti following the data API tutorial. It gives this:

<img width="585" alt="image" src="https://user-images.githubusercontent.com/18582147/168578547-b8a0c29f-b939-41f9-9f84-fd2caaddda70.png">

which is different to the hazard in the API tutorial:

<img width="586" alt="image" src="https://user-images.githubusercontent.com/18582147/168578879-aa1295bd-c3f1-41a2-a88c-14d154dc871f.png">

The smaller island in the centre of the map (Gonave) is missing. It's clearer when you plot the centroids:

<img width="650" alt="image" src="https://user-images.githubusercontent.com/18582147/168579032-1f5bc927-00df-4e2a-bc63-760bc54af09a.png">

I don't know what changed in the API, but I noticed it after the API re-downloaded the data for me with the message:
```
2022-05-16 12:37:11,650 - climada.util.api_client - WARNING - Download failed: /Users/chrisfairless/climada/data/hazard/tropical_cyclone/tropical_cyclone_10synth_tracks_150arcsec_rcp45_HTI_2040/v1/tropical_cyclone_10synth_tracks_150arcsec_rcp45_HTI_2040.hdf5 has the wrong size:9448235 instead of 7781902, retrying...
```

I haven't checked to see if things are different in any other countries.

**Comment by zeliest** [comment]
The country borders are currently defined by pycountry. I originally used another library for country definition, but realised it didn't make sense if everything else is defined with pycountry in climada. So the first hazard may be because the notebook was not updated since then. In general if you are looking at small islands it may make sense to recreate the hazard, @manniepmkam already came across the problem. We could also think of defining centroids differently, happy to update the hazards if you have a good idea on how to define centroids

**Comment by emanuel-schmid** [comment]
> I don't know what changed in the API, but I noticed it after the API re-downloaded the data for me with the message:
> 
> ```
> 2022-05-16 12:37:11,650 - climada.util.api_client - WARNING - Download failed: /Users/chrisfairless/climada/data/hazard/tropical_cyclone/tropical_cyclone_10synth_tracks_150arcsec_rcp45_HTI_2040/v1/tropical_cyclone_10synth_tracks_150arcsec_rcp45_HTI_2040.hdf5 has the wrong size:9448235 instead of 7781902, retrying...
> ```

This is the standard WARNING that's raised when for whatever reason the file in the climada/data folder has a different size than the one given from climada.ethz.ch/data-api/v1/dataset/. It's meant to make sure you have the proper file. Also this implies that when a file is replaced on the server it will be replaced for the client too.

**Comment by ChrisFairless** [comment]
Yes - @zeliest, @manniepmkam and I are working on an updated version for the API.

**Comment by ChrisFairless** [comment]
This has been updated 🙌
