### ISSUE TITLE
AttributeError: partially initialized module 'fiona' has no attribute '_loading' (most likely due to a circular import)

### ISSUE THREAD

**Issue by Maximilian-Nitsche** [CLIMADA-project/climada_python#454]
Hello, 

I am unfortunately not able to finish the installation process by running the unit test as there is an issue with importing Fiona. 

Running: `python -m unittest climada.engine.test.test_impact climada.engine.test.test_cost_benefit` in my activated conda env is returning with 
`Traceback (most recent call last):
  File "/Users/maximiliannitsche/opt/anaconda3/envs/climada/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/Users/maximiliannitsche/opt/anaconda3/envs/climada/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/Users/maximiliannitsche/opt/anaconda3/envs/climada/lib/python3.8/unittest/__main__.py", line 18, in <module>
    main(module=None)
  File "/Users/maximiliannitsche/opt/anaconda3/envs/climada/lib/python3.8/unittest/main.py", line 100, in __init__
    self.parseArgs(argv)
  File "/Users/maximiliannitsche/opt/anaconda3/envs/climada/lib/python3.8/unittest/main.py", line 147, in parseArgs
    self.createTests()
  File "/Users/maximiliannitsche/opt/anaconda3/envs/climada/lib/python3.8/unittest/main.py", line 158, in createTests
    self.test = self.testLoader.loadTestsFromNames(self.testNames,
  File "/Users/maximiliannitsche/opt/anaconda3/envs/climada/lib/python3.8/unittest/loader.py", line 220, in loadTestsFromNames
    suites = [self.loadTestsFromName(name, module) for name in names]
  File "/Users/maximiliannitsche/opt/anaconda3/envs/climada/lib/python3.8/unittest/loader.py", line 220, in <listcomp>
    suites = [self.loadTestsFromName(name, module) for name in names]
  File "/Users/maximiliannitsche/opt/anaconda3/envs/climada/lib/python3.8/unittest/loader.py", line 154, in loadTestsFromName
    module = __import__(module_name)
  File "/Users/maximiliannitsche/opt/anaconda3/envs/climada/lib/python3.8/site-packages/climada/__init__.py", line 25, in <module>
    from .util.constants import *
  File "/Users/maximiliannitsche/opt/anaconda3/envs/climada/lib/python3.8/site-packages/climada/util/__init__.py", line 25, in <module>
    from .constants import *
  File "/Users/maximiliannitsche/opt/anaconda3/envs/climada/lib/python3.8/site-packages/climada/util/constants.py", line 47, in <module>
    from fiona.crs import from_epsg
  File "/Users/maximiliannitsche/opt/anaconda3/envs/climada/lib/python3.8/site-packages/fiona/__init__.py", line 85, in <module>
    with fiona._loading.add_gdal_dll_directories():
AttributeError: partially initialized module 'fiona' has no attribute '_loading' (most likely due to a circular import)`

I precisely followed along the installation guide [here](https://climada-python.readthedocs.io/en/latest/tutorial/climada_installation_step_by_step.html) and [here](https://climada-python.readthedocs.io/en/latest/guide/Guide_Installation.html). However, the error remains for both Conda and pip installation. 

I already checked with [this issue](https://github.com/Toblerity/Fiona/issues/1030#issue-970925415) but changing the order of importing geopandas and fiona does not work. 

Would highly appreciate any help with this issue! Any suggestions?

**Comment by emanuel-schmid** [comment]
Thanks for sharing. could you perhaps post the output of `conda list`?

**Comment by Maximilian-Nitsche** [comment]
Thanks for the response @emanuel-schmid!

Not the same error but 
`ImportError: dlopen(/Users/maximiliannitsche/opt/anaconda3/envs/climada_env/lib/python3.8/site-packages/fiona/ogrext.cpython-38-darwin.so, 0x0002): Symbol not found: _ZSTD_compressBound
  Referenced from: /Users/maximiliannitsche/opt/anaconda3/envs/climada_env/lib/libgdal.30.dylib
  Expected in: /Users/maximiliannitsche/opt/anaconda3/envs/climada_env/lib/libblosc.1.21.1.dylib`.

Here is the package list of the env: 
`# Name                    Version                   Build  Channel
affine                    2.3.1              pyhd8ed1ab_0    conda-forge
attrs                     21.4.0             pyhd8ed1ab_0    conda-forge
bitstring                 3.1.9                    pypi_0    pypi
blosc                     1.21.1               h97e831e_3    conda-forge
bokeh                     2.4.3            py38h50d1736_0    conda-forge
boost-cpp                 1.74.0               hdbf7018_7    conda-forge
bottleneck                1.3.4            py38h4277f33_1    conda-forge
branca                    0.5.0              pyhd8ed1ab_0    conda-forge
brotli                    1.0.9                h5eb16cf_7    conda-forge
brotli-bin                1.0.9                h5eb16cf_7    conda-forge
brotlipy                  0.7.0           py38hed1de0f_1004    conda-forge
bzip2                     1.0.8                h0d85af4_4    conda-forge
c-ares                    1.18.1               h0d85af4_0    conda-forge
ca-certificates           2022.5.18.1          h033912b_0    conda-forge
cached-property           1.5.2                hd8ed1ab_1    conda-forge
cached_property           1.5.2              pyha770c72_1    conda-forge
cairo                     1.16.0            he01c77b_1009    conda-forge
cartopy                   0.20.2           py38h65f7167_1    conda-forge
certifi                   2022.5.18.1      py38h50d1736_0    conda-forge
cffi                      1.15.0           py38h1a44b6c_0    conda-forge
cfgrib                    0.9.9.1            pyhd8ed1ab_2    conda-forge
cfitsio                   4.0.0                hb20e66c_0    conda-forge
cftime                    1.6.0            py38h4277f33_1    conda-forge
charset-normalizer        2.0.12             pyhd8ed1ab_0    conda-forge
click                     8.1.3            py38h50d1736_0    conda-forge
click-plugins             1.1.1                      py_0    conda-forge
cligj                     0.7.2              pyhd8ed1ab_1    conda-forge
climada                   3.1.3.dev0                dev_0    <develop>
cloudpickle               2.1.0              pyhd8ed1ab_0    conda-forge
colorama                  0.4.4              pyh9f0ad1d_0    conda-forge
contextily                1.1.0              pyhd8ed1ab_0    conda-forge
cryptography              37.0.2           py38h0f8513e_0    conda-forge
curl                      7.83.1               h372c54d_0    conda-forge
cycler                    0.11.0             pyhd8ed1ab_0    conda-forge
cytoolz                   0.11.2           py38hed1de0f_2    conda-forge
dask                      2022.5.0           pyhd8ed1ab_0    conda-forge
dask-core                 2022.5.0           pyhd8ed1ab_0    conda-forge
deprecation               2.1.0                    pypi_0    pypi
dill                      0.3.5.1            pyhd8ed1ab_0    conda-forge
distributed               2022.5.0           pyhd8ed1ab_0    conda-forge
eccodes                   2.26.0               hf772d56_0    conda-forge
et_xmlfile                1.0.1                   py_1001    conda-forge
expat                     2.4.8                h96cf925_0    conda-forge
findlibs                  0.0.2              pyhd8ed1ab_0    conda-forge
fiona                     1.8.20           py38h2077077_4    conda-forge
folium                    0.12.1.post1       pyhd8ed1ab_1    conda-forge
font-ttf-dejavu-sans-mono 2.37                 hab24e00_0    conda-forge
font-ttf-inconsolata      3.000                h77eed37_0    conda-forge
font-ttf-source-code-pro  2.038                h77eed37_0    conda-forge
font-ttf-ubuntu           0.83                 hab24e00_0    conda-forge
fontconfig                2.13.94              h10f422b_0    conda-forge
fonts-conda-ecosystem     1                             0    conda-forge
fonts-conda-forge         1                             0    conda-forge
fonttools                 4.33.3           py38h0dd4459_0    conda-forge
freetype                  2.10.4               h4cff582_1    conda-forge
freexl                    1.0.6                h0d85af4_0    conda-forge
fsspec                    2022.5.0           pyhd8ed1ab_0    conda-forge
gdal                      3.4.0           py38hf509309_12    conda-forge
geographiclib             1.52               pyhd8ed1ab_0    conda-forge
geopandas                 0.10.2             pyhd8ed1ab_1    conda-forge
geopandas-base            0.10.2             pyha770c72_1    conda-forge
geopy                     2.2.0              pyhd8ed1ab_0    conda-forge
geos                      3.10.1               he49afe7_1    conda-forge
geotiff                   1.7.0                h9e3163f_5    conda-forge
gettext                   0.19.8.1          hd1a6beb_1008    conda-forge
giflib                    5.2.1                hbcb3906_2    conda-forge
h5py                      3.6.0           nompi_py38h9f21798_100    conda-forge
haversine                 2.5.1              pyhd8ed1ab_0    conda-forge
hdf4                      4.2.15               hefd3b78_3    conda-forge
hdf5                      1.12.1          nompi_ha60fbc9_104    conda-forge
heapdict                  1.0.1                      py_0    conda-forge
icu                       69.1                 he49afe7_0    conda-forge
idna                      3.3                pyhd8ed1ab_0    conda-forge
importlib-metadata        4.11.4           py38h50d1736_0    conda-forge
importlib_metadata        4.11.4               hd8ed1ab_0    conda-forge
jasper                    2.0.33               h013e400_0    conda-forge
jbig                      2.1               h0d85af4_2003    conda-forge
jinja2                    3.1.2              pyhd8ed1ab_0    conda-forge
joblib                    1.1.0              pyhd8ed1ab_0    conda-forge
jpeg                      9e                   h5eb16cf_1    conda-forge
json-c                    0.15                 hcb556a6_0    conda-forge
kealib                    1.4.14               ha22a8b1_3    conda-forge
kiwisolver                1.4.2            py38h8b7791e_1    conda-forge
krb5                      1.19.3               hb49756b_0    conda-forge
lcms2                     2.12                 h577c468_0    conda-forge
lerc                      3.0                  he49afe7_0    conda-forge
libaec                    1.0.6                he49afe7_0    conda-forge
libblas                   3.9.0           14_osx64_openblas    conda-forge
libbrotlicommon           1.0.9                h5eb16cf_7    conda-forge
libbrotlidec              1.0.9                h5eb16cf_7    conda-forge
libbrotlienc              1.0.9                h5eb16cf_7    conda-forge
libcblas                  3.9.0           14_osx64_openblas    conda-forge
libcurl                   7.83.1               h372c54d_0    conda-forge
libcxx                    14.0.3               hc203e6f_0    conda-forge
libdap4                   3.20.6               h3e144a0_2    conda-forge
libdeflate                1.10                 h0d85af4_0    conda-forge
libedit                   3.1.20191231         h0678c8f_2    conda-forge
libev                     4.33                 haf1e3a3_1    conda-forge
libffi                    3.4.2                h0d85af4_5    conda-forge
libgdal                   3.4.0               h3ab75b0_12    conda-forge
libgfortran               5.0.0           9_3_0_h6c81a4c_23    conda-forge
libgfortran5              9.3.0               h6c81a4c_23    conda-forge
libglib                   2.70.2               hf1fb8c0_4    conda-forge
libiconv                  1.16                 haf1e3a3_0    conda-forge
libkml                    1.3.0             h8fd9edb_1014    conda-forge
liblapack                 3.9.0           14_osx64_openblas    conda-forge
libllvm11                 11.1.0               hd011deb_3    conda-forge
libnetcdf                 4.8.1           nompi_h6609ca0_102    conda-forge
libnghttp2                1.47.0               h942079c_0    conda-forge
libopenblas               0.3.20          openmp_hb3cd9ec_0    conda-forge
libpng                    1.6.37               h7cec526_2    conda-forge
libpq                     14.2                 hea3049e_0    conda-forge
librttopo                 1.1.0                h0d74fd6_8    conda-forge
libspatialindex           1.9.3                he49afe7_4    conda-forge
libspatialite             5.0.1               h24415ee_12    conda-forge
libssh2                   1.10.0               h52ee1ee_2    conda-forge
libtiff                   4.3.0                h17f2ce3_3    conda-forge
libwebp                   1.2.2                h28dabe5_0    conda-forge
libwebp-base              1.2.2                h0d85af4_1    conda-forge
libxcb                    1.13              h0d85af4_1004    conda-forge
libxml2                   2.9.12               h7e28ab6_1    conda-forge
libxslt                   1.1.33               h1acebb3_3    conda-forge
libzip                    1.8.0                h8b0c345_1    conda-forge
libzlib                   1.2.11            h6c3fc93_1014    conda-forge
llvm-openmp               14.0.3               ha654fa7_0    conda-forge
llvmlite                  0.38.1           py38h1e1b051_0    conda-forge
locket                    1.0.0              pyhd8ed1ab_0    conda-forge
lxml                      4.8.0            py38hed1de0f_2    conda-forge
lz4                       4.0.0            py38h5cd37e2_2    conda-forge
lz4-c                     1.9.3                he49afe7_1    conda-forge
mapclassify               2.4.3              pyhd8ed1ab_0    conda-forge
markupsafe                2.1.1            py38hed1de0f_1    conda-forge
matplotlib                3.5.2            py38h50d1736_0    conda-forge
matplotlib-base           3.5.2            py38h1b6b9d1_0    conda-forge
mercantile                1.2.1              pyhd8ed1ab_0    conda-forge
msgpack-python            1.0.3            py38h8b7791e_1    conda-forge
multiprocess              0.70.12.2        py38hed1de0f_2    conda-forge
munch                     2.5.0                      py_0    conda-forge
munkres                   1.1.4              pyh9f0ad1d_0    conda-forge
ncurses                   6.3                  h96cf925_1    conda-forge
netcdf4                   1.5.8           nompi_py38h465ef27_101    conda-forge
networkx                  2.8.2              pyhd8ed1ab_0    conda-forge
nspr                      4.32                 hcd9eead_1    conda-forge
nss                       3.77                 hfce436b_0    conda-forge
numba                     0.55.1           py38h1f551d2_1    conda-forge
numexpr                   2.8.0            py38hb872667_2    conda-forge
numpy                     1.21.6           py38h57719e9_0    conda-forge
openjpeg                  2.4.0                h6e7aa92_1    conda-forge
openpyxl                  3.0.9              pyhd8ed1ab_0    conda-forge
openssl                   1.1.1o               hfe4f2af_0    conda-forge
overpy                    0.6                      pypi_0    pypi
packaging                 21.3               pyhd8ed1ab_0    conda-forge
pandas                    1.4.2            py38hb872667_1    conda-forge
pandas-datareader         0.10.0             pyh6c4a22f_0    conda-forge
partd                     1.2.0              pyhd8ed1ab_0    conda-forge
pathos                    0.2.8              pyhd8ed1ab_0    conda-forge
patsy                     0.5.2              pyhd8ed1ab_0    conda-forge
pcre                      8.45                 he49afe7_0    conda-forge
peewee                    3.14.10                  pypi_0    pypi
pillow                    9.1.1            py38h21af888_0    conda-forge
pint                      0.19.2             pyhd8ed1ab_0    conda-forge
pip                       22.1.1             pyhd8ed1ab_0    conda-forge
pixman                    0.40.0               hbcb3906_0    conda-forge
poppler                   21.11.0              h9573804_0    conda-forge
poppler-data              0.4.11               hd8ed1ab_0    conda-forge
postgresql                14.2                 he8fe76e_0    conda-forge
pox                       0.3.1              pyhd8ed1ab_0    conda-forge
ppft                      1.7.6.5            pyhd8ed1ab_0    conda-forge
proj                      8.2.0                h1512c50_0    conda-forge
psutil                    5.9.1            py38h0dd4459_0    conda-forge
pthread-stubs             0.4               hc929b4f_1001    conda-forge
pybufrkit                 0.2.19                   pypi_0    pypi
pycountry                 20.7.3             pyh9f0ad1d_0    conda-forge
pycparser                 2.21               pyhd8ed1ab_0    conda-forge
pyepsg                    0.4.0                      py_0    conda-forge
pyopenssl                 22.0.0             pyhd8ed1ab_0    conda-forge
pyparsing                 3.0.9              pyhd8ed1ab_0    conda-forge
pyproj                    3.3.0            py38h9fb0c80_0    conda-forge
pyshp                     2.3.0              pyhd8ed1ab_0    conda-forge
pysocks                   1.7.1            py38h50d1736_5    conda-forge
pytables                  3.7.0            py38h5215406_0    conda-forge
python                    3.8.13          h394c593_0_cpython    conda-forge
python-dateutil           2.8.2              pyhd8ed1ab_0    conda-forge
python-eccodes            1.4.0            py38h4277f33_1    conda-forge
python_abi                3.8                      2_cp38    conda-forge
pytz                      2022.1             pyhd8ed1ab_0    conda-forge
pyxlsb                    1.0.9              pyhd8ed1ab_0    conda-forge
pyyaml                    6.0              py38hed1de0f_4    conda-forge
rasterio                  1.2.10           py38hc5381f3_3    conda-forge
readline                  8.1                  h05e3726_0    conda-forge
requests                  2.27.1             pyhd8ed1ab_0    conda-forge
rtree                     1.0.0            py38hc59ffc2_1    conda-forge
salib                     1.3.12                   pypi_0    pypi
scikit-learn              1.1.1            py38h4ade575_0    conda-forge
scipy                     1.8.1            py38h2c99f22_0    conda-forge
setuptools                62.3.2           py38h50d1736_0    conda-forge
shapely                   1.8.0            py38hf12dc69_4    conda-forge
six                       1.16.0             pyh6c4a22f_0    conda-forge
snappy                    1.1.9                h6e38e02_1    conda-forge
snuggs                    1.4.7                      py_0    conda-forge
sortedcontainers          2.4.0              pyhd8ed1ab_0    conda-forge
sqlite                    3.38.5               hd9f0692_0    conda-forge
statsmodels               0.13.2           py38hbe852b5_0    conda-forge
style                     1.1.0                    pypi_0    pypi
tabulate                  0.8.9              pyhd8ed1ab_0    conda-forge
tblib                     1.7.0              pyhd8ed1ab_0    conda-forge
threadpoolctl             3.1.0              pyh8a188c0_0    conda-forge
tiledb                    2.5.3                hca4410a_0    conda-forge
tk                        8.6.12               h5dbffcc_0    conda-forge
toolz                     0.11.2             pyhd8ed1ab_0    conda-forge
tornado                   6.1              py38hed1de0f_3    conda-forge
tqdm                      4.64.0             pyhd8ed1ab_0    conda-forge
typing_extensions         4.2.0              pyha770c72_1    conda-forge
tzcode                    2022a                h5eb16cf_0    conda-forge
tzdata                    2022a                h191b570_0    conda-forge
unicodedata2              14.0.0           py38hed1de0f_1    conda-forge
update                    0.0.1                    pypi_0    pypi
urllib3                   1.26.9             pyhd8ed1ab_0    conda-forge
wheel                     0.37.1             pyhd8ed1ab_0    conda-forge
xarray                    2022.3.0           pyhd8ed1ab_0    conda-forge
xerces-c                  3.2.3                h6564042_4    conda-forge
xlrd                      2.0.1              pyhd8ed1ab_3    conda-forge
xlsxwriter                3.0.3              pyhd8ed1ab_0    conda-forge
xmlrunner                 1.7.7                      py_0    conda-forge
xorg-libxau               1.0.9                h35c211d_0    conda-forge
xorg-libxdmcp             1.1.3                h35c211d_0    conda-forge
xyzservices               2022.4.0           pyhd8ed1ab_0    conda-forge
xz                        5.2.5                haf1e3a3_1    conda-forge
yaml                      0.2.5                h0d85af4_2    conda-forge
zict                      2.2.0              pyhd8ed1ab_0    conda-forge
zipp                      3.8.0              pyhd8ed1ab_0    conda-forge
zlib                      1.2.11            h6c3fc93_1014    conda-forge
zstd                      1.5.2                ha9df2e0_1    conda-forge`

Does this help?

**Comment by emanuel-schmid** [comment]
Thanks! This helps insofar as by now we know that your conda environment is broken. Why that is so, is hard to tell.
At this point the only suggestions I can come up with is to power cycle your computer, and at last, to re-install conda and start from scratch. Sorry. 
See
- https://docs.anaconda.com/anaconda/install/uninstall/
- https://docs.anaconda.com/anaconda/install/mac-os/

You may want to install just fiona and gdal at first and check right afterwards whether that succeeded. To do so, execute these commands:
```bash
conda activate
conda create -c conda-forge -n gdal-test python=3.8 gdal=3.4.0 fiona=1.8.20
conda activate climada
python -c 'import fiona; print(fiona.__file__)'
```
If this eventually prints `/Users/maximiliannitsche/opt/anaconda3/envs/climada/lib/python3.8/site-packages/fiona/__init__.py`, all is fine and you can continue with the climada installation like this:
```bash
conda env update -f requirements/env_climada.yml -n climada
pip install climada
```
If it again results in an error, you're still in trouble. 😨

**Comment by Maximilian-Nitsche** [comment]
Actually installing the two packages before going through the installation process worked! Thank you @emanuel-schmid for the help!
