### ISSUE TITLE
write/to_hdf5 methods increase size of existing files

### ISSUE THREAD

**Issue by emanuel-schmid** [CLIMADA-project/climada_python#457]
When `Exposures.write_hdf5` is called with a path to an existing file, the result is not the same as when it's called with a path that a priori leads nowhere. Calling it several times in a row leads to a steadily increased file size.
Looks like the `pandas.HDFStore` object is not by default in the mood for cleaning up and freeing diskspace.

Therefore I suggest to remove any existing file before calling `Exposures.write_hdf5` or `UncOutput.to_hdf5`

**Comment by chahank** [comment]
I think by default, if the file already exists, it appends to it whatever is being written. Instead of removing files by default, should there be a flag? Or maybe an error if the file already exists? I am always a bit worried when files get overwritten by default without warning.

**Comment by emanuel-schmid** [comment]
Yes there is a flag, see #458. 
I'm not really worried about overwriting an existing file. None of the standard file writing methods (e.g. stdio, pandas, ...) do that and we'd have a hard time to raise such warnings consequently.

**Comment by peanutfun** [comment]
Resolved by #458
