### ISSUE TITLE
Future enhancement ideas for the lines & polygons util module

### ISSUE THREAD

**Issue by Evelyn-M** [CLIMADA-project/climada_python#472]
This is a post-merger collection of improvement / enhancement points for the `util/lines_polys_handler` module (to be extended / amended):

- Allowing mixed (line/point/polygon) geodataframes for the disaggregation to a fixed user-given grid. Currently this works only for polygon-containing gdfs. Concerns function `exp_geom_to_grid ` and respective sub-functions. 

- Extend plotting methods beyond eai_exp to a general `plot_impact_geom` function where we have as a kwarg the different usual impact variable options eai, at_event, aai, etc. Concerns function `plot_eai_exp_geom `

- Extend potential aggregation methods beyond summing the point impacts within a corresponding geometry. Options could be returning the min and max.

- Allow for mixed-geometry types incl. points in the geodataframes that are to be disaggregated.

**Comment by peanutfun** [comment]
@Evelyn-M is this still relevant or can this be discussed over at the osm-flex repo?
