### ISSUE TITLE
Resources: Restructuring this Repository

### ISSUE THREAD

**Issue by mmyrte** [CLIMADA-project/climada_python#48]
Both issue #46 (util functions) and #37 (config & constants) have referred to the topic of "where do we keep what". If we (or probably just @emanuel-schmid 😀) are going to package climada for distribution, we're going to need to reorganise the repository. According to the [official docs](https://packaging.python.org/tutorials/packaging-projects/), this is the structure a package should follow:

```
packaging_tutorial
├── LICENSE
├── README.md
├── example_pkg
│   └── __init__.py
├── setup.py
└── tests
```

_I'll use `climada_python` as the root `/` from here on. Also, this is just a proposal, forgive my absolute language._

`/data`, `/script`, and `/doc/tutorial` need to move into other github repos. 

- I find the [climada_papers](https://github.com/CLIMADA-project/climada_papers) ill suited for tutorials, so we'd need a new climada_tuts. `/script` and `/data/demo` can be moved there as well. 
- The `/data/system`, as discussed in #37, should be created on the user's machine, like e.g. `$HOME/.climada`; we should probably check the licenses and host it outside a repository.
- The data necessary for testing needs to be radically minimised and put into `/tests`, along with all the unit tests now living in `/climada` subdirs.

I think this topic is quite involved and needs _a lot_ of reading up on the formats of packaging formats for [pypi/wheel/setuptools ](https://packaging.python.org/) and [conda/conda-forge/conda-build](https://docs.conda.io/projects/conda-build/en/latest/index.html). I only stuck my toes into it and would be glad to let @emanuel-schmid decide for all of us, because I imagine that none of us has the knowledge or the time to find best practices and implement them.

**Comment by chahank** [comment]
Good summary. I think we could have two repositories then. One for the package, and one for the rest. For me tutorials, papers etc. are in the same category.

**Comment by tovogt** [comment]
Thanks for the suggestions!

Just for reference, see the following list of the 100 largest files in the repository (command line from https://stackoverflow.com/questions/10622179/how-to-find-identify-large-commits-in-git-history):

<details><summary>Click to expand the list of 100 largest files in the repository's history</summary>
<p>

```$ git rev-list --objects --all | git cat-file --batch-check='%(objecttype) %(objectname) %(objectsize) %(rest)' | sed -n 's/^blob //p' | sort --numeric-sort --key=2 | cut -c 1-12,41- | $(command -v gnumfmt || echo numfmt) --field=2 --to=iec-i --suffix=B --padding=7 --round=nearest | tail -100
Commit        Size   Path
------------------------------------------------------------------------------------
afdf9d250244  1,5MiB data/supplychain/USA_services_XXX
7b0bde40f2d8  1,5MiB doc/tutorial/climada_entity_Exposures.ipynb
7b5cadab5cfa  1,6MiB doc/tutorial/climada_entity_Exposures.ipynb
c49fc7111e0d  1,6MiB doc/tutorial/climada_entity_Exposures.ipynb
71a04b0332ed  1,6MiB doc/tutorial/climada_entity_Exposures.ipynb
7771f3263d57  1,6MiB doc/tutorial/climada_entity_Exposures.ipynb
2f7e0ca73836  1,6MiB script/tutorial/1_main_climada.ipynb
607362854358  1,6MiB doc/tutorial/climada_entity_LitPop.ipynb
c90a0f3284d9  1,6MiB data/supplychain/FRA_agriculture_XXX
7a2a1295d6b6  1,6MiB doc/tutorial/climada_entity_LitPop.ipynb
358001e6d875  1,6MiB doc/tutorial/climada_entity_LitPop.ipynb
805f29c38ebc  1,6MiB doc/tutorial/climada_entity_LitPop.ipynb
7a9e5af40035  1,6MiB doc/tutorial/climada_entity_LitPop.ipynb
ba2fb96b6ee3  1,6MiB doc/tutorial/climada_entity_LitPop.ipynb
9b738e384042  1,6MiB doc/tutorial/climada_entity_LitPop.ipynb
04647bd8b895  1,6MiB doc/tutorial/climada_entity_LitPop.ipynb
bdef60960e28  1,6MiB doc/tutorial/climada_entity_LitPop.ipynb
9a3fa22242eb  1,7MiB doc/tutorial/climada_entity_LitPop.ipynb
dc26c1560790  1,7MiB data/supplychain/ROW_agriculture_XXX
b78a959c7569  1,7MiB doc/tutorial/climada_entity_LitPop.ipynb
56008533bd4a  1,7MiB data/demo/California_firms_2016_viirs.csv
74c6286c0d8f  1,7MiB data/supplychain/AUS_agriculture_XXX
9b16d9f4c6f8  1,7MiB script/workshop_I/Hands-on_I.ipynb
1ccabe803c86  1,8MiB data/supplychain/TUR_agriculture_XXX
bc03576dc17f  1,8MiB script/tutorial/climada_entity_Exposures.ipynb
c95ded79ebab  1,8MiB doc/tutorial/climada_entity_Exposures.ipynb
944049d01093  1,8MiB data/supplychain/CAN_agriculture_XXX
2807d06acd33  1,9MiB data/system/NatID_grid_0150as.nc
05b8b073fa47  2,0MiB doc/tutorial/climada_entity_BlackMarble.ipynb
3e361005ea56  2,0MiB doc/tutorial/climada_entity_BlackMarble.ipynb
4048178c77d3  2,0MiB doc/tutorial/climada_entity_BlackMarble.ipynb
d3ab436b04f1  2,0MiB data/supplychain/MEX_agriculture_XXX
7a6c555d6760  2,1MiB script/tutorial/climada_entity_LitPop.ipynb
2f9cdd203bd9  2,1MiB script/tutorial/climada_entity_LitPop.ipynb
ae226ed99cff  2,1MiB climada/test/data/buildings_47_8.dbf
52a3b730ef46  2,1MiB script/tutorial/climada_entity_LitPop.ipynb
c9dd435c0d1e  2,1MiB doc/tutorial/climada_entity_LitPop.ipynb
ab7e168310ef  2,1MiB script/tutorial/climada_entity_LitPop.ipynb
82ba67d2d905  2,1MiB script/tutorial/climada_entity_LitPop.ipynb
c1d248a585bd  2,2MiB data/demo/h08_gfdl-esm2m_ewembi_historical_histsoc_co2_dis_global_daily_DEMO_FR_2001_2003.nc
1953d6fe0d8c  2,3MiB data/supplychain/CAN_services_XXX
b40a3cf5ccd9  2,4MiB data/supplychain/IDN_agriculture_XXX
b7ea0f4a34c5  2,6MiB data/system/GDP2Asset_converter_2.5arcmin.nc
febc69be140c  2,7MiB script/tutorial/5_blackmarble.ipynb
f881dc1edee9  2,7MiB script/tutorial/climada_entity_LitPop.ipynb
1170d76eb438  2,7MiB script/tutorial/climada_entity_LitPop.ipynb
acd637415a02  2,7MiB script/tutorial/climada_entity_LitPop.ipynb
dd1190329814  2,7MiB script/tutorial/climada_entity_LitPop.ipynb
b920c0a578ef  2,7MiB script/tutorial/climada_entity_LitPop.ipynb
d29e8ea548a2  2,8MiB doc/tutorial/climada_entity_BlackMarble.ipynb
aaefe1ae6818  2,8MiB script/tutorial/climada_entity_BlackMarble.ipynb
23756ddc625a  2,8MiB script/tutorial/climada_entity_BlackMarble.ipynb
32b12fe30ba5  2,8MiB script/tutorial/climada_entity_BlackMarble.ipynb
cc64db7d153d  3,1MiB climada/engine/test/data/supplychain/test_hazard
b6ac52e0df52  3,1MiB script/tutorial/5_blackmarble.ipynb
2ca5f50c405e  3,4MiB data/demo/earth_engine/landcover.tif
cfc1110ac778  3,4MiB data/supplychain/IND_agriculture_XXX
3389da6ed038  3,7MiB data/demo/h08_gfdl-esm2m_ewembi_historical_histsoc_co2_dis_global_daily_DEMO_FR_2001_2005.nc
68c0e2ec19be  3,8MiB script/applications/eca_san_salvador/San_Salvador_Risk.ipynb
8416b7843ecf  3,9MiB data/demo/tc_fl_1975_2011.h5
9c72e4b14e59  4,0MiB data/supplychain/RUS_services_XXX
4a4f2ae421b8  4,3MiB data/supplychain/RUS_agriculture_XXX
3758d01539d9  4,5MiB data/demo/WS_ERA40.mat
03ecae28d707  4,8MiB data/supplychain/BRA_agriculture_XXX
e528b62cb0bc  4,8MiB script/applications/eca_san_salvador/San_Salvador_Risk.ipynb
ab730b2e6070  5,3MiB script/applications/eca_san_salvador/San_Salvador_Risk.ipynb
2304b65ad0ba  5,3MiB script/applications/eca_san_salvador/San_Salvador_Risk.ipynb
1a693d23e8df  5,4MiB data/supplychain/CHN_agriculture_XXX
799b5f35455a  5,5MiB script/applications/eca_san_salvador/San_Salvador_Risk.ipynb
835ed0d1e415  5,5MiB script/applications/eca_san_salvador/San_Salvador_Risk.ipynb
0efdda0ef036  5,7MiB data/supplychain/USA_agriculture_XXX
4fe57575bcd9  5,8MiB script/applications/eca_san_salvador/San_Salvador_Risk.ipynb
9ce0afd9b4f4  5,9MiB data/demo/flddph_WaterGAP2_miroc5_historical_flopros_gev_picontrol_2000_0.1.nc
1e54fca74b5f  6,2MiB data/demo/fldfrc_WaterGAP2_miroc5_historical_flopros_gev_picontrol_2000_0.1.nc
f3aed133427c  6,9MiB script/applications/eca_san_salvador/San_Salvador_Risk-Copy1.ipynb
6719ca15aee3  7,1MiB data/demo/atl_prob.mat
7f603961260f  7,6MiB climada/hazard/test/data/test_global_landslide_nowcast_20190508.tif
589b0ef33943  7,7MiB climada/hazard/test/data/test_global_landslide_nowcast_20190501.tif
2675811213d0  7,8MiB climada/hazard/test/data/test_global_landslide_nowcast_20190509.tif
b0c1cd004b06  8,1MiB climada/hazard/test/data/cropping_test_LS.tif
cee69928a590  9,0MiB dist/climada-0.0.1.tar.gz
ca4c7071c104   10MiB climada/hazard/test/data/Victoria_firms.csv
a64e0f3e5c24   13MiB data/F101992.v4b_web.stable_lights.avg_vis.tif.gz
b9e8e61a2eec   14MiB climada/test/data/system/admin0.mat
7390384f5085   15MiB data/system/ls_pr_NGI_UNEP/ls_pr.tif
1678be6b232f   15MiB climada/test/data/GLB_NatID_grid_0360as_adv_1.mat
0fa15d7d60ef   15MiB climada/test/data/GLB_NatID_grid_0360as_adv_2.mat
2a1a77be0dc8   15MiB data/system/GLB_NatID_grid_0360as_adv_2.mat
7bc480bd96d2   16MiB data/F152007.v4b_web.stable_lights.avg_vis.tif.gz
93c8b4eb9131   16MiB data/supplychain/ROW_services_XXX
3109d2e4bf3b   17MiB data/F162007.v4b_web.stable_lights.avg_vis.tif.gz
2a5a60d34a27   17MiB data/demo/earth_engine/rgb_zurich.tif
8b8bc642dfa6   18MiB data/F182012.v4c_web.stable_lights.avg_vis.tif.gz
439e36b6bb9a   24MiB data/system/IBTrACS.ALL.v04r00.nc
0bd3d429871b   25MiB data/system/ECLIPSE_base_CLE_V5a_NOx.nc
5e8e2e083e95   31MiB climada/hazard/test/data/nasa_global_landslide_catalog_point.dbf
864876f19e62   41MiB data/demo/gdp2asset_demo_exposure.nc
3026099e8d97   51MiB data/supplychain/GLB_agriculture_XXX
090d7bb7444a   82MiB data/supplychain/WIOT2014_Nov16_ROW.xlsx
7f0d4a40ca5d   91MiB data/supplychain/sup_ib_hazard_default
```
</p>
</details>

**Comment by emanuel-schmid** [comment]
Thanks for the suggestions and thanks for the list of large files!
- for registering climada-python in pypi.org, it's necessary to have the overall filesize below 60MB. This includes everything below `/climada`. Therefore we need to radically minimise these files indeed.
- _ceterum censeo_ for seamless operation, we need to make sure nothing is written to any location below the source foulder `/climada`
- on the other hand, `/data`, `/script` and `/doc/tutorial` are not disturbing the packaging, at least not for pip but from what I've seen not for conda either. For me, they can stay where they are.
- `/tests` is seemingly just a placeholder directory for the tutorial, I think it's just to demonstrate that not everything must be included in the package. I don't think we need it.

**Comment by mmyrte** [comment]
My argument for moving big files away from `/data` etc. is to make the cloning of the repo more lightweight; this would also mean deleting large files from history, i.e rewriting it. I understand if you want to leave that particular stone unturned. We have the `climada.ethz.ch` domain/VM already, so we could use that to host (slightly) larger files.

The argument for keeping `/tests` is that we can move the testing code there - AFAIK, the CI would still run off of this repo instead of the package. I personally would appreciate the clearer separation of actual programme logic and tests, but if you want users to be able to validate the correct functioning of the software on their machines, then it's a no-go. In that case, I would consider it curteous to the user to only download an archive of test files if the tests are indeed executed.

**Comment by tovogt** [comment]
About the large files:
- Repository size is currently around **~460 MiB** (use `git count-objects -vH`).
- Removing all files larger than 10 MiB (see my list above) reduces the repository size to only **~180 MiB**
- The largest files are due to @KasparTo's changes in February 2020 to the branch `feature/supplychain`. Removing that branch reduces the repository size already to **~280 MiB**. Can you comment whether we can somehow get rid of those huge files, @KasparTo?
- An acceptable size for a git-repository is around 100 MiB, in my opinion. That means, it's still necessary to also consider the files of smaller size than 10 MiB...

**Comment by tovogt** [comment]
This is a follow-up about the large files:

Here is a list of large files that are obsolete (i.e., can be safely removed because they have already been replaced), removing those **reduces repository size by 110 MiB** already:
<details><summary>Click to expand the list of obsolete files in the git history</summary>
<p>

```
script/applications/eca_san_salvador/San_Salvador_Risk-Copy1.ipynb
climada/hazard/test/data/cropping_test_LS.tif
dist/climada-0.0.1.tar.gz
data/F101992.v4b_web.stable_lights.avg_vis.tif.gz
climada/test/data/system/admin0.mat
climada/test/data/GLB_NatID_grid_0360as_adv_1.mat
climada/test/data/GLB_NatID_grid_0360as_adv_2.mat
data/F152007.v4b_web.stable_lights.avg_vis.tif.gz
data/F162007.v4b_web.stable_lights.avg_vis.tif.gz
data/F182012.v4c_web.stable_lights.avg_vis.tif.gz
data/demo/gdp2asset_demo_exposure.nc
```
</p></details>

Here is a list of the files larger than 3 MiB (except those in `feature/supplychain`)  and the people who added them to the repository. Can those people please replace the files by smaller ones or give reasoning why the files have to be that large?

- `climada/hazard/test/data/Victoria_firms.csv` (bush fire hazard, originally Marine Perus, no GitHub-account)
- `data/demo/h08_gfdl-esm2m_ewembi_historical_histsoc_co2_dis_global_daily_DEMO_FR_2001_2005.nc` (@sameberenz)
- `data/demo/flddph_WaterGAP2_miroc5_historical_flopros_gev_picontrol_2000_0.1.nc` (@ingajsa)
- `data/demo/fldfrc_WaterGAP2_miroc5_historical_flopros_gev_picontrol_2000_0.1.nc` (@ingajsa)
- `climada/hazard/test/data/test_global_landslide_nowcast_20190508.tif` (@Evelyn-M)
- `climada/hazard/test/data/test_global_landslide_nowcast_20190501.tif` (@Evelyn-M)
- `climada/hazard/test/data/test_global_landslide_nowcast_20190509.tif` (@Evelyn-M)
- `data/system/ls_pr_NGI_UNEP/ls_pr.tif` (@Evelyn-M)
- `climada/hazard/test/data/nasa_global_landslide_catalog_point.dbf` (@Evelyn-M)
- `data/demo/earth_engine/landcover.tif` (@raychpistache)
- `data/demo/earth_engine/rgb_zurich.tif` (@raychpistache)

Here is a list of files where we can save some space without removing:

- `script/tutorial/5_blackmarble.ipynb` (the file might be okay, but there are several obsolete revisions in the git history)
- `script/applications/eca_san_salvador/San_Salvador_Risk.ipynb` (the file might be okay, but there are several obsolete revisions in the git history)
- `data/demo/tc_fl_1975_2011.h5` (used in several tests, could probably be reduced in size easily)
- `data/demo/atl_prob.mat` (used in many tests, could probably be reduced in size easily)
- `data/demo/WS_ERA40.mat` (never used in the code, any ideas if this is needed?)
- `data/system/GLB_NatID_grid_0360as_adv_2.mat` (has already been replaced by a smaller file of the same name)

Addressing all of the above files will bring the repository size down to **100-150 MiB** which seems acceptable to me.

However, permanently removing files from a git history changes a lot of commit hashes. That's why I think we should wait for all files listed above to be discussed. Then we can make one single change that removes large files once and for all. After that, we should have a much stricter policy for large files and we should be fine in the future.

**Comment by sameberenz** [comment]
Hi Thomas, thanks for the check on the files. Should we change the files and tests using them directly on develop branch?

**Comment by tovogt** [comment]
Hi Samuel, since we are preparing for a release, the develop branch should be handled with care. It will be frozen and merged into the main branch very soon. Double-check that your changes don't break any tests, preferably create a branch and a PR in a first step.

**Comment by emanuel-schmid** [comment]
> 
> 
> This is a follow-up about the large files:
> 
> Here is a list of large files that are obsolete (i.e., can be safely removed because they have already been replaced), removing those **reduces repository size by 110 MiB** already:
> Click to expand the list of obsolete files in the git history
> 
> Here is a list of the files larger than 3 MiB (except those in `feature/supplychain`) and the people who added them to the repository. Can those people please replace the files by smaller ones or give reasoning why the files have to be that large?
> 
>     * `climada/hazard/test/data/Victoria_firms.csv` (bush fire hazard, originally Marine Perus, no GitHub-account)
> 
>     * `data/demo/h08_gfdl-esm2m_ewembi_historical_histsoc_co2_dis_global_daily_DEMO_FR_2001_2005.nc` (@sameberenz)
> 
>     * `data/demo/flddph_WaterGAP2_miroc5_historical_flopros_gev_picontrol_2000_0.1.nc` (@ingajsa)
> 
>     * `data/demo/fldfrc_WaterGAP2_miroc5_historical_flopros_gev_picontrol_2000_0.1.nc` (@ingajsa)
> 
>     * `climada/hazard/test/data/test_global_landslide_nowcast_20190508.tif` (@Evelyn-M)
> 
>     * `climada/hazard/test/data/test_global_landslide_nowcast_20190501.tif` (@Evelyn-M)
> 
>     * `climada/hazard/test/data/test_global_landslide_nowcast_20190509.tif` (@Evelyn-M)
> 
>     * `data/system/ls_pr_NGI_UNEP/ls_pr.tif` (@Evelyn-M)
> 
>     * `climada/hazard/test/data/nasa_global_landslide_catalog_point.dbf` (@Evelyn-M)
> 
>     * `data/demo/earth_engine/landcover.tif` (@raychpistache)
> 
>     * `data/demo/earth_engine/rgb_zurich.tif` (@raychpistache)
> 
> 
> Here is a list of files where we can save some space without removing:
> 
>     * `script/tutorial/5_blackmarble.ipynb` (the file might be okay, but there are several obsolete revisions in the git history)
> 
>     * `script/applications/eca_san_salvador/San_Salvador_Risk.ipynb` (the file might be okay, but there are several obsolete revisions in the git history)
> 
>     * `data/demo/tc_fl_1975_2011.h5` (used in several tests, could probably be reduced in size easily)
> 
>     * `data/demo/atl_prob.mat` (used in many tests, could probably be reduced in size easily)
> 
>     * `data/demo/WS_ERA40.mat` (never used in the code, any ideas if this is needed?)
> 
>     * `data/system/GLB_NatID_grid_0360as_adv_2.mat` (has already been replaced by a smaller file of the same name)
> 
> 
> Addressing all of the above files will bring the repository size down to **less than 130 MiB** which seems acceptable to me.
> 
> However, permanently removing files from a git history changes a lot of commit hashes. That's why I think we should wait for all files listed above to be discussed and replaced in all currently active branches (most important: main and develop). Then we can make one single change that removes large files once and for all (e.g. using the tool https://rtyley.github.io/bfg-repo-cleaner/). After that, we can implement a much stricter policy for large files and we should be fine in the future.

Thanks a lot for the compilation and the suggestions. Sounds like a sound plan to me.

**Comment by tovogt** [comment]
Please continue the discussion about the large files in the new issue #56. The current issue is more about changing some of the paths, maybe moving some parts of the repository to a new repository or to some other external location.

**Comment by emanuel-schmid** [comment]
**Resolution**
At some point the tests should be moved out of the package directory in order to keep the installation as light weighted as possible.
Apart from that the repository structure will stay as is for the time being.
