### ISSUE TITLE
entity plot: log colorbar ent.plot_hexbin(bins='log')

### ISSUE THREAD

**Issue by sameberenz** [CLIMADA-project/climada_python#5]
using the log-functionality in plot_hexbin, the colorbar is not labelled correctly.
In the screenshot, the values per pixel actually range from 0 to 16926138554 USD

![screenshot 2019-02-14 at 10 44 47](https://user-images.githubusercontent.com/27805268/52778572-98264680-3046-11e9-89f9-f6e919786e4e.png)

**Comment by sameberenz** [comment]
# code:
from climada.entity.exposures.litpop import LitPop
country_name = ['MEX']
resolution = 120 # change to 30 for final version (slow!)
financial_mode = 'pc' # produced capital: "pc"
year = 2014
ent = LitPop()
ent.plot_hexbin(bins='log')

**Comment by gabrielaznar** [comment]
Hi Sam,

plot_hexbin() is using the function hexbin of matplotlib (https://matplotlib.org/api/_as_gen/matplotlib.axes.Axes.hexbin.html) and the kwargs you can provide to it are the same as in matplotlib's hexbin. The 'bins' option shows you the colorbar in log scale as well. If you use LogNorm instead, the colorbar will be in logscale but with the unlogged numbers:

from matplotlib import colors
norm=colors.LogNorm()
ent.plot_hexbin(norm=norm)

You can find some examples of this use in the tutorial of the Black Marble: 
http://localhost:8888/notebooks/Documents/Python/climada_python/script/tutorial/climada_entity_BlackMarble.ipynb

I hope this solves your question.

**Comment by sameberenz** [comment]
Thank you Gabriela,

Following your instructions, managed to get a nice plot with these settings:

norm=colors.LogNorm(vmin=1.0e3, vmax=1.2e10) # setting min. und max. for the log-normal scale
ent.plot_hexbin(linewidth=2, norm=norm)

![screenshot 2019-02-14 at 11 08 31](https://user-images.githubusercontent.com/27805268/52787722-feb75e80-305e-11e9-946e-28511656d321.png)
