### ISSUE TITLE
Modules with additional requirements

### ISSUE THREAD

**Issue by tovogt** [CLIMADA-project/climada_python#51]
Please join the discussion about CLIMADA modules that need packages/libraries that are not listed in the conda requirements files. Under which circumstances can we accept this? How do we deal with such a situation?

Examples:
* The module `climada.util.earth_engine` imports `ee` (provided by `earthengine-api`), which is not in the requirements files. Only very few users would be interested in using `climada.util.earth_engine` and it's only useful if you have a Google account. Additionally, installing `earthengine-api` brings in a lot more requirements (especially a lot of `google-*` packages). So it seems restrictive to force all users of CLIMADA to install this requirement. On the other hand, when importing `climada.util.earth_engine`, an `ImportError` is raised without instructions on how to deal with it. A more user-friendly output is desirable.
* The module `climada.util.alpha_shape` imports from `descartes` which is not in the requirements files (it's in `setup.py`, but not in the conda requirements files). I don't know anything about `climada.util.alpha_shape`. It's used nowhere else in the CLIMADA code. Anyone?
* The module `climada.hazard.tc_surge_geoclaw` uses the Fortran library `geoclaw` and will compile Fortran code at runtime:  https://github.com/CLIMADA-project/climada_python/blob/e2351353d819454c6826f96f77bef98244818b4d/climada/hazard/tc_surge_geoclaw.py#L322
Fortran compilers are only available as OS-dependent packages in Conda, so we can't easily add one to the requirements files. I will make sure that users who import `climada.hazard.tc_surge_geoclaw` will be informed about the additional requirement.
* The module `climada.hazard.tc_surge` imports the `elevation` package that doesn't work with Windows: https://github.com/CLIMADA-project/climada_python/issues/9

Questions:
* Do you know more examples? Are you working on a new feature that introduces similar additional requirements?
* Do we want to generally avoid such situations under all circumstances? We could strictly remove such modules from the CLIMADA repository and force them to be placed in an external "add-on" repository. This is how the old MATLAB version of CLIMADA was organized and, from my understanding, this is not desirable for the new Python-based CLIMADA which should instead provide all features in one central place.
* If we tolerate such additional requirements, do we want to formulate a policy under which circumstances this is acceptable?
* If we tolerate such additional requirements, what are conventions when and how to instruct users to install the additional requirements?

**Comment by mmyrte** [comment]
I am working with [`pybufrkit`](https://github.com/ywangd/pybufrkit/), which is a rather exotic library. It would be a perfect example for an additional module that is simply dependent on climada while being able to set its own dependencies. I understand why we don't want core functionality tacked on in outside packages, but as long as everyone that's writing extensions also has push access here, I think we're good.

**Comment by tovogt** [comment]
But `pybufrkit` is in the requirements file: https://github.com/CLIMADA-project/climada_python/blob/a6261671a65517f3033dc3dd2731cf38369ba90f/requirements/env_climada.yml#L58
This issue is about packages/libraries that are needed to run certain CLIMADA modules, but that are not included in the requirements files.

**Comment by mmyrte** [comment]
Yes, I put it there so that I can test it in CI. I'm just stating that my project would potentially fall in this category. 🙂

**Comment by tovogt** [comment]
In the last dev meeting, it was getting clear that a policy along the following lines is desirable:
* CLIMADA is aimed at an audience that is not particularly tech-savvy and shouldn't be bothered with any complicated installation steps beyond installing a Conda environment with the provided requirements files.
* However, it is still acceptable to have some CLIMADA modules that require additional and more complicated steps to be taken (e.g. additional external libraries or datasets) as long as those modules are sufficiently isolated from the core code.
* Those "complicated" modules may still be part of the main repository, but users should be informed or warned in a timely manner about which modules are affected.
