### ISSUE TITLE
Import error 

### ISSUE THREAD

**Issue by chahank** [CLIMADA-project/climada_python#510]
A change in the import of `DistanceMetrics was introduced recently

from `from sklearn.neighbors import DistanceMetric` to `from sklearn.metrics import DistanceMetric` 

in `tc_tracks.py`.

This requires adjusting the requirements:

`scikit-learn>=1.0.2`

However, this might be incompatible with other requirements 

`plotly<3.11,>=3.10` 
and
`xarray<0.17,>=0.16`

This is quite a blocker as `tc_tracks` gets imported every time `hazard` is imported.

**Comment by emanuel-schmid** [comment]
Thanks for pointing this out!

The requirements files env_climada.yml is now adapted accordingly (develop branch).

Where does the incompatibility with plotly (matplotlib?) and xarray come from? All I found is geopandas depends on mapclassify, depends on scikit-learn.

Would you get an error if you did `conda env update -n climada_env -f requirements/env_climada.yml?

**Comment by emanuel-schmid** [comment]
Also see https://github.com/CLIMADA-project/climada_python/issues/286
