### ISSUE TITLE
Frequency Unit

### ISSUE THREAD

**Issue by emanuel-schmid** [CLIMADA-project/climada_python#516]
The frequency unit is globally set to 'annual' (y<sup>-1</sup>).
We need to make this a variable.
Task: introduce a `frequency_unit` being part of the meta data of the affected CLIMADA objects.

**Comment by chahank** [comment]
Can it be a property instead of a meta data?

**Comment by emanuel-schmid** [comment]
Sure, the term "meta data" is used in a general sense, without implementation bias.
