### ISSUE TITLE
Renaming AAI and EAI

### ISSUE THREAD

**Issue by ChrisFairless** [CLIMADA-project/climada_python#521]
Following the Developer's Meeting last week, we want to come up with new acronyms for EAI (expected annual impact) and AAI (average annual impact) when CLIMADA uses them. (Side note: why do we even use both acronyms, are they not the same thing?)

The reason is to remove the word 'annual': CLIMADA doesn't assume that frequency information is annual. That is, an expected impact calculation makes perfect sense for e.g. an ensemble forecast, but the expected impact isn't annual.

We want the new acronyms to keep EAI and AAI as their abbreviations so that no methods need to be renamed. This Issue will be solved with an update to documentation only.

This is my suggestion:

`eai_exp`
- Old: expected annual impact
- New: exposure average impact

`aai_agg`
- Old: average annual impact
- New: aggregated average impact

It's not exciting, and it creates redundant acronyms, but the naming is consistent and now when `eai` and `aai` are used in different places they mean different things.

I'll leave this open for a few days for comments and then submit a pull request.

**Comment by ChrisFairless** [comment]
To both of those points, isn't 'expected annual impact' equivalent to 'average annual impact'? i.e. EAI == AAI?

I was thinking it was odd to use both of those phrases rather than sticking to one. The new suggested acronyms have EAI != AAI

**Comment by chahank** [comment]
I understand. It is correct that both refer to the fact that the values are multiplied with the event's frequency, thus expectation value or average. These mean exactly the same thing in this context. The difference comes from the `_exp` and the `_agg`. `eai_exp` and `eai_agg` would have made more sense, although the problem of `a=annual` remains. I like your suggestion, event though it is a bit repetitive :D.

**Comment by peanutfun** [comment]
I would like to make the point that abbreviations tend to make code less readable. I therefore suggest to also add full-name aliases to these methods, suggesting that we might move away from (ambiguous) abbreviations in the future:
```python
def eai_agg(*args):
    """Compute exposure average impact (EAI) aggregated (AGG)

    Alias for ``average_impact``.
    """
    return average_impact(args)

def average_impact(*args):
    """Compute average impact

    More information.
    """
    pass
```

**Comment by chahank** [comment]
Do you mean as an exposed variable name? Sure, otherwise I am not convinced that having two names for the same variable  in the code base makes it more readable.

Also, your example would actually make things much worse, as the verbatim version is not an accurate description of the variable. This is the advantage of acronyms. You can have short variables for few selected variables that need long descriptions to be clear.

**Comment by peanutfun** [comment]
Sorry, I mixed something up. These are attributes, not methods. But my example can be adapted easily:
```python
def __init__(self):
    self.eai_exp = np.array([])

@property
def average_impact(self):
    return self.eai_exp
```

> Also, your example would actually make things much worse, as the verbatim version is not an accurate description of the variable.

I disagree. Following this argument, no variable name would be accurate. If I was unfamiliar with the meaning of `eai_exp`, I would need to look it up in the documentation. The same is true if I expected from its name that `average_impact` was an "overall" mean, not an array mapping to the exposure points. I simply argue that it's easier to recall what `average_impact` meant than `eai_exp`.

**Comment by chahank** [comment]
Average impact is a concept, but it is different from the eai_exp variable. This is like using the word “sun” whenever you speak of the “moon”. Instead, eai_exp has no other meaning, thus it cannot be confused. If reading the documentation is anyway needed, we should use unambiguous variable names. “Average_impact” is not only unambiguous, but misleading.

**Comment by chahank** [comment]
def __init__(self):
    self.eai_exp = np.array([])

@property
def average_impact(self):
    return self.eai_exp

We can define a property as alias, but the code should use only one of both imho.

**Comment by peanutfun** [comment]
@davidnbresch @chahank @ChrisFairless Is this still relevant? I recall we planned the renaming in a retreat but the changes were never implemented.

**Comment by chahank** [comment]
Thanks for checking in @peanutfun : I would say this is not strongly relevant at the moment. I think that your alias proposal might still be explored (we can put this in the backlog of our scrum), but it seems not critical. Since this discussion, no serious issue about the namings came to my ears, which might indicate that this is ok as is.

**Comment by peanutfun** [comment]
Moved this into the backlog of our Scrum. Closing the issue for now.
