### ISSUE TITLE
`UnboundLocalError` in `geo_im_from_array`

### ISSUE THREAD

**Issue by peanutfun** [CLIMADA-project/climada_python#525]
There is a logic error in the `geo_im_from_array` function in the plot utility module. I ran into this issue when setting a custom CRS. The error occurs at [`climada/util/plot.py#L316`](https://github.com/CLIMADA-project/climada_python/blob/1b1fb2d343a4721cf916080a017965d85522b273/climada/util/plot.py#L316): If `axes` is `None`, but `proj` is not an instance of `ccrs.PlateCarree`, the variable `plot_proj` is not set when calling `make_map`:

```python
# def geo_im_from_array() ...
    if not proj:
        mid_lon = 0.5 * sum(extent[:2])
        proj = ccrs.PlateCarree(central_longitude=mid_lon)
    if 'vmin' not in kwargs:
        kwargs['vmin'] = np.nanmin(array_sub)
    if 'vmax' not in kwargs:
        kwargs['vmax'] = np.nanmax(array_sub)
    if axes is None:
        if isinstance(proj, ccrs.PlateCarree):
            # use different projections for plot and data to shift the central lon in the plot
            xmin, xmax = u_coord.lon_bounds(np.concatenate([c[:, 1] for c in list_coord]))
            proj_plot = ccrs.PlateCarree(central_longitude=0.5 * (xmin + xmax))
        _, axes, fontsize = make_map(num_im, proj=proj_plot, figsize=figsize,
                                     adapt_fontsize=adapt_fontsize)
```
I would guess instead of setting a new variable, `proj_plot` could be replaced with `proj`?

**Comment by emanuel-schmid** [comment]
fixed with #576
