### ISSUE TITLE
Shifted holland wind max intensity relative to track

### ISSUE THREAD

**Issue by bguillod** [CLIMADA-project/climada_python#536]
I find cases where the holland wind maps appear to be shifted relative to the track.

Take for example:
```
from climada.hazard.tc_tracks import TCTracks
from climada.hazard.centroids import Centroids

# load one track
tr_ib = TCTracks.from_ibtracs_netcdf(provider='usa', storm_id='2022024S16044', estimate_missing=True)
tr_ib.equal_timestep(1/12)

# create centroids on a 5 km grid
centr2 = Centroids.from_pix_bounds(-14, 32, -0.05, 0.05, 6*20, 13*20)

# calculate wind map
haz_def = TropCyclone.from_tracks(tr_ib, centr2, ignore_distance_to_coast=True)

# plot wind map and track for that event
tr_ib.plot()
haz_def.plot_intensity(event="2022024S16044")
```

![image](https://user-images.githubusercontent.com/13904718/189093008-f41bba11-9e13-459f-a773-715f6e0addf4.png)
![image](https://user-images.githubusercontent.com/13904718/189093042-2edb7a3d-0e69-4e76-944b-f5968eea280f.png)

The track passes above the semi-island called "Natiquinde", but the maximum wind speed is below that.

Is this expected? I looks weird to me. In some cases the shift looks quite large:
<img width="737" alt="image" src="https://user-images.githubusercontent.com/13904718/189094092-83039519-d228-4381-b596-1d1f99975aa3.png">

Any idea whether this is expected and why, or if there might be a bit, will be welcome.

**Comment by bguillod** [comment]
I should say I *think* this is expected but wanted to be sure... Probably in those storms wind speed is low so this is just more clearly visible than for strong storms...

**Comment by tovogt** [comment]
At first glance, I guess that this is due to the influence of storm movement. The examples you plotted are on the southern hemisphere, where storms rotate clockwise. Thus, when the storm moves westwards, the storm movement enhances wind speeds south of the eye, and attenuates wind speeds north of the eye. Since storm movement is generally slow (at most 5 m/s) this effect is more pronounced for storms with low maximum wind speeds.

**Comment by bguillod** [comment]
Thanks a lot @tovogt for confirming my assumption! This clarifies it.
