### ISSUE TITLE
AttributeError in climada.util.coordinates.get_country_code if all lats, lons are over ocean

### ISSUE THREAD

**Issue by ThomasRoosli** [CLIMADA-project/climada_python#540]
There is a bug in climada.util.coordinates.get_country_code 
`from climada.util.coordinates import get_country_code as u_get_country_code`
If I run
`u_get_country_code([45.1 , 45.32634711, 45.55751498, 45.79698392], [7.3 , 7.23261237, 7.14440587, 7.04121094])`
the output is
`array([380, 380, 380, 380])`
as expected. 
But if all points (lats, lons) are in the ocean, (more specifically if the extend/bounding box is only in the ocean) the line 1450 produces an Attribute error: https://github.com/CLIMADA-project/climada_python/blob/481ec6e0c6785377f28314ab4bd86c04e7bb11dd/climada/util/coordinates.py#L1450 
e.g. with this line of code, this can be reproduced:
`u_get_country_code([-24.1 , -24.32634711, -24.55751498, -24.79698392], [87.3 , 87.23261237, 87.14440587, 87.04121094])`

This case could be handled more gracefully by checking if `total_land` is None before running the line producing the error.

**Comment by emanuel-schmid** [comment]
:pray: Thanks for the report!

**Comment by emanuel-schmid** [comment]
Fixed by 3615ac7
