### ISSUE TITLE
Could not import ImpactCalc from climada.engine

### ISSUE THREAD

**Issue by SHFeMIX** [CLIMADA-project/climada_python#547]
![图片](https://user-images.githubusercontent.com/57001434/196485654-2bdc453f-809d-45a6-961c-468ea6fea4fc.png)
When I try to run the demo in project document and import ImpactCalc from climada.engine, I got this error.

**Comment by chahank** [comment]
Which version of CLIMADA are you using? The `ImpactCalc` class is not part of the current latest release 3.2.0, and is only available on the develop branch. It will be part of the next release.

**Comment by SHFeMIX** [comment]
I installed climada just by pip install.

**Comment by SHFeMIX** [comment]
> Which version of CLIMADA are you using? The `ImpactCalc` class is not part of the current latest release 3.2.0, and is only available on the develop branch. It will be part of the next release.

I installed climada just by pip install.

**Comment by chahank** [comment]
In this case, you are using CLIMADA version 3.2.0. Please follow the documentation for this version, see https://climada-python.readthedocs.io/en/stable/tutorial/1_main_climada.html#Engine and https://climada-python.readthedocs.io/en/stable/tutorial/climada_engine_Impact.html .

The `ImpactCalc` class will be available in the next release.
