### ISSUE TITLE
Resources: Remove/replace large binary files

### ISSUE THREAD

**Issue by tovogt** [CLIMADA-project/climada_python#56]
This is extracted from the discussion in #48 (sorry for retagging everyone). The lengthy part about large files became off topic, so I decided to move it here.

The repository size is currently around **~580 MiB** (using `git count-objects -vH`). Cloning this repository therefore takes considerable amounts of time. However, an analysis of large binary blobs in the git history suggests that we can easily save more than 80% of the space by rewriting git history (using https://github.com/newren/git-filter-repo).

### List of largest files in repository's history
For reference, the list of the 100 largest files in the repository's history (command line from https://stackoverflow.com/questions/10622179/how-to-find-identify-large-commits-in-git-history):
<details><summary>Click to expand the list of 100 largest files in the repository's history</summary>
<p>

```$ git rev-list --objects --all | git cat-file --batch-check='%(objecttype) %(objectname) %(objectsize) %(rest)' | sed -n 's/^blob //p' | sort --numeric-sort --key=2 | cut -c 1-12,41- | $(command -v gnumfmt || echo numfmt) --field=2 --to=iec-i --suffix=B --padding=7 --round=nearest | tail -100
Object hash   Size   Path
------------------------------------------------------------------------------------
afdf9d250244  1,5MiB data/supplychain/USA_services_XXX
7b0bde40f2d8  1,5MiB doc/tutorial/climada_entity_Exposures.ipynb
7b5cadab5cfa  1,6MiB doc/tutorial/climada_entity_Exposures.ipynb
c49fc7111e0d  1,6MiB doc/tutorial/climada_entity_Exposures.ipynb
71a04b0332ed  1,6MiB doc/tutorial/climada_entity_Exposures.ipynb
7771f3263d57  1,6MiB doc/tutorial/climada_entity_Exposures.ipynb
2f7e0ca73836  1,6MiB script/tutorial/1_main_climada.ipynb
607362854358  1,6MiB doc/tutorial/climada_entity_LitPop.ipynb
c90a0f3284d9  1,6MiB data/supplychain/FRA_agriculture_XXX
7a2a1295d6b6  1,6MiB doc/tutorial/climada_entity_LitPop.ipynb
358001e6d875  1,6MiB doc/tutorial/climada_entity_LitPop.ipynb
805f29c38ebc  1,6MiB doc/tutorial/climada_entity_LitPop.ipynb
7a9e5af40035  1,6MiB doc/tutorial/climada_entity_LitPop.ipynb
ba2fb96b6ee3  1,6MiB doc/tutorial/climada_entity_LitPop.ipynb
9b738e384042  1,6MiB doc/tutorial/climada_entity_LitPop.ipynb
04647bd8b895  1,6MiB doc/tutorial/climada_entity_LitPop.ipynb
bdef60960e28  1,6MiB doc/tutorial/climada_entity_LitPop.ipynb
9a3fa22242eb  1,7MiB doc/tutorial/climada_entity_LitPop.ipynb
dc26c1560790  1,7MiB data/supplychain/ROW_agriculture_XXX
b78a959c7569  1,7MiB doc/tutorial/climada_entity_LitPop.ipynb
56008533bd4a  1,7MiB data/demo/California_firms_2016_viirs.csv
74c6286c0d8f  1,7MiB data/supplychain/AUS_agriculture_XXX
9b16d9f4c6f8  1,7MiB script/workshop_I/Hands-on_I.ipynb
1ccabe803c86  1,8MiB data/supplychain/TUR_agriculture_XXX
bc03576dc17f  1,8MiB script/tutorial/climada_entity_Exposures.ipynb
c95ded79ebab  1,8MiB doc/tutorial/climada_entity_Exposures.ipynb
944049d01093  1,8MiB data/supplychain/CAN_agriculture_XXX
2807d06acd33  1,9MiB data/system/NatID_grid_0150as.nc
05b8b073fa47  2,0MiB doc/tutorial/climada_entity_BlackMarble.ipynb
3e361005ea56  2,0MiB doc/tutorial/climada_entity_BlackMarble.ipynb
4048178c77d3  2,0MiB doc/tutorial/climada_entity_BlackMarble.ipynb
d3ab436b04f1  2,0MiB data/supplychain/MEX_agriculture_XXX
7a6c555d6760  2,1MiB script/tutorial/climada_entity_LitPop.ipynb
2f9cdd203bd9  2,1MiB script/tutorial/climada_entity_LitPop.ipynb
ae226ed99cff  2,1MiB climada/test/data/buildings_47_8.dbf
52a3b730ef46  2,1MiB script/tutorial/climada_entity_LitPop.ipynb
c9dd435c0d1e  2,1MiB doc/tutorial/climada_entity_LitPop.ipynb
ab7e168310ef  2,1MiB script/tutorial/climada_entity_LitPop.ipynb
82ba67d2d905  2,1MiB script/tutorial/climada_entity_LitPop.ipynb
c1d248a585bd  2,2MiB data/demo/h08_gfdl-esm2m_ewembi_historical_histsoc_co2_dis_global_daily_DEMO_FR_2001_2003.nc
1953d6fe0d8c  2,3MiB data/supplychain/CAN_services_XXX
b40a3cf5ccd9  2,4MiB data/supplychain/IDN_agriculture_XXX
b7ea0f4a34c5  2,6MiB data/system/GDP2Asset_converter_2.5arcmin.nc
febc69be140c  2,7MiB script/tutorial/5_blackmarble.ipynb
f881dc1edee9  2,7MiB script/tutorial/climada_entity_LitPop.ipynb
1170d76eb438  2,7MiB script/tutorial/climada_entity_LitPop.ipynb
acd637415a02  2,7MiB script/tutorial/climada_entity_LitPop.ipynb
dd1190329814  2,7MiB script/tutorial/climada_entity_LitPop.ipynb
b920c0a578ef  2,7MiB script/tutorial/climada_entity_LitPop.ipynb
d29e8ea548a2  2,8MiB doc/tutorial/climada_entity_BlackMarble.ipynb
aaefe1ae6818  2,8MiB script/tutorial/climada_entity_BlackMarble.ipynb
23756ddc625a  2,8MiB script/tutorial/climada_entity_BlackMarble.ipynb
32b12fe30ba5  2,8MiB script/tutorial/climada_entity_BlackMarble.ipynb
cc64db7d153d  3,1MiB climada/engine/test/data/supplychain/test_hazard
b6ac52e0df52  3,1MiB script/tutorial/5_blackmarble.ipynb
2ca5f50c405e  3,4MiB data/demo/earth_engine/landcover.tif
cfc1110ac778  3,4MiB data/supplychain/IND_agriculture_XXX
3389da6ed038  3,7MiB data/demo/h08_gfdl-esm2m_ewembi_historical_histsoc_co2_dis_global_daily_DEMO_FR_2001_2005.nc
68c0e2ec19be  3,8MiB script/applications/eca_san_salvador/San_Salvador_Risk.ipynb
8416b7843ecf  3,9MiB data/demo/tc_fl_1975_2011.h5
9c72e4b14e59  4,0MiB data/supplychain/RUS_services_XXX
4a4f2ae421b8  4,3MiB data/supplychain/RUS_agriculture_XXX
3758d01539d9  4,5MiB data/demo/WS_ERA40.mat
03ecae28d707  4,8MiB data/supplychain/BRA_agriculture_XXX
e528b62cb0bc  4,8MiB script/applications/eca_san_salvador/San_Salvador_Risk.ipynb
ab730b2e6070  5,3MiB script/applications/eca_san_salvador/San_Salvador_Risk.ipynb
2304b65ad0ba  5,3MiB script/applications/eca_san_salvador/San_Salvador_Risk.ipynb
1a693d23e8df  5,4MiB data/supplychain/CHN_agriculture_XXX
799b5f35455a  5,5MiB script/applications/eca_san_salvador/San_Salvador_Risk.ipynb
835ed0d1e415  5,5MiB script/applications/eca_san_salvador/San_Salvador_Risk.ipynb
0efdda0ef036  5,7MiB data/supplychain/USA_agriculture_XXX
4fe57575bcd9  5,8MiB script/applications/eca_san_salvador/San_Salvador_Risk.ipynb
9ce0afd9b4f4  5,9MiB data/demo/flddph_WaterGAP2_miroc5_historical_flopros_gev_picontrol_2000_0.1.nc
1e54fca74b5f  6,2MiB data/demo/fldfrc_WaterGAP2_miroc5_historical_flopros_gev_picontrol_2000_0.1.nc
f3aed133427c  6,9MiB script/applications/eca_san_salvador/San_Salvador_Risk-Copy1.ipynb
6719ca15aee3  7,1MiB data/demo/atl_prob.mat
7f603961260f  7,6MiB climada/hazard/test/data/test_global_landslide_nowcast_20190508.tif
589b0ef33943  7,7MiB climada/hazard/test/data/test_global_landslide_nowcast_20190501.tif
2675811213d0  7,8MiB climada/hazard/test/data/test_global_landslide_nowcast_20190509.tif
b0c1cd004b06  8,1MiB climada/hazard/test/data/cropping_test_LS.tif
cee69928a590  9,0MiB dist/climada-0.0.1.tar.gz
ca4c7071c104   10MiB climada/hazard/test/data/Victoria_firms.csv
a64e0f3e5c24   13MiB data/F101992.v4b_web.stable_lights.avg_vis.tif.gz
b9e8e61a2eec   14MiB climada/test/data/system/admin0.mat
7390384f5085   15MiB data/system/ls_pr_NGI_UNEP/ls_pr.tif
1678be6b232f   15MiB climada/test/data/GLB_NatID_grid_0360as_adv_1.mat
0fa15d7d60ef   15MiB climada/test/data/GLB_NatID_grid_0360as_adv_2.mat
2a1a77be0dc8   15MiB data/system/GLB_NatID_grid_0360as_adv_2.mat
7bc480bd96d2   16MiB data/F152007.v4b_web.stable_lights.avg_vis.tif.gz
93c8b4eb9131   16MiB data/supplychain/ROW_services_XXX
3109d2e4bf3b   17MiB data/F162007.v4b_web.stable_lights.avg_vis.tif.gz
2a5a60d34a27   17MiB data/demo/earth_engine/rgb_zurich.tif
8b8bc642dfa6   18MiB data/F182012.v4c_web.stable_lights.avg_vis.tif.gz
439e36b6bb9a   24MiB data/system/IBTrACS.ALL.v04r00.nc
0bd3d429871b   25MiB data/system/ECLIPSE_base_CLE_V5a_NOx.nc
5e8e2e083e95   31MiB climada/hazard/test/data/nasa_global_landslide_catalog_point.dbf
864876f19e62   41MiB data/demo/gdp2asset_demo_exposure.nc
3026099e8d97   51MiB data/supplychain/GLB_agriculture_XXX
090d7bb7444a   82MiB data/supplychain/WIOT2014_Nov16_ROW.xlsx
7f0d4a40ca5d   91MiB data/supplychain/sup_ib_hazard_default
```
</p>
</details>

### Obsolete files and folders

There are whole folders that can be safely removed recursively using `git filter-repo --invert-paths --path <path>`:

<details><summary>Click to expand the list of folders that can be safely removed recursively from the git history</summary>
<p>

```
script/tutorial/
data/supplychain/
script/workshop_I/
```
</p></details>

Furthermore, there is a list of single blobs that are obsolete. They and all files with the same base names can be removed from the git history using `git filter-repo --invert-paths --path-glob */<basename>`.

<details><summary>Click to expand the list of obsolete files in the git history</summary>
<p>

```
data/system/ECLIPSE_base_CLE_V5a_NOx.nc
doc/tutorial/climada_hazard_RelativeCropyield_entity_CropProduction.ipynb
script/applications/eca_san_salvador/San_Salvador_Risk-Copy1.ipynb
climada/hazard/test/data/cropping_test_LS.tif
dist/climada-0.0.1.tar.gz
data/F101992.v4b_web.stable_lights.avg_vis.tif.gz
climada/test/data/system/admin0.mat
climada/test/data/GLB_NatID_grid_0360as_adv_1.mat
data/F152007.v4b_web.stable_lights.avg_vis.tif.gz
data/F162007.v4b_web.stable_lights.avg_vis.tif.gz
data/F182012.v4c_web.stable_lights.avg_vis.tif.gz
data/demo/gdp2asset_demo_exposure.nc
data/demo/tc_fl_1975_2011.h5
data/demo/atl_prob.mat
data/demo/WS_ERA40.mat
data/demo/h08_gfdl-esm2m_ewembi_historical_histsoc_co2_dis_global_daily_DEMO_FR_2001_2005.nc
climada/hazard/test/data/test_global_landslide_nowcast_20190508.tif
climada/hazard/test/data/test_global_landslide_nowcast_20190501.tif
climada/hazard/test/data/test_global_landslide_nowcast_20190509.tif
data/system/ls_pr_NGI_UNEP/ls_pr.tif
data/system/IBTrACS.ALL.v04r00.nc
data/system/WIOT2014_Nov16_ROW.xlsx
climada/hazard/test/data/nasa_global_landslide_catalog_point.dbf
climada/hazard/test/data/01_ClimatologyMonthly_032818_9600x5400_test.tif
climada/hazard/test/data/02_ClimatologyMonthly_032818_9600x5400_test.tif
climada/hazard/test/data/03_ClimatologyMonthly_032818_9600x5400_test.tif
data/demo/earth_engine/landcover.tif
data/demo/earth_engine/rgb_zurich.tif
climada/hazard/test/data/Victoria_firms.csv
data/demo/flddph_WaterGAP2_miroc5_historical_flopros_gev_picontrol_2000_0.1.nc
data/demo/fldfrc_WaterGAP2_miroc5_historical_flopros_gev_picontrol_2000_0.1.nc
```
</p></details>

Finally, there are files where we will only keep the latest revision because previous versions were too large. The [BGF Repo-Cleaner](https://rtyley.github.io/bfg-repo-cleaner/) can do exactly this using the `--delete-files` option. It won't remove the files in the current HEAD.

<details><summary>Click to expand the list of files with obsolete revisions in the git history</summary>
<p>

```
data/system/GLB_NatID_grid_0360as_adv_2.mat
script/applications/eca_san_salvador/San_Salvador_Risk.ipynb
doc/tutorial/climada_hazard_entity_Crop.ipynb
doc/tutorial/climada_entity_BlackMarble.ipynb
doc/tutorial/climada_entity_LitPop.ipynb
doc/tutorial/climada_entity_Exposures.ipynb
doc/tutorial/climada_entity_TropCyclone.ipynb
```
</p></details>

### Large files in active branches
All files larger than 3 MiB have been removed from all currently active branches! 

### Conclusion
Addressing all of the above files with [git-filter-repo](https://github.com/newren/git-filter-repo) will bring the repository size down to **~96 MiB** which seems acceptable to me. However, permanently removing files from a git history changes a lot of commit hashes. That's why I think we should make one single change that removes large files once and for all (using https://github.com/newren/git-filter-repo). After that, we can implement a much stricter policy for large files and we should be fine in the future.

Since this issue requires changes to be made to *all* branches including the main branch, fixing it is expected to take at least until the next release in early 2021.

**Comment by sameberenz** [comment]
Commit 8568a4a1d8f541e7523b769739f61bc650645b2e removes `data/demo/h08_gfdl-esm2m_ewembi_historical_histsoc_co2_dis_global_daily_DEMO_FR_2001_2005.nc` on branch [feature/isimip_lowflow](https://github.com/CLIMADA-project/climada_python/tree/feature/isimip_lowflow) and restructures the tests for low_flow.py in a way that it is not required anymore.

This branch will go into peer-review soon.

**Comment by chahank** [comment]
The supplychain branch is currently in a sleeping state, so we could definitely remove it from the repository and archive it. The work on this branch is not finished, and the main author @KasparTo is not working on it anymore. Ideally, someone else will take over this work in the future, hence we should keep everything, but it needs not be in the repository probably. One less radical solution would be to archive all the files added by the commit 
[All data files required for supplychain workflow](https://github.com/CLIMADA-project/climada_python/commit/688e7ae566dd1f2d0d79f706e34360693877bde2) and keep the rest.

**Comment by tovogt** [comment]
@chahank I agree. Do you have permissions to create a new repository in the CLIMADA-project group? You can create a repository `climada_early_dev` or `climada_experimental` and fork the current state of `feature/supplychain` (include `develop` as default branch, but omit all the other branches, see [here](https://github.com/tovogt/climada_early_dev)). After that, we can remove the branch `feature/supplychain` in `climada_python`. This would immediately reduce the required download size for cloning our `climada_python` repository. However, there seems to be one prospective user of the `feature/supplychain` branch. You will receive an email with details shortly.

**Comment by chahank** [comment]
I copied all the files in the folder data/supplychain to the WCR-group server. Strangely, the size is 522MiB which would be more than the full repository (?). These files can all be generated from the file `WIOT2014_Nov16_ROW.xlsb` downloaded from the link given in the DocString of the class SupplyChain. The  methods `SupplyChain.read_wiod()`  and  `SupplyChain.default_exposures()` are then used to generate the files. Hence, I think it is safe to remove them from the repository.

**Comment by tovogt** [comment]
Thanks!

The 460 MiB mentioned above is the packed (=compressed) size of the git repository. It's not the size of all the actual data files stored in the history of the git repository (after decompressing), but it's the size of the compressed data that has to be downloaded in order to clone the repository. The packed repository size is the bottle-neck for most users since it has to be downloaded over their internet connection. The uncompressed size of all the files in a single branch checkout might be much larger or smaller.

**Comment by Evelyn-M** [comment]
Thanks a lot @tovogt for this overview on the large files! Regarding my contribution to the items under `Large files in active branches`, will take care of that soon. @wjan262 is currently working on the landslide module, so we'll re-write the testing etc. anyways (and replace those files by more adequate solutions) before we merge the feature branch into develop.

**Comment by mmyrte** [comment]
@ThomasRoosli may know more about the `data/demo/WS_ERA40.mat` file. Maybe it's used in a tutorial?

An interesting question is how to rewrite history. Should we do the obvious thing and duplicate this github repo, archive that, then have someone rewrite history locally and force push that back into this repo? @emanuel-schmid I guess that would that be your task?

**Comment by ThomasRoosli** [comment]
First of all, thanks @tovogt for starting this initiative.
About the `data/demo/WS_ERA40.mat` file: My knowledge is that it is a hazard file from the MATLAB CLIMADA version, that was used there to reproduce the results of a study by Schwierz et al. 2010.  In CLIMADA_python, it may have been used in a tutorial at one point, but at the moment, I don't think it is used in CLIMADA_python anymore. For me it's ok to delete it.

**Comment by davidnbresch** [comment]
Dear colleagues,

just to confirm, the file has been used to reproduce Schwierz et al. 2010. Can be deleted from the climada repository. I still plan (one day) to rewrite the Schwierz reproduction in Python and would then add the file (in the paper respository, not the core Climada). But I do have a copy, hence please delete at your leisure.

With best regards,
David


Prof. Dr. David N. Bresch 
Professor for Weather and Climate Risks
Institute for Environmental Decisions
ETH Zurich/MeteoSwiss
dbresch@ethz.ch <mailto:dbresch@ethz.ch>, dbresch@meteoswiss.ch <mailto:dbresch@meteoswiss.ch>
office: +41 44 632 77 87
mobile: +41 79 770 15 92
skype: davidnbresch
zoom: https://ethz.zoom.us/my/ <https://ethz.zoom.us/my/dbresch>dbresch <https://ethz.zoom.us/my/dbresch>
https://www.usys.ethz.ch/en/people/profile.david-bresch.html
http://www.wcr.ethz.ch <http://www.wcr.ethz.ch/>

**Comment by tovogt** [comment]
In #61, I address three of the larger demo files that are not assigned to anyone in my list. It should be a comparably easy review task - please have a look!

**Comment by sameberenz** [comment]
> Commit [8568a4a](https://github.com/CLIMADA-project/climada_python/commit/8568a4a1d8f541e7523b769739f61bc650645b2e) removes `data/demo/h08_gfdl-esm2m_ewembi_historical_histsoc_co2_dis_global_daily_DEMO_FR_2001_2005.nc` on branch [feature/isimip_lowflow](https://github.com/CLIMADA-project/climada_python/tree/feature/isimip_lowflow) and restructures the tests for low_flow.py in a way that it is not required anymore.
> 
> This branch will go into peer-review soon.

file removed with commit https://github.com/CLIMADA-project/climada_python/commit/281812c136576ea1a6c5d9efe6a649fd9eaa01d4

**Comment by chahank** [comment]
Commit 8c8e4e5 removes all the files in data/supplychain. The history of the repository must still be cleaned to reduce the size.

**Comment by tovogt** [comment]
Thanks for the updates!

I updated my first post accordingly in order to gather all the information in one location. Especially the section about obsolete files is important because it allows us to keep track of which files will be removed in the final rewrite of history.

**Comment by Evelyn-M** [comment]
Commit 10afad6 and commit a2ccd92 remove all the files related to the landslide module referenced above. I also removed further large-ish files in favour of requiring manual download by the user upon usage of the module.

**Comment by tovogt** [comment]
Update: The only two remaining large files are now related to the river flood module.

@ingajsa The demo files are used in tests and in the tutorial: two files of 6 MB each representing floods in the year 2000 on a global grid. Maybe it's possible to crop the grid and adapt all tests and examples to one small region, like Central Europe (most of the examples are for Central Europe anyway).

**Comment by ingajsa** [comment]
Thank you for the reminder. I will remove them within the next weeks...I am still waiting for the flood data to be provided by ISIMIP. Once this is done I will change the tutorial and the tests and provide information on the data. I will leave a note once it is done.

**Comment by tovogt** [comment]
Thanks @ingajsa for replacing the large demo files by smaller ones!

All large files have been removed from the active branches and we can proceed to actually removing stuff from the git history. @emanuel-schmid and @chahank: Since the current HEAD of the main branch also needs to be modified, and the current HEAD is supposed to always point to a release, we have to implement these changes at the exact time when a new release is made, right?

**Comment by chahank** [comment]
Awesome, we are getting there. I do not know about erasing git history, so I would let @emanuel-schmid handle this.

**Comment by zedrdave** [comment]
Sorry to piggyback on a very tangentially related issue, but in the now-closed #38, I saw mention of somehow packaging for PyPi and couldn't find any other mentions. Is there an ongoing discussion about moving in that direction somewhere?

I would be very interested and definitely up for contributing to anything that removes the reliance on the Conda toolchains…

**Comment by emanuel-schmid** [comment]
No need to be sorry. The plan to wrap Climada into a package installable through pip is still valid, although there was little activity in this direction lately. However, even when this is accomplished, it doesn't imply that one can do without Conda. Some dependencies are more or less uninstallable without Conda, at least on Windows, and cannot be easily replaced.

**Comment by zedrdave** [comment]
From a very selfish perspective, we'd be happy enough being able to run Climada in a unix/OS X environment (and it's quite understandable that getting a large Python framework to work directly under Windows would be harder verging on impossible)…

If you care to start a thread on what's needed to make a pip (/pipenv) install possible, I'll be happy to join and see if I can contribute…

**Comment by ingajsa** [comment]
Thanks for your message. I am out of office until Jan 8th. I will get back to you
as soon as possible after my return.

Best regards,
Inga Sauer

    -- 
Inga Sauer
PhD Student
RD3 Transformation Pathways
Potsdam Institute for Climate Impact Research (PIK)
Phone: +49 (0)331 288 20825
Email: inga.sauer@pik-potsdam.de

**Comment by tovogt** [comment]
@emanuel-schmid When do you plan to apply the changes discussed in this issue? For the upcoming release in March?

**Comment by tovogt** [comment]
Since today seems to be a big day, let me mention that I just added the following files to my lists above. I somehow didn't include them in the process even though they are clearly obsolete and too big:
```
data/supplychain/WIOT2014_Nov16_ROW.xlsx
data/system/IBTrACS.ALL.v04r00.nc 
```
Furthermore there are big old revisions of this file, so I added it to the list of "protected" files, where only the current revision should be saved: `doc/tutorial/climada_entity_TropCyclone.ipynb`

Here is my script that does the cleanup from 580 MB to only 96 MB: https://gist.github.com/tovogt/cf8c04dfa772fe8d02636a3c52b36183

**Comment by chahank** [comment]
Thanks @tovogt . As quick check, could @aleeciu please comment on the file `data/supplychain/WIOT2014_Nov16_ROW.xlsx` ? Is this needed or not?

**Comment by tovogt** [comment]
@chahank Actually, it doesn't matter whether it's needed. The file `data/system/WIOT2014_Nov16_ROW.xlsx` is 82 MB in size. It must be removed NOW. If you need it later, we will have a backup for sure. But we will never again add it to this repository.

**Comment by chahank** [comment]
Perfect, I just wanted to be sure before history is rewritten!

**Comment by aleeciu** [comment]
In what branch is this file?

> WIOT2014_Nov16_ROW.xlsx

I cannot find it under data/system of `main`, `develop `and `SupplyChain`. Anyway, I wrote `SupplyChain` such that these files are not needed, but are instead downloaded when the user uses the module. However, this is conditioned to the fact we can add the `pyxlsb` to CLIMADA (see #180 description). If not and we do not want big files, then we can just delete `SupplyChain` all together :-)

**Comment by tovogt** [comment]
@aleeciu Don't worry, it's fine. It's of course perfectly fine that your module downloads this data. It's only about the fact that this file was included in a very old commit and that blows up the git history. If you remember: You yourself removed that file in commit https://github.com/CLIMADA-project/climada_python/commit/77b57ef7fdcda13a3deb7acfe4933a9239936147

**Comment by aleeciu** [comment]
> If you remember: You yourself removed that file in commit 77b57ef

Yep, that is why I was confused. So yes please delete the history!

**Comment by chahank** [comment]
Also, latest news, the package `pyxlsb` can be added to the repository as approved by @emanuel-schmid .
