### ISSUE TITLE
"Longitudinal coordinates need to be normalized to a common 360 degree range"-Error when a TC track is travelling across the antimeridian: Solution suggestion included

### ISSUE THREAD

**Issue by cicconef** [CLIMADA-project/climada_python#584]
While using the function `exposures.assign_centroids(hazard, threshold=5)` I noticed that a problem occurs when a TC track is travelling across the antimeridian. A ValueError is thrown, saying: "**Longitudinal coordinates need to be normalized to a common 360 degree range**". The error is thrown from the function `def _nearest_neighbor_antimeridian` (complete Traceback attached below):

![Traceback](https://user-images.githubusercontent.com/100867268/202163909-66815281-6ccc-4631-a3e1-5d4f9f68ff90.png)

By applying the function `u_coord.lon_normalize()` (from `climada.util.coordinates`) one can normalize the longitudinal coordinates of the hazard such that always -180 < lon <= 180.
In my opinion, the error could be solved within the function where the error is thrown from (`def _nearest_neighbor_antimeridian`) by just normalizing "_lon_min_" and "_lon_max_" in line 1203 instead of raising the _ValueError_. Does it make sense, or is there a reason why the longitudes are not simply normalised within this function? (function cutout below)

![function_nearest_neighbor_antimeridian](https://user-images.githubusercontent.com/100867268/202159722-0d3ba472-805b-454d-8d13-c802bc0a24b6.png)

To get around the implementation within the function, I tried to normalize the longitudinal coordinates of the hazard (`Hazard.centroids.coord[:, 1] = u_coord.lon_normalize(Hazard.centroids.coord[:, 1])`). I did the same for the longitudes of the exposure: `exp.gdf.longitude.values = u_coord.lon_normalize(exp.gdf.longitude.values)`. _The terms Hazard and exp here are adapted to the names in my script of course._
Unfortunately, these arrays are not saved in the hazard or exposure, which is why calling the initial function again triggers a ValueError. This leads me to believe that this error can only be solved within the function `def _nearest_neighbor_antimeridian` (implementation suggestion above).

**Comment by cicconef** [comment]
To specify:
The proposed solution looks like:
_line 1203_: `lon_min = u_coord.lon_normalize(lon_min)`
_line 1204_: `lon_max = u_coord.lon_normalize(lon_max)`

In this case the Error raise could be left out...

**Comment by emanuel-schmid** [comment]
Actually the error message is quite appropriate: `"Longitudinal coordinates need to be normalized"`.

I close this for the time being, even though one could argue that auto-normalization in such cases would be nice. On the other hand one could argue for less auto-ization too. 🤷
