### ISSUE TITLE
Tutorial 1_main of climada python 

### ISSUE THREAD

**Issue by NicolasColombi** [CLIMADA-project/climada_python#590]
Error in cell 22 of climada_python/doc/tutorial/1_main_climada.ipynb when trying to define an entity

Cell In [22], line 3
      1 from climada.entity import Entity
----> 3 ent = Entity(
      4     exposures=exp_litpop,
      5     disc_rates=disc,
      6     impact_func_set=imp_fun_set,
      7     measures_set=meas_set
      8 )

TypeError: __init__() got an unexpected keyword argument 'measures_set'

**Comment by emanuel-schmid** [comment]
Yes, that has changed. Try `measures` instead.

**Comment by NicolasColombi** [comment]
@emanuel-schmid Perfect. I corrected the mistake and made a PR.
