### ISSUE TITLE
Switch to more pleasing HTML theme for CLIMADA docs

### ISSUE THREAD

**Issue by peanutfun** [CLIMADA-project/climada_python#592]
The HTML theme describes the appearence (and only the appearance) of the docs built by the Sphinx package. We currently use the almost default `sphinxdoc` theme, which I find a bit unappealing.

The theme used to display the docs can easily be changed by installing the respective theme package via pip,
```
pip install <theme-pkg>
```
and then adding the theme in the `doc/conf.py`
```python
# conf.py
html_theme = "<theme-name>"
```

Examples of commonly used themes can be found on https://sphinx-themes.org/.
* [Furo](https://sphinx-themes.org/sample-sites/furo/),
* [Book](https://sphinx-themes.org/sample-sites/sphinx-book-theme/), and 
* [Read the Docs](https://sphinx-themes.org/sample-sites/sphinx-rtd-theme/)

are amongst the most common today and I find each of them much nicer than [our current theme](https://climada-python.readthedocs.io/en/stable/index.html).

**Comment by emanuel-schmid** [comment]
👍 Good idea!

**Comment by chahank** [comment]
Yes! I think I have a preference for the `Read the Docs`, but all are an improvement on our current theme I think.

**Comment by peanutfun** [comment]
How to proceed? This requires updating the requirements on Jenkins.

**Comment by emanuel-schmid** [comment]
Does it?

In any case it may require adapting the `requirements/env_docs.yml` file, which is a conda export of the climada environment on an Ubuntu machine. (Being vague about any package version in this file leads to readthedocs running out of memory real soon 🙄 )\
We'll find out as soon as we change the `doc\conf.py` file in the develop branch.

**Comment by peanutfun** [comment]
Alright, to be honest, I'm not sure how the documentation is actually built. Do you use a custom environment and run the `doc/Makefile` or do you let readthedocs run everything?

I would like to avoid the case where the documentation fails to build simply because the theme package is not installed. But I see no way of "testing" this in production. So you think we should just go ahead, change the theme, and find out what's happening? 😅

**Comment by emanuel-schmid** [comment]
Right, before creating the doc files locally, `readthedocs_ext` needs to be installed.

This is because we leave the building of the doc files entirely to readthedocs.org and they obviously add it to all of their environments by default. (That's also the reason why I think that it _may_ be enough to just edit the `doc/conf.py` file)

Have you eventually succeeded to build the doc files locally? If they look good and are functional (navigation makes sense, links are working as they should), I'll just give it a try and update `conf.py` and `env_doc.yml` on develop.

**Comment by peanutfun** [comment]
If it's all handled by readthedocs.org, why do we need a separate `env_doc.yml` environment specification?

**Comment by peanutfun** [comment]
Answer: Readthedocs needs to build the package to resolve the links within the module. It installs dependencies via mambaforge. Resolving the dependencies without exactly specifying the package version takes up too much memory and the build fails. Therefore, we maintain the `env_doc.yml` file.

The `sphinx-rtd-theme` is pre-installed with Readthedocs and does not need to be specified in the requirements.

**Comment by chahank** [comment]
Is it possible to make subsections for the list on the left of the Read the Docs theme?

**Comment by emanuel-schmid** [comment]
Probably yes. Why not? If the doc pages are structured in the right way ...

Something else to consider: the Read the Docs theme shows adds at the bottom. Are we happy with this?

**Comment by peanutfun** [comment]
> Is it possible to make subsections for the list on the left of the Read the Docs theme?

Yes. We simply need to add `caption`s to the `toctree` directives. For an example, see https://gitlab.com/utopia-project/utopia/-/blob/master/doc/index.rst?plain=1#L49 and the result: https://docs.utopia-project.org/html/index.html

**Comment by chahank** [comment]
> Something else to consider: the Read the Docs theme shows adds at the bottom. Are we happy with this? 

Good question. To be discussed I suppose.

**Comment by peanutfun** [comment]
Switched to Book theme (as elected in the last CLIMADA call) in #600
