### ISSUE TITLE
Impact Aggregation by Region

### ISSUE THREAD

**Issue by emanuel-schmid** [CLIMADA-project/climada_python#595]
There should be an easy way to get damages per event and region_id.

There are many ways to implement this, but all of them come with a price on calculation and/or memory. From a discussion on Slack a vague plan emerged to 
- introduce an additional method in `Impact` that provides this kind of aggregation 
- introduce an additional argument in the `ImpactCalc.impact` method that indicates how/whether to persist the aggregation result within the `Impact` object.

**Comment by aleeciu** [comment]
- introduce an additional argument in the `ImpactCalc.impact` method (e.g., `at_region_id_event`) and we the current `at_event` becomes `at_region_id_event.sum(0)` or something

**Comment by emanuel-schmid** [comment]
Er, actually, the case depending replacement of `at_event` was declined, I'm afraid 😬

**Comment by aleeciu** [comment]
see proposed addition in #642

**Comment by peanutfun** [comment]
Resolved by #642
