### ISSUE TITLE
entity plots: default clipping

### ISSUE THREAD

**Issue by sameberenz** [CLIMADA-project/climada_python#6]
Hello again,

The plot_hexbin function per default clips the map of an entity tightly to the grid points with data.
For low resolutions, parts of the country are sometimes cut off, as can be seen in the plot below:
Parts of Schaffhausen and eastern Switzerland are cut off.
Of course this can be set manually, but I would suggest a default with a certain buffer (or clipping according to borders instead of grid points for country plots).
What do you think?
(Code below)

![image](https://user-images.githubusercontent.com/27805268/52787851-843b0e80-305f-11e9-85c1-e244d15a7681.png)

from climada.entity.exposures.litpop import LitPop
ent = LitPop()
ent.set_country('CHE', fin_mode='pc', res_arcsec=300, reference_year=2017)
ent.plot_hexbin(pop_name=True, linewidth=7)

**Comment by davidnbresch** [comment]
Yes, eg a buffer of 10% width on esch side (as we did in MATLAB ;-)

Prof. Dr. David N. Bresch 
Professor for Weather and Climate Risks
Institute for Environmental Decisions
ETH Zurich/MeteoSwiss
dbresch@ethz.ch, dbresch@meteoswiss.ch
office: +41 44 632 77 87
mobile: +41 79 770 15 92
skype: davidnbresch
www.usys.ethz.ch/en/people/profile.html?persid=49820, http://www.wcr.ethz.ch

**Comment by gabrielaznar** [comment]
yes, can use the option of plot_hexbin() 'buffer_deg' for that:

buffer_deg (float, optional): border to add to coordinates  in degrees.

**Comment by sameberenz** [comment]
Perfect, thank you for pointing out the option for me!
