### ISSUE TITLE
Docs environment has to be updated

### ISSUE THREAD

**Issue by peanutfun** [CLIMADA-project/climada_python#603]
The documentation builds on ReadTheDocs started failing due to requirements that cannot be fulfilled (anymore): https://readthedocs.org/projects/climada-python/builds/

Seems like required package versions have become (or are temporarily) unavailable. What's the process to update the `requirements/env_docs.yml` specs?

I don't know if it would help to switch to Python 3.9, see #596. On my system, the current `env_climada.yml` specs work just as well with `python=3.9`. But I guess for the `env_docs.yml` all the versions will be different then?

**Comment by emanuel-schmid** [comment]
Right. If I had to guess, some updated dependency broke it and we need to adapt. C<del>o</del>urse of time...

**Comment by peanutfun** [comment]
Alright, I'm on it 👍

**Comment by emanuel-schmid** [comment]
what do you mean, you're on it? Are you working on it? The issue's already assigned 😱

**Comment by peanutfun** [comment]
> what do you mean, you're on it? Are you working on it? The issue's already assigned 😱

Damn, I missed that 😁 But I guess I'll have to update the packages anyway for #600, because there are some new pip dependencies. I'll give it a try.

> now it fails at `latexmk`

The error is:
```
! TeX capacity exceeded, sorry [main memory size=5000000].
```
Not sure how we could reduce the memory usage of the latex compiler. But is the PDF a common use case? Sure, we advertise it, but is there any advantage over the HTML version? Should we just ditch it? 🤔

**Comment by emanuel-schmid** [comment]
I guess we can ditch it for now in the develop branch (latest) and discuss it with the group, i.g., and David, i.p. 🤔

**Comment by peanutfun** [comment]
Could you share a script or instructions how to "create" the `env_doc.yml` specs?

**Comment by emanuel-schmid** [comment]
```bash
mamba env create -n climada_doc -f requirements/env_climada.yml
conda activate climada_doc
mamba install nb_conda nb_conda_kernels
pip install nbsphinx
conda env export -n climada_doc > requirements/env_docs.yml
```

Should be done on a Linux machine I assume. I usually do it on _Red Hat Enterprise Linux 8.7_.

**Comment by peanutfun** [comment]
I'm on macOS, but ReadTheDocs uses Ubuntu, so I'm trying with Docker right now 😬

**Comment by peanutfun** [comment]
Fixed the environment and added instructions for re-creating it in #600
