### ISSUE TITLE
read_ibtracs_netcdf provides tracks with only missing values if estimate_missing is True

### ISSUE THREAD

**Issue by bguillod** [CLIMADA-project/climada_python#62]
On the develop branch I found the following issue:

Calling read_ibtracs_netcdf with estimate_missing set to True return tracks with misleading data when both pressure and wind speed data are missing.

For instance:
```
all_tracks = TCTracks()
all_tracks.read_ibtracs_netcdf(provider='usa', basin='SI', year_range=(1850, 1851))
```
correctly issues a warning:
```
climada.hazard.tc_tracks - WARNING - No valid wind/pressure values found for 1851080S15062, 1851080S15063, 1851080S21060, 1851080S21420, 1851305S08089.
```

However:
```
all_tracks = TCTracks()
all_tracks.read_ibtracs_netcdf(provider='usa', basin='SI', year_range=(1850, 1851), estimate_missing=True)
```
does not issue any warning, but the tracks that are loaded contain data that don't look correct:
- max_sustained_wind and central_pressure are all -1
- radius_max_wind and radius_oci are all 0.

I think the issue is that _estimate_pressure and _estimate_vmax convert all NaNs to -1 and then the line

```
ibtracs_ds['valid_t'] &= ibtracs_ds.wind.notnull() & ibtracs_ds.pres.notnull()
```

does not filter those out.

Is this intended and if so what will be the impact on the wind field?
I would suggest that even if estimate_missing is True, tracks without any pressure or wind information MUST be skipped, but I might be wrong.

**Comment by chahank** [comment]
Thanks @bguillod  for raising this issue! Could you please add labels to the issue?

**Comment by bguillod** [comment]
@chahank I would like to but I am not able to. How should I do that? Or perhaps I can't because I'm not a member?

**Comment by bguillod** [comment]
I guess best placed to answer is @tovogt

**Comment by bguillod** [comment]
@tovogt Thanks! Currently I observe that if these tracks are kept, the intensity and all variables are empty in the TropCyclone hazard for that event. This leads to bugs in the plotting though. I suggest that when neither vmax nor pres is available then the track is entirely skipped, but I leave it up to you to decide.

My fix would be:
last line of _estimate_pressure, add:
```
cen_pres = np.where(cen_pres == -1, np.nan, cen_pres)
```
last line of _estimate_vmax, add:
```
v_max = np.where(v_max == -1, np.nan, v_max)
```
Hope this helps.

**Comment by bguillod** [comment]
@tovogt BTW am I right that latitude and longitude informations are never read from the provider but are the "combined" values from IBTrACS? It would be nice to be able to also read those ones from a specific provider.

**Comment by tovogt** [comment]
@bguillod Your last question is offtopic. Please open a new issue for that.
