### ISSUE TITLE
Bank loan level metrics  

### ISSUE THREAD

**Issue by gamamou** [CLIMADA-project/climada_python#629]
Hello all!
Considering Climate-related events, I'm trying to estimate the Probability of Default (PD) and Loss Given Default (LGD) for a bank 's portfolio of mortgages. The issue I'm facing is that the peril and exposure default data in Climada are too coarse to assess property level PD and LGD. As an open-source tool, I know it can be reprogrammed to ingest new data, edit damage functions, and the financial modules to get to Loan-To-Value (LTV) and other loan level metrics, which could then be used to calculate PD and LGD. Any thought on this?

**Comment by peanutfun** [comment]
Hi @gamamou and thank you for your inquiry! Reprogramming is indeed not needed. We provide exemplary datasets through our [Data API](https://climada-python.readthedocs.io/en/latest/tutorial/climada_util_api_client.html) and other means to create, e.g., exposure datasets from the [LitPop](https://climada-python.readthedocs.io/en/latest/tutorial/climada_entity_LitPop.html) module.

If these datasets are not suitable for your task, you can just bring your own. For an impact calculation, Climada requires one instance each of [`Hazard`](https://climada-python.readthedocs.io/en/latest/tutorial/climada_hazard_Hazard.html), [`Exposures`](https://climada-python.readthedocs.io/en/latest/tutorial/climada_entity_Exposures.html) and [`ImpactFuncSet`](https://climada-python.readthedocs.io/en/latest/tutorial/climada_entity_ImpactFuncSet.html). You can create these objects via their default initializers, or use the various classmethods to read in data in certain file formats that we support. For example, you can use [`Hazard.from_raster_xarray`](https://github.com/CLIMADA-project/climada_python/blob/develop/climada/hazard/base.py#L413) to create a hazard object from raster data than can be read by xarray. Similarly, there is a [`Exposure.from_raster`](https://github.com/CLIMADA-project/climada_python/blob/develop/climada/entity/exposures/base.py#L465) method. Finally, you can create impact functions from, e.g., sigmoidal functions using [`ImpFunc.from_sigmoid_impf`](https://github.com/CLIMADA-project/climada_python/blob/develop/climada/entity/impact_funcs/base.py#L208) and plug them into an impact function set. Then you are ready to compute an impact.

I hope this helps!

**Comment by gamamou** [comment]
@peanutfun, thank you for your answer. This is helpful. I appreciate it.
