### ISSUE TITLE
LitPop exposures used in Impact tutorial changed considerably since October 2021

### ISSUE THREAD

**Issue by peanutfun** [CLIMADA-project/climada_python#630]
## Issue overview

#529 updated the Impact tutorial. When executing the notebook with the latest version of CLIMADA, the values of the `LitPop` exposure change considerably compared to the current `main` version. It also happens when rolling back to fe0d413e12a750aeb1049159a925b554a980a086 (October 2021), so it might be related to the underlying data or a change in default parameters for the methods used.

## Original comment

This is not related to this PR. It even happens when rolling back the source code to October 2021 (fe0d413e12a750aeb1049159a925b554a980a086). I don't have time to dig any deeper, unfortunately. But when looking at the plot output below this cell, the changes are non-trivial but quite moderate (at least big enough to spot differences with your bare eyes). I would suggest to continue this discussion somewhere else, on Slack or in a separate GitHub issue.
![image](https://user-images.githubusercontent.com/57705593/214629987-a5115fdd-7319-411f-98f8-d0c6df51f612.png)
![image](https://user-images.githubusercontent.com/57705593/214630026-6ef62297-e6ce-4f50-a9b1-decce693d109.png)

_Originally posted by @tovogt in https://github.com/CLIMADA-project/climada_python/pull/529#discussion_r1086904313_

**Comment by raphael-portmann** [comment]
Probably it depends on the underlying data no? In the tutorial it says
# Note that the file gpw_v4_population_count_rev11_2015_30_sec.tif must be downloaded (do not forget to unzip) if
# you want to execute this cell on your computer.

I remember I downloaded the most recent version (2020) of this population count file. Maybe the change is related to the version of this dataset that one uses?

**Comment by tovogt** [comment]
This data set wasn't changed since 2018: https://sedac.ciesin.columbia.edu/data/collection/gpw-v4/documentation

**Comment by peanutfun** [comment]
It looks like the results are more "smooth" now. Maybe the default exponents used in `LitPop` have changed?

**Comment by tovogt** [comment]
As far as I understand, the notebook has been executed back in October 2021 for https://github.com/CLIMADA-project/climada_python/commit/fe0d413e12a750aeb1049159a925b554a980a086. That means, by rolling back to the code base of that commit, we can easily guarantee that all model parameters are reproduced. The only reasons for changes that remain are:

* a change to the input data: GPW, nightlight and World Bank data
* changes to the conda environment (I didn't test rolling back to the requirements from October 2021)
* ...?

**Comment by peanutfun** [comment]
I'm not sure this is correct. The metadata states that the cells were executed in October 2021, but the logging messages in the output date back further. So it seems to me that the cells were executed, but the new output was somehow not saved/captured?

<img width="992" alt="Screenshot 2023-01-27 at 10 01 09" src="https://user-images.githubusercontent.com/34276446/215047948-6c25e3f5-f37d-42e1-9d9a-9ea6e2bfbaa1.png">

**Comment by tovogt** [comment]
Okay, I think that the plot output comes from 9ad3f3dbe143642e8cda8b293c813f074d4bec6d where we actually had a different implementation of LitPop with different default parameters, including a different reference year. Furthermore, the resolution in the tutorial notebook was set to 10 km, but has been changed to 1 km (30 arc-seconds) later.

So, I think this settles this question and we can safely close this.

**Comment by peanutfun** [comment]
Gladly, thank you for digging into this! 🙌
