### ISSUE TITLE
Unsequa

### ISSUE THREAD

**Issue by gamamou** [CLIMADA-project/climada_python#639]
Hello everyone,

I'm modeling uncertainty using the Unsequa module. The desired outcome is a data frame including risk measures (AAI, Impact at event, PMI, EAI, etc.) for each return period. Using the helper, I maintained the same exposure and hazard and passed them to InputVar. However, I varied the impact function bounds for mdd, paa, and FI. When I attempted to execute output_imp.get_uncertainty().tail(), I got a data frame with the modified PAA,MDD, and FI values rather than the risk metrics. What am I missing here? Please see below for further details.

Thansk

**Exposure:**
bounds_totval = None
bounds_noise = None
exp_iv = InputVar.exp([My exp_base], bounds_totval, bounds_noise)

**Hazad:**
bounds_freq = None
bounds_int = None 
n_ev = None
haz_iv = InputVar.haz(My haz_base, n_ev=n_ev, bounds_freq=bounds_freq, bounds_int=bounds_int)

**Impact Function**
from climada.entity import ImpactFuncSet, ImpfTropCyclone
impf = ImpfTropCyclone.from_emanuel_usa()
impf_set_base = ImpactFuncSet()
impf_set_base.append(impf)

bounds_impfi = [-10, 10] 
bounds_mdd = [0.7, 1.1] 
bounds_paa = [0.2,0.5]
impf_iv = InputVar.impfset(My impf_set_base,
                           bounds_impfi=bounds_impfi,
                           bounds_mdd=bounds_mdd,
                           bounds_paa=bounds_paa,
                           haz_id_dict={'TC': [1]})

calc_imp = CalcImpact(exp_iv, impf_iv, haz_iv)
output_imp.get_uncertainty().tail()

**Comment by gamamou** [comment]
@peanutfun , please see below.
<img width="485" alt="image001 (1)" src="https://user-images.githubusercontent.com/57597860/216637886-7a520c82-dc93-4bce-9c0c-14cc8a4bd36d.png">

**Comment by gamamou** [comment]
@peanutfun ,
I would like to get an output like this using the same scripts previously provided.
![image](https://user-images.githubusercontent.com/57597860/216638802-8103a49a-01bd-43d7-bee4-b95471576330.png)

**Comment by gamamou** [comment]
@peanutfun 
I think found the issue. There was no centroid associated with the exposure for the hazard input. I realized that when dealing with tracks from the IBTracks , the Calc_imp would only work when centroids are defined for exposure. Thank you for looking into this.

**Comment by emanuel-schmid** [comment]
@gamamou 
Excellent! Glad you found that. 😄 
As for the RP looking all the same - I'm afraid we can't really help you unless you provide the full script (as text) that produced this result, together with the input data. Could you please open a new issue including this information? Many thanks!
