### ISSUE TITLE
Building documentation locally fails partly on Windows

### ISSUE THREAD

**Issue by emanuel-schmid** [CLIMADA-project/climada_python#641]
Windows cannot handle the symbolic links in the `doc/misc` directory.
The documentation builds but in the Miscellaneous section of the menu all links but the one to the Python modules are omitted.

- duplication of files is out of question

- relative links starting with `../` don't work for sphinx. Afaik there is currently no way to include files from outside the toctree in the documentation build

- switching the links (i.e.: moving the files into `doc/misc` and linking from `./` is not a solution. Although the documentation would fully build on Windows, the files cannot be accessed anymore on GitHub.

All I can come up with is to add a note especially for Windows users in the `doc/README.md` file. 
Ideas are welcome!

**Comment by peanutfun** [comment]
Did you try this: https://stackoverflow.com/questions/5917249/git-symbolic-links-in-windows/59761201#59761201 ?

**Comment by peanutfun** [comment]
@emanuel-schmid You mentioned this issue yesterday, if I am not mistaken. Did you try out my suggestion above?
