### ISSUE TITLE
UNSEQUA-Issue with Frequency curve for different  RPs 

### ISSUE THREAD

**Issue by gamamou** [CLIMADA-project/climada_python#643]
Hello all,
When running uncertainty analysis, I got an output matrix showing identical values for different return period. Any thought on how to overcome this? Please see below scripts.

Dataset head:

<img width="615" alt="image001 (4)" src="https://user-images.githubusercontent.com/57597860/216928255-fd428f15-40c5-40ad-9220-0cdeb09556b7.png">

scripts
<img width="534" alt="image001 (3)" src="https://user-images.githubusercontent.com/57597860/216927269-4ff30d6c-7a25-49db-bcfb-9d9bb06dc4e2.png">
<img width="629" alt="image002" src="https://user-images.githubusercontent.com/57597860/216927454-6e58ad46-068c-4409-a4a8-78d4a113edc6.png">
<img width="460" alt="image003" src="https://user-images.githubusercontent.com/57597860/216927562-418b028c-bc0a-44f0-b299-02a078e8dfc5.png">
<img width="472" alt="image004" src="https://user-images.githubusercontent.com/57597860/216927638-e740545d-461b-470a-aff5-5c3cdb8986c9.png">

**Comment by emanuel-schmid** [comment]
@gamamou 
Thanks a lot for the input! Would you mind to post the complete notebook - or copy and paste the content of the cells as code/text instead of images?

**Comment by gamamou** [comment]
@emanuel-schmid ,
Thank you so much for taking a look at this. There are some restrictions in place preventing me from sharing the file or code. However, I have realized that the issue is related to the scale of the frequency curve plot. The x-axis has a max value of 6 for the RP (I' don't know why). If a chose a RP ranging anywhere from 1 to 6, I got a nice output with different value for each of the RP. When I chose a RP beyond 6 (the max on the x-axis), I got identical values for each RP. The question now becomes, how to expand the value on the x-axis to include larger RP values. 

![image](https://user-images.githubusercontent.com/57597860/217006083-24f919ae-3412-4626-b7f2-495ae33c8061.png)

![image](https://user-images.githubusercontent.com/57597860/217006624-c3175ede-0483-4ab7-aa91-55c41135f7f8.png)

**Comment by peanutfun** [comment]
Just a quick thought: The return periods for events are comuted from the frequency of the hazard events and the time span comprising them. If you only have a hazard event set spanning 6 years, you cannot compute longer return periods. But again, without data or a full script we can execute to recreate the error we cannot provide more help

**Comment by gamamou** [comment]
@peanutfun ,
Thank you for your feedbacks. This is very helpful. I think that's exactly the issue. My set of events consist of Tropical cyclones in the NA basin spanning from 2017 to 2022. So, becaude the  IBTrack data spans from 1840 to present, does this mean I cannot produce frequency curce for RT of 200 or greater years for TCs ?

**Comment by peanutfun** [comment]
Correct. You need information on how an event with a 200y return period looks like to compute the exceedance frequency curve for return periods up to 200y.
