### ISSUE TITLE
Python module docs empty because 'sparse' is not part of `env_docs.yml` (anymore)

### ISSUE THREAD

**Issue by peanutfun** [CLIMADA-project/climada_python#647]
Many module docs are not built because `sparse` cannot be imported, see https://climada-python.readthedocs.io/en/latest/climada/climada.hazard.html#climada-hazard-base-module

<img width="1391" alt="Screenshot 2023-02-08 at 09 48 30" src="https://user-images.githubusercontent.com/34276446/217480309-dc9824ed-68c1-4ed2-92df-a6f0e33c0b62.png">

The [doc build logs](https://readthedocs.org/projects/climada-python/builds/19395235/) are full of errors like these:

```
WARNING: autodoc: failed to import module 'engine.calibration_opt' from module 'climada'; the following exception was raised:
No module named 'sparse'
WARNING: autodoc: failed to import module 'engine.cost_benefit' from module 'climada'; the following exception was raised:
No module named 'sparse'
```

**Comment by emanuel-schmid** [comment]
This will be fixed by when #622 is merged (today I hope).

**Comment by peanutfun** [comment]
Excellent, thanks for handling that! Btw, there is a setting in Sphinx that turns warnings like these into build errors. We could enable that, but that would require to resolve all other Sphinx warnings first 😬 

See https://docs.readthedocs.io/en/stable/config-file/v2.html#sphinx-fail-on-warning

**Comment by emanuel-schmid** [comment]
🤣

**Comment by peanutfun** [comment]
The issue is still not resolved. I think this is because the [builds fail](https://readthedocs.org/projects/climada-python/builds/19430159/). I don't see the error in the log for building the HTML files anymore, but the build fails when running LaTeX. I think this causes the new build outputs not to be uploaded.

**Comment by emanuel-schmid** [comment]
Yes, I can confirm that. My guess is that the new environment had implications for the LaTeX engine running the pdf build. Now it's less tolerant.
I got rid of the memory issue, but the CLIMADA_logo_QR1.png is still "not a PNG file" in their eyes. Also the '.svg' files present a 'Unknown graphics extension' to them.
My current plan is to first build it locally, which I am not yet able to (although for other reasons).
Until I get there, we may just skip the PDF build for now, so we can at least have a look at the html version. Where is the switch for that? Just remove the pdf entry or the whole formats block in .readthedocs.yml file?

**Comment by peanutfun** [comment]
I just switched off "Enable PDF build" in the Advanced Settings on readthedocs.org, let's see if that's enough.

Are we using the PDF version of the docs at all?

**Comment by peanutfun** [comment]
> I just switched off "Enable PDF build" in the Advanced Settings on readthedocs.org, let's see if that's enough.

It's not. We have to turn off the PDF build in the `.readthedocs.yml`

**Comment by emanuel-schmid** [comment]
> Are we using the PDF version of the docs at all?

Well, at least we promote it in the README page...

**Comment by emanuel-schmid** [comment]
The HTML pages are building [again](https://github.com/CLIMADA-project/climada_python/commit/2ef5d4141c419ee319c7f2b629112deff49a3d69)

**Comment by peanutfun** [comment]
Great work!

> Well, at least we promote it in the README page...

So, we stop promoting it? 😅

**Comment by emanuel-schmid** [comment]
The pdf build still fails to some extent. I've fixed a couple of issues but one remains: the status indicators (DOI, build and docs) at the top of the README page resist to be integrated.

We have several options

a) abandon pdf build altogether
b) don't include the README page in the documentation
c) abandon pdf build in develop, and deviate the main branch from develop so that the README page is excluded from the documentation in main
d) figure out how to integrate the status indicators in the pdf build

(I've tried to exclude the README page from the pdf _build_. That didn't work out, so that is not an option)

My personal favorites are a) and b). The other ones seem to much effort for a questionable achievement.

**Comment by peanutfun** [comment]
If the README is the only issue, I think we can leave it out of the documentation. But if we don't need the PDF build at all, why bother? I personally see no use case for it. Why pass the PDF to somebody if they can simply open a webpage? Sure, you need internet access for that, but how far do you get with CLIMADA if you don't have internet access? 🤔

**Comment by chahank** [comment]
Just to pitch in: I appreciate to have a .pdf build for offline working for instance during long train travels.
