### ISSUE TITLE
Line & Polygon interpolation cannot handle metre disaggregation when already in a projected crs

### ISSUE THREAD

**Issue by Evelyn-M** [CLIMADA-project/climada_python#648]
Concerns the util.lines_polys_handler module:

If exp.gdf is already in a metre-based reference system, the kwarg `to_metres=True`  is somewhat ambiguous, since the code currently tries to re-project from a metre-based reference system to a metre-based reference system (and hence fails), as pointed out by @thomini.

Should be an aasy fix by checking if already in a "useful" crs, and dont reproject in that case.
Error could also be avoided by simply putting `to_metres=False`, yet perhaps not so user-friendy / intuitive.

```
exp_pnt = u_lp.exp_geom_to_pnt(
    exp, res=1000, to_meters=True,
    disagg_met=u_lp.DisaggMethod.DIV, disagg_val=None
)
```
![image001](https://user-images.githubusercontent.com/42063186/217483241-d6dc354a-0b26-4a4b-98c3-3ca53a498b55.png)

**Comment by peanutfun** [comment]
@Evelyn-M was this resolved by #666? If yes, feel free to close this issue
