### ISSUE TITLE
Remove `requirements/env_docs.yml`

### ISSUE THREAD

**Issue by peanutfun** [CLIMADA-project/climada_python#654]
As tested in #649, the readthedocs environment does not run out of memory anymore when building the conda environment based on the default `env_climada.yml` specs, see the corresponding [build logs](https://readthedocs.org/projects/climada-python/builds/19418163/). Installing the dependencies just takes a bit longer, some 320 sec as opposed to 250 sec. This gives us the opportunity to remove the `requirements/env_docs.yml` altogether, which currently causes a considerable maintenance overhead. The downside is that we can only specify a *single* environment file for readthedocs. This means that the dependencies for building the documentation have to be moved to the base image specs in `env_climada.yml`.

**Comment by emanuel-schmid** [comment]
Actually, I think the overhead of a separate env_docs.yml file is justified. Although it may work at the moment without hitting memory boundaries, there is no guarantee that it will stay like that.

**Comment by peanutfun** [comment]
I find updating the `env_docs.yml` quite tedious because I have no native Ubuntu environment and have to employ Docker to set it up. Also, issues with the environment are mostly silent, as seen in #647. If we stick with the `env_docs.yml`, I at least want the docs to fail if expected packages are missing, but for that we need to [resolve all Sphinx warnings](https://github.com/CLIMADA-project/climada_python/issues/647#issuecomment-1422435563) first.

**Comment by peanutfun** [comment]
In the meantime, we decided to keep the current setup until something breaks and maintenance becomes to cumbersome.

**Comment by peanutfun** [comment]
Removed with #687
