### ISSUE TITLE
Upgrade shapely to v2.0.1

### ISSUE THREAD

**Issue by Evelyn-M** [CLIMADA-project/climada_python#655]
Shapely 2.0 is out, which brings many useful functionalities, most importantly the integration of pygeos functionalities (for vectorized operations!). A lot of other packages (such as geopandas etc., may require shapely 2.X in the future, too).
We should check out what other changes this entails, a lot of our operations in climada currently trigger warnings that they will fail under this new version, such as multi-part geometries ceasing to be iterables. A lot of other packages (such as geopandas etc., may require shapely 2.X in the future, too).

We're currently at 1.8, some migration instructions (and updates):
https://shapely.readthedocs.io/en/stable/migration.html

**Comment by peanutfun** [comment]
Bummer: We do not restrict the version of shapely ourselves. The packages that require shapely in our dependency tree are geopandas and cartopy. Geopandas >=0.12 [supports shapely 2.0](https://github.com/geopandas/geopandas/blob/main/CHANGELOG.md#version-012-october-24-2022), but cartopy [does not](https://scitools.org.uk/cartopy/docs/latest/whatsnew/v0.21.html). We cannot upgrade to shapely 2.0 until a release of cartopy supports it.

**Comment by emanuel-schmid** [comment]
Looks like cartopy can deal with it now
https://github.com/conda-forge/cartopy-feedstock/commit/61104dde5777e722a0584ce5f682b13564f6e231
https://github.com/SciTools/cartopy/issues/2076

**Comment by peanutfun** [comment]
@Evelyn-M Do you want to give this a try? You will have to remove the [version pin](https://github.com/CLIMADA-project/climada_python/blob/main/requirements/env_climada.yml#L7) on Cartopy and build a new conda environment. This should install cartopy v0.21.1, which is compatible with shapely v2.

**Comment by peanutfun** [comment]
After #682, we support shapely v2.0. Upgrading makes sense because it provides a significant performance boost.
