### ISSUE TITLE
haz.plot_intensity fails after using Hazard.from_xarray

### ISSUE THREAD

**Issue by thomini** [CLIMADA-project/climada_python#657]
I tried to use `Hazard.from_xarray` to load a `xarray.Dataset` as CLIMADA hazard:

```python
import xarray as xr
from climada.hazard import  Hazard

ds = xr.open_dataset('xyz.nc')

# reads a dataset -- this is only available in the development package!
haz = Hazard.from_raster_xarray(data = ds, 
    coordinate_vars = dict(event="time", longitude="x", latitude="y"), 
    intensity = 'TX',
    hazard_type = 'HT', 
    intensity_unit='degC', 
    crs='EPSG:3416') #works without errors/warnings

haz.check() #works without errors/warnings

print(haz.centroids.geometry.crs)
"""EPSG:3416"""

haz.plot_intensity(event=2) 
```

But in the last line I got the following error msg:
```python
Traceback (most recent call last):
  File "/conda/citsys/miniconda3/envs/climada_env_dev/lib/python3.9/site-packages/cartopy/mpl/geoaxes.py", line 909, in set_extent
    x1, y1, x2, y2 = projected.bounds
ValueError: not enough values to unpack (expected 4, got 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  ...
  File "/conda/citsys/miniconda3/envs/climada_env_dev/lib/python3.9/site-packages/cartopy/mpl/geoaxes.py", line 911, in set_extent
    raise ValueError(
ValueError: Failed to determine the required bounds in projection coordinates. Check that the values provided are within the valid range (x_limits=(107674.1001143264, 694885.8414785322), y_limits=(284902.9479101519, 575905.4776601079)).
```

Is there anything I did wrong here? (obviously yes, but what?) Do I have to take care of the CRS before plotting?

FYI the `xarray.Dataset` looks like this:
![image](https://user-images.githubusercontent.com/118282246/219383535-239d36cc-cb65-40fa-8e90-eb1a5d97d659.png)

Thank you very much!!

**Comment by thomini** [comment]
@peanutfun Thank you for your help via email so far! I did not encounter a warning `Error parsing coordinate system …` and also the CRS seems to stay the same as in the original dataset (EPSG:3416).

**Comment by peanutfun** [comment]
I found this SO thread where a similar issue occurs: https://stackoverflow.com/questions/54569028/ignore-projection-limits-when-setting-the-extent They resolve it by building their own projection with adjusted extent limits.

Apparently, cartopy uses the limits set by proj4 for the respective CRS, which can sometimes be wrong or too restrictive. The extents reported in your error message do not match the ones reported here: https://epsg.io/3416

My proposal would be to transform the coordinates into a globally applicable CRS like the default EPSG:4326 before plotting.

**Comment by thomini** [comment]
Thank you @peanutfun! I am trying to transform the coordinates to the default EPSG:4326 - can you recommend a standard way of doing so for the hazard class? Or should I find a way of transforming the original data before using the function `Hazard.from_xarray_raster`?

**Comment by thomini** [comment]
**Update**

Problem solved using `rioxarray`, for example:

```
import rioxarray
import xarray
ds = xarray.open_dataset(...)
ds.rio.reproject("EPSG:4326")
```

Then plotting works!
 
I close the issue.

**Comment by peanutfun** [comment]
Great solution, thanks for reporting back!
