### ISSUE TITLE
Create conda package for Climada

### ISSUE THREAD

**Issue by peanutfun** [CLIMADA-project/climada_python#660]
Since we use Anaconda to manage most of our dependencies, it would make sense to create a conda package ourselves for installing Climada. Users that do not want to develop Climada and are happy with the stable version could then simply execute
```
conda install climada
```
to have Climada (and all its dependencies) available.

Having a conda package on conda-forge requires to maintain a [recipe](https://conda-forge.org/docs/maintainer/adding_pkgs.html#) whose initial version can be created using [grayskull](https://github.com/conda/grayskull#introduction).

**Comment by peanutfun** [comment]
I gave this a try. The only issue I currently see is `pybufrkit`, because it is not available from `conda`. Once #662 is merged, we need to release a new Climada version on PyPI. Building the conda recipe should then work fine.

**Comment by peanutfun** [comment]
Climada is now a standalone package on conda-forge: https://github.com/conda-forge/staged-recipes/pull/22191

See https://anaconda.org/conda-forge/climada

**Comment by emanuel-schmid** [comment]
🍾 Excellent!
