### ISSUE TITLE
Remove `pybufrkit` from list of requirements

### ISSUE THREAD

**Issue by peanutfun** [CLIMADA-project/climada_python#661]
`pybufrkit` is listed in the conda and pip requirements, but the package is never used. I guess the related code was deleted or changed? My proposal is to simply remove it from the requirements.

**Comment by chahank** [comment]
This was used to get WMO data at some point. But it is possible that the code was changed to not using this package anymore. In this case, I would be strongly in favor of removing it from the requirements.

Thanks!!

**Comment by peanutfun** [comment]
Fixed by #662

**Comment by emanuel-schmid** [comment]
post closing remark: wmo and BUFR are still active in petals' `tc_tracks_forecast` module.
(and pybufrkit potentially required by `eccodes.codes_bufr_new_from_file`?)

**Comment by peanutfun** [comment]
`eccodes` does not require `pybufrkit`, see https://github.com/ecmwf/eccodes-python/blob/develop/setup.py#L45
