### ISSUE TITLE
Issue with damage computation from TC surge 

### ISSUE THREAD

**Issue by gamamou** [CLIMADA-project/climada_python#664]
Hello all,
I'm trying to compute impact from hurricane Irma on Florida using the impact calc method and the TcSurgebuthtub class (from Petals). Can the natural Impact Calc method in Climada Core combine exposure, surge data provided by the TCsurgebathtub as hazard input and the impact function set defined by TS to estimate damage or impact?
Please see below the error message I'm getting.
 Also, I have attached the Jupiyter file for codes.  Any thought on this? 
![image](https://user-images.githubusercontent.com/57597860/221375773-76218432-5487-469a-9537-e2c68b18affa.png)
[TCsurge.zip](https://github.com/CLIMADA-project/climada_python/files/10832107/TCsurge.zip)

**Comment by emanuel-schmid** [comment]
Hi @gamamou! Thanks for raising this but sorry, imho, this is not reallly qualifiying as an issue with climada as software, but rather with your program or your data.
Perhaps, you may try to make a minimal reproducible example and ask the question on Stackoverflow?
Having said that - the error message says that there is a `ValueError: Missing exposures impact functions impf_.`
Have you checked that?
In any case: good luck 😄

**Comment by gamamou** [comment]
@emanuel-schmid , Thank you for investigating this. While CLIMADA is gaining in popularity, few individuals outside of the ETH community are proficient in its use. Therefore, the likelihood of finding someone on Stackoverflow who can answer CLIMADA-related queries at this time is fairly low. In my post, I actually raise points that are absent from the tutorial. Before posting my message, I first checked the error message and searched the Internet for a solution. I'm hopping to see a CLIMADA-specific blog where such questions can be discussed. Many thanks for your time.

**Comment by chahank** [comment]
Dear @gamamou, we really cannot offer personalized consulting for applying CLIMADA. Good luck and don't hesitate please use Stackoverflow.
