### ISSUE TITLE
Improve impact calc error messages

### ISSUE THREAD

**Issue by chahank** [CLIMADA-project/climada_python#669]
Currently, the `ImpactCalc.impact()` method generates non-understandable error messages if the input data is inconsistent.  For instance, if the input `Hazard` object has type `Hazard.haz_type = ''`, the impact computation fails. Smilarly is probably the case if the `Exposures` has no properly defined `impf_haz_type` column.

**Comment by leonie-villiger** [comment]
I could reproduce the issue by setting the `Hazard.haz_type = ''` before applying ImpactCalc.impact(). But what do you mean with the `impf_haz_type` in the `Exposure`? For instance, if I load a exposure layer through the data API (e.g., `exp = client.get_litpop(exponents=(0,1), country='CHE')`) I don`t have a column `impf_haz_type`...  do you simply mean if the `impf_` column is missing?

**Comment by chahank** [comment]
The column `impf_{haz_type}` (haz_type must be replace with the hazard type, e.g. 'RF') must be there to make an impact computation. If it is missing, the impact computation fails with a cryptic message.

**Comment by leonie-villiger** [comment]
Ok, could reproduce the error 😃 E.g., with <impf_TC> in the <Exposure> and <haz_type = WC> in the <Hazard> yields an error. However, climada also allows to leave the hazard type unspecified in the <Expsoure>, i.e., <impf_> (with an empty hazard type) as long as the hazard type is specified in the <Hazard>. Anyway, I'll try to implenent an improved error message.

**Comment by leonie-villiger** [comment]
Issue solved with pull request #691

**Comment by luseverin** [comment]
There is stil a confusing error message when one uses the `ImpactCalc.impact()` when the impact function id of the `impf_haz_type` column from the `Exposures` has no match in the `ImpactFuncSet`.

**Comment by peanutfun** [comment]
Fixed by #863
