### ISSUE TITLE
Read storm type ("nature") from IBTrACS data

### ISSUE THREAD

**Issue by peanutfun** [CLIMADA-project/climada_python#674]
@ChrisFairless proposed to read the storm type data from IBTrACS data in PR #646:

> Changes proposed in this PR:
>
> * When creating a trackset from IBTrACS also read the 'Nature' of a storm. The nature gives information about whether a system is a disturbance, tropical storm, post-transition extratropical storm, or subtropical storm (or whether agencies disagree or don't report). This is potentially useful in visualisations and for generating synthetic tracks.

@tovogt https://github.com/CLIMADA-project/climada_python/pull/646#issuecomment-1420974181:

> I tend to prefer supporting a keyword argument for "other variables" to include instead of adding explicit support for the "nature" variable. Maybe we can start by supporting non-agency-specific variables, because the agency-specific need to be treated a bit differently?

**Comment by bguillod** [comment]
I assume this can be closed following PR #728
If not please re-open
