### ISSUE TITLE
upgrade rasterio 1.2 -> 1.3

### ISSUE THREAD

**Issue by emanuel-schmid** [CLIMADA-project/climada_python#683]
**Failing Tests**
- `climada.test.test_litpop_integr.TestAdmin1.test_brandenburg`
- `TestLitPopExposure.test_netherlands150_pass`

`rasterio.warp.reproject` used to throw a `ValueError` when either the source or the target were empty. Now it throws a `rasterio._err.CPLE_AppDefinedError`, with a different error message.

**Comment by peanutfun** [comment]
Seems like #512 resolved itself?

**Comment by peanutfun** [comment]
Upgraded with #682
