### ISSUE TITLE
upgrade shapely 1.8 -> 2.0

### ISSUE THREAD

**Issue by emanuel-schmid** [CLIMADA-project/climada_python#684]
**Failing Tests**

- `climada.hazard.test.test_tc_tracks.TestIO.test_to_geodataframe_line`

With 1.8 a `MultiLineString` used to be iterable. This is not the case for 2.0. Iterations must be made over `MulitLineString.geoms`.

**Comment by peanutfun** [comment]
Upgraded with #682
