### ISSUE TITLE
upgrade matplotlib 3.5 -> 3.7

### ISSUE THREAD

**Issue by emanuel-schmid** [CLIMADA-project/climada_python#685]
**Failing Tests**

- `climada.engine.unsequa.test.test_unsequa.TestOutput.test_plot_unc_cb`

`DataFrame.plot(kind='bar', yerr=error_df)` used to work fine with empty columns (all values NaN) in the error_df.
Since 3.7 (3.6?) this runs into a `StopIteration` exception.

**Comment by peanutfun** [comment]
Upgraded with #682
