### ISSUE TITLE
impact: Exceedance frequency at exposure centroid level

### ISSUE THREAD

**Issue by sameberenz** [CLIMADA-project/climada_python#7]
Hi everyone

with the Impact class, the EAI (expected annual impact) values at each exposure point is computed saved per default as "eai_exp".

**Question:**
Do you know of a method to get something like _"impact exceeded every N years"_ per exposure coordinate?
I guess, I need to calculate the full impact matrix by putting _save_mat=True_(?)
From there on, how would you proceed?

(To clarify, I want to plot a map showing the impact that is expected to be exceeded every 10 or 50 years per exposure coordinate)

**Comment by davidnbresch** [comment]
Let's discuss at the hackathon, but you're right, in essence you set save_mat=True and might start experimenting with not too many exposure points ;-)

**Comment by gabrielaznar** [comment]
@sameberenz this is already implemented and finished, right?

**Comment by sameberenz** [comment]
The functionality has been added.
To compute and plot exceedance impact maps for different return periods, the method **plot_rp_imp()** of the class **[Impact](https://github.com/CLIMADA-project/climada_python/blob/master/climada/engine/impact.py)** can be called. 

Commit: https://github.com/CLIMADA-project/climada_python/commit/1043689ea4bffcbf9d26a4aa412e76804777c6a6#diff-00c41206ade9f8439711b632fdcfba8b
