### ISSUE TITLE
upgrade pandas 1.5 -> 2.0

### ISSUE THREAD

**Issue by emanuel-schmid** [CLIMADA-project/climada_python#700]
`append` and `iteritems` are no longer methods of pandas DataFrame.

**Failing Tests:**

- `climada.engine.unsequa.test.test_unsequa.TestCalcCostBenefit.test_calc_sensitivity_pass`
- `climada.engine.unsequa.test.test_unsequa.TestCalcCostBenefit.test_calc_uncertainty_pass`
- `climada.engine.unsequa.test.test_unsequa.TestCalcCostBenefit.test_calc_uncertainty_pool_pass`
- `climada.engine.unsequa.test.test_unsequa.TestCalcImpact.test_calc_sensitivity_morris_pass`
- `climada.engine.unsequa.test.test_unsequa.TestCalcImpact.test_calc_sensitivity_pass`
- `climada.engine.unsequa.test.test_unsequa.TestOutput.test_plot_unc_imp`
- `climada.engine.unsequa.test.test_unsequa.TestOutput.test_save_load_pass`
- `climada.util.test.test_lines_polys_handler.TestGeomImpactCalcs.test_calc_geom_impact_mixed`
- `climada.util.test.test_lines_polys_handler.TestGeomImpactCalcs.test_impact_pnt_agg`

**Comment by chahank** [comment]
`iteritems` must apparently be replaced with `items` and `append` with `pd.concat`.

**Comment by ThomasRoosli** [comment]
Another possible stopper for the update is apparently the `pandas.Series.resample()`/`pandas.DataFrame.resample()`/`pandas.Grouper` methodologies that no longer accepts the deprecated parameter `base`.
This could be another reason for some of the failing tests.

**Comment by chahank** [comment]
All the unsequa tests are now passing after merging of PR https://github.com/CLIMADA-project/climada_python/pull/763 .
