### ISSUE TITLE
impact_data overhaul

### ISSUE THREAD

**Issue by emanuel-schmid** [CLIMADA-project/climada_python#708]
The module could use a major refactoring.

Also it's perhaps better suited for climada_petals than core.

**Comment by peanutfun** [comment]
What's the problem with the module? What exactly needs to be refactored?

As this seems quite vague to me, I would prefer to either close this issue or specify an exact task/problem to be tackled.

**Comment by emanuel-schmid** [comment]
👍  is a discussion now: #722
