### ISSUE TITLE
Update tutorials (working group)

### ISSUE THREAD

**Issue by ChrisFairless** [CLIMADA-project/climada_python#72]
We started work to update the CLIMADA tutorials and had our first meeting on 29 Sept 2020. This issue summarises the discussion and gives us a place to continue it.

---

**Summary of the Tutorial update session:** (thanks @chahank)
A few general points were addressed and summarised in https://etherpad.wikimedia.org/p/CLIMADA-Tutorials . You are all welcome to give your opinion. Furthermore, we distributed the task to update different tutorial notebooks to different team members. We still need more persons that would help.

Not assigned are the [notebooks](https://github.com/CLIMADA-project/climada_python/tree/develop/doc/tutorial) BlackMarble, Exposures_polygons_lines, LitPop, openstreemap, RiverFlood, StormEurope, TropCyclone, drought, emulator, entity_crop, util_earth_engine, MeasureSet. Maybe not all need an update, but if you can take up one (you do NOT need to be an expert) and update it according to the points mentioned in the link above, please feel free to do so.

Please let @chahank know if you want to work on a given tutorial, or comment here. We would like to avoid two person working on the same document.

We agreed to make the updates until Monday 12.10.2020 and meet again on this date at 14:30. Contact @chahank for a meeting invite.
Thanks to all of you!

---

We're collecting work on the `tutorial_update` branch. Since most people are only working on one document there won't be many conflicts, so you can ususally push directly to the branch (make sure you're up to date and there aren't conflicts by pulling first). 

Currently assigned:
- Main outline tutorial @ChrisFairless 
- Exposure @Evelyn-M
- Hazard @simonameiler
- Impact, impact data @chahank
- Impact functions/IFS @manniepmkam
- Discount rates @samluethi

**Comment by tovogt** [comment]
Did you discuss the issue that tutorial files are quite large? Many changes will generate a lot of data in the git history that will increase the repository size considerably over time. This could be prevented by storing only versions with stripped output in git and providing compiled version either on an external server or by having a single commit at the top of the main branch that would contain only the most recent version of the outputs (described here: http://www.iiasa.ac.at/web/home/research/researchPrograms/air/ECLIPSEv5a.html).

**Comment by chahank** [comment]
Good point. No, we did not discuss this too much yet.

**Comment by Evelyn-M** [comment]
Exposures tutorial is updated now,  pushed it to develop with this [commit](https://github.com/CLIMADA-project/climada_python/commit/77e3880743fe8e49d15320a6a29692d175bec892)

**Comment by chahank** [comment]
Thanks @Evelyn-M . Just FYI, we have a branch for the tutorial updates, and it is probably simpler to first update all tutorials in that branch, and then only push all the changes to the develop branch.

**Comment by chahank** [comment]
What are the tutorials that require some more improvements?

There is no tutorial on the cost benefit part / option apraisal. Did it go missing?

**Comment by tovogt** [comment]
@chahnk @emanuel-schmid How is it possible that the `tutorial_update` branch has been removed? It contained changes that now seem to be completely lost.

**Comment by chahank** [comment]
@emanuel-schmid : can we close this issue?
