### ISSUE TITLE
`CostBenefit` verbosity

### ISSUE THREAD

**Issue by emanuel-schmid** [CLIMADA-project/climada_python#725]
The methods `calc`, `combine_measures` and `apply_risk_transfer` print a lot of data to stdout with raw `print` statements.

Climada should provide a way to opt out of this verbositiy.

**Comment by peanutfun** [comment]
I think it would be better to pipe the output through the logger. Its output can be configured with the `climada.conf` and would not require a verbosity parameter

**Comment by emanuel-schmid** [comment]
I'm still pondering. I agree, `print` is hideous and must be replaced by `log`.  On the other hand the content and the way it's printed point to the direction that it was actually meant to be piped into a file or something as a result kind of thing. I mean, when you look at it:
```
Measure              Cost (USD m)    Benefit (USD m)    Benefit/Cost
-----------------  --------------  -----------------  --------------
Mangroves                 1106.8            909.752      0.821962
Beach nourishment         1458              717.969      0.492434
Seawall                   7491.47             3.1775     0.000424148
Building code             7762.5            811.979      0.104603

--------------------  --------  -------
Total climate risk:   3247.91   (USD m)
Average annual risk:  3247.91   (USD m)
Residual risk:         805.037  (USD m)
--------------------  --------  -------
Net Present Values
```
this is just not a log entry to me. 🧐
