### ISSUE TITLE
Problems with figures in PDF report

### ISSUE THREAD

**Issue by JoMSPH** [CLIMADA-project/climada_python#757]
Hello, 

i installed the CLIMADA App with the zip i got from EIOPA following all the prerequisites and the simple instuctions from the docs online. Everything works pretty well except the figures in the PDF report are not shown correctly. There is just the caption and i white box. The first figure:  stacked aggregated distribution for all countires is shown correctly.

Unfortunately my coding is really bad, so i could not figure it out on my own. 

Thank you for helping me!

**Comment by chahank** [comment]
Thank you for reaching out! Unfortunately, we are not able to help you further with this question. The CLIMADA app was developed by EIOPA and any issues / question regarding its functioning must be addressed to them directly. 

Alternatively, you could consider to install and use the CLIMADA python version following the detailed tutorials https://climada-python.readthedocs.io/en/stable/

**Comment by JoMSPH** [comment]
Thank you for your answer!
