### ISSUE TITLE
Importing the `unsequa` module unconditionally adjusts matplotlib style

### ISSUE THREAD

**Issue by peanutfun** [CLIMADA-project/climada_python#758]
When importing anything from the `unsequa` module, the file `climada/engine/unsequa/unc_output.py` is parsed, in which a matplotlib style is set and some configuration parameters are adjusted. This cannot be avoided and affects all following plots, not just the ones created by the unsequa module. Is there a particular reason for that behavior?

If the style is really desired for output of the unsequa module, we can wrap this into a function or context that is only applied when unsequa plotting functions are called.

If not, we can simply remove these lines, see https://github.com/CLIMADA-project/climada_python/blob/main/climada/engine/unsequa/unc_output.py#L67

**Comment by chahank** [comment]
Good point. Can we make a solid solution for all plots in CLIMADA at once at little costs? If not, I fully agree to remove them as you propose (maybe we make one quick check that the default graphs are then not too ugly).

**Comment by peanutfun** [comment]
We could create our own [style sheet](https://matplotlib.org/stable/tutorials/introductory/customizing.html#using-style-sheets) and have a function shortcut that enables the style. The default behavior could be added as an entry in the `climada.conf`.

But I am wondering why we would bother. The default matplotlib style is not *really* beautiful, but it's also far from ugly. Why not leave it as is?

**Comment by chahank** [comment]
Well, I think it would actually be nice to have a good set of plotting methods that look good for CLIMADA objects. The default matplotlib methods in general are just barely ok. But, this is a larger endeavor.

**Comment by peanutfun** [comment]
I see the plotting methods and their options (e.g., `hexbin` with a specific grid size) as distinct from the plotting styles that can be set via `plt.rcParam`. Sure, there is an overlap when it comes to linewidths and markersizes, but overall, I think setting styles should be left to the user, and Climada should only access plotting methods.

**Comment by chahank** [comment]
Matplotlib styling was removed from the unsequa module in merged PR #763 .
