### ISSUE TITLE
Move `data` directory *into* the climada package

### ISSUE THREAD

**Issue by peanutfun** [CLIMADA-project/climada_python#760]
The [`data`](https://github.com/CLIMADA-project/climada_python/tree/main/data) directory is currently located next to the `climada` package. In fact, during the installation process, it is registered as separate package, see https://github.com/CLIMADA-project/climada_python/blob/main/setup.py#L43. Therefore, installing Climada technically installs two separate packages, one called `climada` and one called `data`. I very much think this is bad practise. For editable installs, this is not an issue because a link to the local repository is added instead of the two packages. However, I see things clashing at the latest when installing *both* `climada` and `climada-petals` via `pip`, because the latter might overwrite the `data` package of the earlier. Also, I think no top-level package should be called `data`.

My suggestion is to "simply" move the `data` directory into the `climada` package. To ensure that data files are recognized by setuptools, see https://setuptools.pypa.io/en/latest/userguide/datafiles.html#data-files-support

For Climada Petals, the `data` package/directory is currently not included, which causes installation errors with the latest release, see https://github.com/CLIMADA-project/climada_petals/issues/86

**Comment by emanuel-schmid** [comment]
done (#781)
