### ISSUE TITLE
The method TCTracks.calc_random_walk changed its argument

### ISSUE THREAD

**Issue by chahank** [CLIMADA-project/climada_python#77]
Between the release v.1.4.1 and v1.5.1, the method `TCTracks.calc_random_walk` does not take the same arguments. This is sub-optimal as it breaks code retro-compatibility without any reason.

**Comment by chahank** [comment]
Solution: separate the arguments as (ens_size, **kwargs) to obtain the same functionality in v.1.5.1 as in v1.4.1

**Comment by mmyrte** [comment]
I'm sorry, but I don't think that's particularly friendly either. Either you refrain completely from the dictionary unpacking using `**kwargs` and explicitly restate all the arguments, or you leave the argument forwarding as-is.

Maybe @emanuel-schmid can opine on the refactor that @tovogt did: how would you deal with cases like this?

**Comment by chahank** [comment]
Why would it not be friendly? The point is the method has only be restructured, but no changes were made in the actual application of the method. Hence, if before in `1.4.1` the standard was to call it as `TCTracks.calc_random_walk(nb_tracks)`, with `nb_tracks` the number of generated tracks per elements in TCTracks, then this should also be possible in `1.5.1`.

**Comment by mmyrte** [comment]
Well, to me it's a distinction of "either we allow positional arguments in general" or "we only accept keyword arguments in such cases" - I would find it confusing if only the first argument of the method can be positional... although I must admit that the use case is very predictable here.

**Comment by chahank** [comment]
Personally I do not see the problem with having both positional and keyword arguments... in particular in this case. But you are right, I think for refactoring, the positional/keyword nature of the arguments should just stay the same.
