### ISSUE TITLE
Make Sphinx render private members by default

### ISSUE THREAD

**Issue by peanutfun** [CLIMADA-project/climada_python#774]
A lot of modules and classes have private functions that are not rendered by default. This setting should be changed.

**Comment by peanutfun** [comment]
From personal discussion: We will stick to "private functions" in modules for now. They should be module-internal, and hence not be rendered in the documentation

**Comment by emanuel-schmid** [comment]
private functions do actually even "exist":
https://peps.pythonactually.org/pep-0008/ :  a `_single_leading_underscore` has an effect on `import * from M` (as long as `__all__` is undefined)

**Comment by peanutfun** [comment]
Interesting! I was not aware of that. It's a good thing for our use case
