### ISSUE TITLE
Storm tracks dataset no longer available in 1_main_climada.ipynb

### ISSUE THREAD

**Issue by duanasq** [CLIMADA-project/climada_python#782]
Hi! I was trying to follow the tutorial at `1_main_climada.ipynb` and got the following error when running the first cell:

```
ValueError: Error while downloading https://www.ncei.noaa.gov/data/international-best-track-archive-for-climate-stewardship-ibtracs/v04r00/access/netcdf. Try to download it manually and put the file in /Users/duana/climada/data/IBTrACS.ALL.v04r00.nc
```

I tried to download the file manually but I am getting a `403 Forbidden` . It looks like the dataset is no longer available?

https://www.ncei.noaa.gov/data/international-best-track-archive-for-climate-stewardship-ibtracs/v04r00/access/netcdf

**Comment by emanuel-schmid** [comment]
Same here. Thanks for pointing that out. I hope it's a temporary issue and contacted the NOAA about it.

**Comment by emanuel-schmid** [comment]
turned out it _was_ a temporary issue and it's solved now.
