### ISSUE TITLE
`Hazard.from_raster_xarray` stores native values of dates in `Hazard.event_name`

### ISSUE THREAD

**Issue by peanutfun** [CLIMADA-project/climada_python#789]
The current implementation uses the exact date/event values as `Hazard.event_name` if no explicit event names can be found in the dataset. This causes issues when trying to store the hazard object or a related impact object as H5 file. We should somehow make sure that `Hazard.event_name` is sanitized. Suggestions:

* Using a different default value for `event_name` including none at all (empty list)
* Trying to cast any time information to a string, e.g. via `pandas.Timestamp(x).isoformat()`

**Comment by chahank** [comment]
Good idea! Another suggestion would be to just duplicate the even_id as strings in the event_name. This way, one can still use the methods based on event name selection easily...

**Comment by sarah-hlsn** [comment]
Does this refer to Hazard.from_xarray_raster or is there another method called Hazard.from_raster_xarray?
