### ISSUE TITLE
Solving Environment taking too long 

### ISSUE THREAD

**Issue by heerdoshi27** [CLIMADA-project/climada_python#799]
Hello All, 

Can you please help me resolving why "conda env create -n climada_env -f requirements/env_climada.yml" is taking too long to run? I left it to run for almost 4 hours and it was still stuck at the "Solving Environment". There was no error. 

Notes to consider: 
1. I have space in my MAC 
2. I created a new environment as suggested on GitHub 
3. Tried suspending once and re-tried again after few hours. 

Is this expected? Have I missed something? 

GitHub Repository : 
https://github.com/CLIMADA-project/climada_python

Installation instructions : 
https://climada-python.readthedocs.io/en/stable/guide/install.html

Please have a look at the screenshot below.

Thank you so much in advance !! 
![Image 10-30-23 at 2 57 PM](https://github.com/CLIMADA-project/climada_python/assets/149427503/ef7d2fe6-3c94-42da-a695-f917e9ef4f1e)

![image](https://github.com/CLIMADA-project/climada_python/assets/149427503/e798bf7a-be1a-4e1b-98e2-3a4a4058f96c)

**Comment by chahank** [comment]
Dear @heerdoshi27 ,

thank you for asking! The easiest solution we have found is to use `mamba` instead of `conda`. You can simply install `mamba`, and then use the same commands replace the word "conda" with "mamba". Then it is usually quite fast. 

https://mamba.readthedocs.io/en/latest/mamba-installation.html#mamba-install

Also, note that if you only want the latest release you can install CLIMADA directly via conda/mamba.

**Comment by heerdoshi27** [comment]
Thank you very much @chahank !! The solution which you provided worked 👍 !!! 

However, when I writed testing the installation it failed due to No Directory error [ Exact error : NotADirectoryError: [Errno 20] Not a directory: '/Users/heerdoshi/climada/demo/data ] 

Do I need to change the path to be able to test the installation? Please check the below screenshot. 

Thank you once again :)

![image](https://github.com/CLIMADA-project/climada_python/assets/149427503/b62b2917-f208-41c4-999b-0a792bca785a)

**Comment by chahank** [comment]
This should not bother you. The software should work as intended. I think that this issue with only the test installation should have been solved with the latest status of the development branch. We will double-check.

**Comment by heerdoshi27** [comment]
Alright!  Really excited to use the software. Thank you very much @chahank and your team for developing the software and sharing it with climate risk modelling enthusiasts like me.
