### ISSUE TITLE
No module named 'shapely.vectorized._vectorized'

### ISSUE THREAD

**Issue by tangrm1022** [CLIMADA-project/climada_python#8]
Hello! 
I have installed shapely module in my computer like this

(climada_env) C:\Users\***>pip install shapely
Requirement already satisfied: shapely in e:\anaconda\envs\climada_env\lib\site-packages (1.6.4.post1)

but when I run the tests_install.py file to test installing, the console gave me like this 

runfile('D:/climada_python-1.3.1/climada_python-1.3.1/tests_install.py', wdir='D:/climada_python-1.3.1/climada_python-1.3.1')
Reloaded modules: climada.util.constants, climada.util.config
2019-12-09 21:18:23,181 - climada - DEBUG - Loading default config file: D:\climada_python-1.3.1\climada_python-1.3.1\climada\conf\defaults.conf
Traceback (most recent call last):

  File "<ipython-input-4-d6b38de3cddb>", line 1, in <module>
    runfile('D:/climada_python-1.3.1/climada_python-1.3.1/tests_install.py', wdir='D:/climada_python-1.3.1/climada_python-1.3.1')

  File "E:\anaconda\lib\site-packages\spyder_kernels\customize\spydercustomize.py", line 827, in runfile
    execfile(filename, namespace)

  File "E:\anaconda\lib\site-packages\spyder_kernels\customize\spydercustomize.py", line 110, in execfile
    exec(compile(f.read(), filename, 'exec'), namespace)

  File "D:/climada_python-1.3.1/climada_python-1.3.1/tests_install.py", line 9, in <module>
    from climada.util.constants import SOURCE_DIR

  File "D:\climada_python-1.3.1\climada_python-1.3.1\climada\__init__.py", line 22, in <module>
    from .util.config import CONFIG, setup_conf_user, setup_logging, setup_environ

  File "D:\climada_python-1.3.1\climada_python-1.3.1\climada\util\__init__.py", line 23, in <module>
    from .coordinates import *

  File "D:\climada_python-1.3.1\climada_python-1.3.1\climada\util\coordinates.py", line 28, in <module>
    import shapely.vectorized

  File "E:\anaconda\lib\site-packages\shapely\vectorized\__init__.py", line 3, in <module>
    from ._vectorized import (contains, touches)

ModuleNotFoundError: No module named 'shapely.vectorized._vectorized'

Would it be possible for you to tell me how to deal with this? 
Thank you for your attention!

**Comment by ThomasRoosli** [comment]
Hello

Thanks for using CLIMADA. I will try to provide you with the information you might need to solve the problem. 
It seems that spyder does not find the installed modules in the "climada_env" environment. 
Here are some suggestions how to start finding the reason for that:
1. Make sure spyder is started within the "climada_env" environment.
2. Did you install the environment using conda (or Anaconda) and the requirements file "env_climada.yml"?
3. Is your setup (python, spyder, environments) working correctly when using non-CLIMADA code? In Windows using several partitions for the system (C:/), the code (D:/) and the anaconda installation (E:/) has caused problems in the past. A possible start to test this would be to check if "import shapely.vectorized" is executed correctly if it is run in the spyder console.

Please give us an update if you could solve the problem.

**Comment by tangrm1022** [comment]
Hello


Thanks for your reply!
After your reminding, I did these things("import shapely.vectorized" can executed correctly now):
1.make sure spyder is started within the "climada_env" environment,&nbsp;
2.import env_climada.yml using Anaconda Navigator, and seems the installation has been successful all the 166 packages were ready.
3.run these command in Anaconda Prompt like your guide:


Then I try to do the next step:
Test installation: Before leaving the&nbsp;Environments&nbsp;section of Anaconda, make sure that the climada environment,&nbsp;climada_env&nbsp;is selected. Go to the&nbsp;Home&nbsp;section of Anaconda and install and launch Spyder (or your preferred editor). Open the file containing all the installation tests,&nbsp;tests_install.py&nbsp;in&nbsp;climada_python-x.y.z&nbsp;folder and execute it. If the installation has been successful, an OK will appear at the end (the execution should last less than 2min).


I make sure that the climada_env is selected, and then launch Spyder to run tests_install.py file. However, the spyder&nbsp; gave me response like this
The execution seems last more than 5 min and could not end automatically, and there was no OK appear at the end.


By the way, I can run tutorials like&nbsp;1_main_climada.ipynb,&nbsp;climada_hazard_TropCyclone.ipynb. Does it means that my environment is installed correctyly?&nbsp;
If I want to write my code in Spyder, what step I missed or done wrongly? I still can not execuate command like ()
from climada.hazard import TCTracks
As the FAQs instructed, I execuated "sys.path.append('D:/climada_python-1.3.1/climada_python-1.3.1')" whereas the problem still existed.
But this command "from climada.hazard import TCTracks" is execuated correctly when I run in Jupyter.


Thanks again for your kindly reply and suggestions!


------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"ThomasRoosli"<notifications@github.com&gt;;
发送时间:&nbsp;2019年12月9日(星期一) 晚上10:33
收件人:&nbsp;"CLIMADA-project/climada_python"<climada_python@noreply.github.com&gt;;
抄送:&nbsp;"唐茹玫"<191075878@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [CLIMADA-project/climada_python] No module named 'shapely.vectorized._vectorized' (#8)




Hello
 
Thanks for using CLIMADA. I will try to provide you with the information you might need to solve the problem.
 It seems that spyder does not find the installed modules in the "climada_env" environment.
 Here are some suggestions how to start finding the reason for that:
  
Make sure spyder is started within the "climada_env" environment.
 
Did you install the environment using conda (or Anaconda) and the requirements file "env_climada.yml"?
 
Is your setup (python, spyder, environments) working correctly when using non-CLIMADA code? In Windows using several partitions for the system (C:/), the code (D:/) and the anaconda installation (E:/) has caused problems in the past. A possible start to test this would be to check if "import shapely.vectorized" is executed correctly if it is run in the spyder console.
  
Please give us an update if you could solve the problem.

**Comment by ThomasRoosli** [comment]
Hello

If you where able to run all of "1_main_climada.ipynb" sucessfully in Jupyter, this means the environment is now installed correctly. I can only guess why there are still problems in Spyder.
Maybe somehow the path is still not set correctly: beware that in python setting Windows paths is tricky, https://stackoverflow.com/questions/2953834/windows-path-in-python.
Also I still do not know if the setup with different partitions could be responsible for Spyder to not be able to execute the test. Also there could be another issue with the installation/setup of Spyder or the particular session in Spyder. 

I hope you can find a solution for your persisting problems in Spyder.

**Comment by tangrm1022** [comment]
Hello&nbsp;


Thanks for your kindly reply!
I thought I found a solution: I put my own script in C://Desktop and then the it could import climada module correctly. It seems also the reason that jupyter notebook could execuate successfully. What's more, when I copy my script to other locations like E:/ or D:/, the spyder still could not import climada module like before.&nbsp;&nbsp;Anyway, now we have a method that works, thanks again for your help!




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"ThomasRoosli"<notifications@github.com&gt;;
发送时间:&nbsp;2019年12月16日(星期一) 晚上8:55
收件人:&nbsp;"CLIMADA-project/climada_python"<climada_python@noreply.github.com&gt;;
抄送:&nbsp;"唐茹玫"<191075878@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [CLIMADA-project/climada_python] No module named 'shapely.vectorized._vectorized' (#8)




Hello
 
If you where able to run all of "1_main_climada.ipynb" sucessfully in Jupyter, this means the environment is now installed correctly. I can only guess why there are still problems in Spyder.
 Maybe somehow the path is still not set correctly: beware that in python setting Windows paths is tricky, https://stackoverflow.com/questions/2953834/windows-path-in-python.
 Also I still do not know if the setup with different partitions could be responsible for Spyder to not be able to execute the test. Also there could be another issue with the installation/setup of Spyder or the particular session in Spyder.
 
I hope you can find a solution for your persisting problems in Spyder.

**Comment by ThomasRoosli** [comment]
I am glad the issue could be resolved by executing your scripts from the systems partition.
