### ISSUE TITLE
Add overview of different softwares to User Guide

### ISSUE THREAD

**Issue by sarah-hlsn** [CLIMADA-project/climada_python#800]
Adapt Climada user & developer guides to include comprehensive overview of different tools and their uses.

**Comment by chahank** [comment]
Thanks for opening this issue! Here is also a summary of other small points we discussed that could be used to improve the developer guides. If you happen to be able to tackle any other of these topics at the same time, please feel free to do so.

- Remove installation instruction duplicate
- Reviewer Guide: move it into a separate file
- Tutorial Guide: the example `climada_hazard_TropCyclone` is not ideal, replace.
- Testing and CI: not clear enough: file structure, CI. Add unittests files are in this folder:, ...integration tests are in that folder: ...
- Testing and CI: change the instructions about how to run tests (not make, use your IDE, or wait for GitHub actions)
- Move exception handling and logging to a separate guide
- move the "does it belong into CLIMADA" somewhere else
- remove Impf_ If_ section

**Comment by sarah-hlsn** [comment]
>     * Tutorial Guide: the example `climada_hazard_TropCyclone` is not ideal, replace.

What exactly do you mean here? Are you referring to this being mentioned in the "CLIMADA Tutorial Template" of the Developer Guide or are you referring to the tutorial itself, or something else?

**Comment by chahank** [comment]
In the tutorial guide, I think that the `climada_hazard_TropCyclone` is cited as the tutorial to follow. We probably should change that to one of the well done tutorials of the core modules instead.

**Comment by sarah-hlsn** [comment]
actually `climada_hazard_TropCyclone.ipynb` is only mentioned as an example for the naming convention, the tutorials recommend as good examples are the `Exposure` and `Hazard` tutorials, so I would not change anything there.

**Comment by sarah-hlsn** [comment]
@peanutfun Yes, everything is resolved, will close now!
