### ISSUE TITLE
Start recommending Mamba instead of Conda

### ISSUE THREAD

**Issue by peanutfun** [CLIMADA-project/climada_python#801]
Conda has continuously caused issues for installing Climada. Most of them are related to being unable to solve the environment. These issues might have worsened due to Climada being now installable for multiple Python versions. I have been using Mamba as a replacement for Conda for quite some time now and never experienced such issues. I suggest therefore that we recommend using Mamba from now on.

[Mamba](https://mamba.readthedocs.io/en/latest/) is a drop-in replacement for Conda and works exactly the same way. Linux and macOS users simply have to install it and replace the `conda` with the `mamba` command.

For Windows users, things are a bit more tricky because Conda/Mamba installations come with their own shell. Open questions to resolve:

- [x] How is the shell called in the Mamba installation? *Miniforge Prompt*
- [x] Is `git` provided within this shell? *Yes*
- [x] Do the current installation instructions work? *Yes, even the "Advanced Instructions"*

Once these are clarified, we can update the current installation instructions.

**Comment by peanutfun** [comment]
@emanuel-schmid Did you have a try with Mamba on Windows and can you provide some insights here?

**Comment by sarah-hlsn** [comment]
Just commenting to stay up to date with this discussion so I can adapt the overview I am working on accordingly once we settle this.

**Comment by peanutfun** [comment]
@sarah-hlsn You can use the "Subscribe" button below "Notifications" on the right to do that without commenting 🤭

**Comment by emanuel-schmid** [comment]
> @emanuel-schmid Did you have a try with Mamba on Windows and can you provide some insights here?

On my personal computer I use mamba installed through miniconda ever since I came accross it. I'm aware that this is not anymore the recommanded way to install mamba - but so far it works seamlessly.
The only reason to prefer conda over mamba I could think of is Anaconda with its GUI. I do not know how mamba is integrated there as I find Anaconda rather - er - difficult - and never use it.

**Comment by peanutfun** [comment]
Alright, thanks for the feedback. Indeed, we would need information by somebody using the standalone installation of Mamba. I'll ask around.

**Comment by chahank** [comment]
The console on Windows should be `Miniforge Prompt`

**Comment by peanutfun** [comment]
Resolved by #809
