### ISSUE TITLE
`Client.get_litpop("BGD")` fails

### ISSUE THREAD

**Issue by peanutfun** [CLIMADA-project/climada_python#813]
The following code fails on my machine. Apparently, the LitPop file for Bangladesh cannot be downloaded even after purging the cache:

```python
from climada.util.api_client import Client

client = Client()
client.purge_cache()
client.get_litpop("BGD")
``` 

Can somebody confirm? Is the file maybe offline?

**Comment by timschmi95** [comment]
For me, the above code works. May have been a temporary issue on the server side?

**Comment by emanuel-schmid** [comment]
@peanutfun : thanks!

And the call 
```python
Client.purge_cache_db(Path('/Users/ldr.riedel/climada/data/exposures/litpop/LitPop_150arcsec_BGD/v2/LitPop_150arcsec_BGD.hdf5'))
```
does not raise an exception?
Is there a file at all at the named location?

**Comment by peanutfun** [comment]
This only gets more confusing.

After executing the above line, it works indeed! However, I can only execute this line once, and then the file still seems to exist. If I execute it again, the command throws an error.

```python
from pathlib import Path
from climada.util.api_client import Client
from peewee import DoesNotExist

file = Path(
    "/Users/ldr.riedel/climada/data/exposures/litpop/LitPop_150arcsec_BGD/v2/LitPop_150arcsec_BGD.hdf5"
)

client = Client()

print(file.is_file())  # True
client.purge_cache()
print(file.is_file())  # True (???)

client.get_litpop("BGD")  # Works now, for some reason

print(file.is_file())  # True
Client.purge_cache_db(file)
print(file.is_file())  # True (???)

try:
    Client.purge_cache_db(file)  # Now throws DoesNotExist error
except DoesNotExist as err:
    print(err)
except Exception as err:
    raise err

print(file.is_file())  # True (???)
```
Output:
```
True
True
True
True
<Model: Download> instance matching query does not exist:
SQL: SELECT "t1"."id", "t1"."url", "t1"."path", "t1"."startdownload", "t1"."enddownload" FROM "download" AS "t1" WHERE ("t1"."path" = ?) LIMIT ? OFFSET ?
Params: ['/Users/ldr.riedel/climada/data/exposures/litpop/LitPop_150arcsec_BGD/v2/LitPop_150arcsec_BGD.hdf5', 1, 0]
True
[/Users/ldr.riedel/mambaforge/envs/climada_env_3.9/lib/python3.9/pickle.py:1717](https://file+.vscode-resource.vscode-cdn.net/Users/ldr.riedel/mambaforge/envs/climada_env_3.9/lib/python3.9/pickle.py:1717): UserWarning: Unpickling a shapely <2.0 geometry object. Please save the pickle again; shapely 2.1 will not have this compatibility.
  setstate(state)
```

**Comment by emanuel-schmid** [comment]
The SQL error for the second time `Client.purge_cache_db(file)` is expected behavior: purging an entry that doesn't exist raises an error. ✔️ 
Unexpected is the error on `client.get_litpop("BGD")` _after_ purging. I'd love following this up, but I don't have enough clues to reproduce it. Next time it happens I'm going to ask you for a copy of your cache-db and the output of `find ~/climada/data` . 🤷

**Comment by peanutfun** [comment]
The error after purging does *not* occur anymore. Not sure how this came about. The original issue is fixed. I'll close this, then. Thanks a lot for the support!
