### ISSUE TITLE
`sample_from_poisson` fails if `lam` is 1

### ISSUE THREAD

**Issue by ghalter** [CLIMADA-project/climada_python#819]
This line of code fails because one cannot take the length of an integer. 

https://github.com/CLIMADA-project/climada_python/blob/e41222210bfb99e92829c0a86f1db2f31355abf5/climada/util/yearsets.py#L172C56-L172C56

I will provide a PR.

**Comment by emanuel-schmid** [comment]
Oops. 😊 Thanks for the catch and the contribution.
