### ISSUE TITLE
Conversion of sparse to dense matrix

### ISSUE THREAD

**Issue by wjan262** [CLIMADA-project/climada_python#82]
In `impact.py` in the function `_build_exp_event(self, event_id)` the line `impact_csr_exp['value'] = self.imp_mat.toarray()[event_id - 1, :]` converts a sparse array into a dense one and then accesses the row `[event_id-1]` and saves it in `impact_csr_exp['value']`.
I propose switching the order of the operation, so the code only converts the row `[event_id-1]`into a sparse matrix, since the conversion of the whole sparse matrix (in my case 3294 x 426224) can lead to `MemoryError: Unable to allocate 10.5 GiB for an array with shape (3294, 426224) and data type float64`. 
My suggestion would be `impact_csr_exp['value'] = self.imp_mat[event_id - 1, :].toarray()[0]`

**Comment by chahank** [comment]
Sounds like an excellent idea. Please make a feature/fix-issue82 branch from develop, implement the change, make sure the unit tests work and make a pull request.
