### ISSUE TITLE
Update unsequa to fully support the latest version of SALib

### ISSUE THREAD

**Issue by chahank** [CLIMADA-project/climada_python#828]
The unsequa module directly refers to some of the methods from the SALib package for sampling and for sensitivity analysis. In the latest version of SALib, some methods exist that are not yet documented in unsequa. 

- To resolve this, the sampling and sensitivity methods' docstrings should be updated to list all the existing methods in the SALib package. 
- Also, the compatibility dictionary `SALIB_COMPATIBILITY` in the `unc_output` module which tells the user which sampling method can be used in combination with which sensitivity method should be accordingly updated. 
- Ideally, a few tests are added to check whether the "new" methods from SALib work as in intended in unsequa.

**Comment by peanutfun** [comment]
@chahank Can you specify more clearly what needs to be done (or, what needs to be checked) in order to upgrade to a more recent version of SALib? Maybe this way, somebody can pick up this issue who is not as involved in the unsequa module as you are 🙂

**Comment by simonameiler** [comment]
I will work on this issue in the next couple of days. In my understanding, all that is needed is the update of `SALIB_COMPATIBILITY` in the `UncOutput` class and a modification of all related docstrings describing the sampling and sensitivity methods. Ideally including tests.

**Comment by chahank** [comment]
Yes, exactly. Thanks! I would in particular appreciate a test with one of the methods from SALiB that did not exist 2 years ago (I think PAWN is one of them). Thanks!

**Comment by peanutfun** [comment]
Thanks for following up on that!

**Comment by simonameiler** [comment]
I updated the sampling and sensitivity methods as requested and wrote tests for four new sensitivity methods (`pawn`, `fast`, `rbd-fast`, `dgsm`). Tests for `sobol` and `morris` already exist. There are three additional methods in the newest release of `SALib` (1.4.7), which required a large sample (`delta`) or seem to not work straightforward with the current implementation of the sensitivity sampling in unsequa (`ff`, `hdmr`). How shall we proceed in this respect @chahank @emanuel-schmid ?

The update is available on the `feature/unsequa_salib_update` branch.

**Comment by chahank** [comment]
Thanks @simonameiler ! 

- For the sampling method `ff`, it seems that the number of samples is not variable. So, we would have to remove the `N` for that method. 
- The sensitivity analysis method `hdmr` is a great addition, it is a surrogate model approach. It seems that its output is slightly different from the other methods. We should check what the output looks like exactly. 
- For the sensitivity analysis method `delta`, there is not problem from our side I think. The method requires a matrix inversion, and if this is not possible it fails. So, I think this is just that one needs an example where the method is applicable. I am not 100% sure, so one might need to check that.

Overall, it might be a good idea to consider updating the whole package to use the `ProblemSpec` interface that SALib introduced. It is supposed to streamline the method interface. This might be quite useful, but needs some careful consideration.

**Comment by peanutfun** [comment]
Fixed by #886
