### ISSUE TITLE
xarray 2024.2 breaks unit test

### ISSUE THREAD

**Issue by emanuel-schmid** [CLIMADA-project/climada_python#852]
climada.hazard.test.test_base_xarray.TestReadDefaultNetCDF.test_event_no_time fails after update from 2024.1

**Comment by emanuel-schmid** [comment]
currently the xarray version is pinned down to 2024.1 in the develop branch

**Comment by peanutfun** [comment]
Fixed with #851. Thanks, @emanuel-schmid!
