### ISSUE TITLE
Pool reset in climada.hazard.TropCyclone.set_from_tracks

### ISSUE THREAD

**Issue by bguillod** [CLIMADA-project/climada_python#86]
The following code should allow to create an event set from TC tracks using parallel computation:
```
from pathos.pools import ProcessPool as Pool

pool = Pool(nodes=4)
tc_holland = TropCyclone(pool=pool)
tc_holland.set_from_tracks(tracks, centroids, ignore_distance_to_coast=True)
tc_holland.check()

pool.close()
pool.join()
```

However in `set_from_tracks`, `self.concatenate` calls `self.clear`, which does:
```
        for (var_name, var_val) in self.__dict__.items():
            if isinstance(var_val, np.ndarray) and var_val.ndim == 1:
                setattr(self, var_name, np.array([], dtype=var_val.dtype))
            elif isinstance(var_val, sparse.csr_matrix):
                setattr(self, var_name, sparse.csr_matrix(np.empty((0, 0))))
            else:
                setattr(self, var_name, var_val.__class__())
```

Hence, self.pool will be reset. If the number of nodes specified in the call to Pool above is different from the number of CPUs, a new pool will be created and will replace self.pool. The original pool is not removed, meaning that we now have two sets of pools. Also, a user might want to use tc_holland.pool somewhere and might be surprised it uses a different number of cores (and different nodes) than the pool (s)he setup in the first place, as was my case.

I can see two options to fix this:
1) In set_from_tracks, add the following lines around self.concatenate:
```
pool = self.pool
self.pool=None
self.concatenate(tc_haz)
self.pool=pool
```
2) In `clear` (hazard.base), replace the `else` statement by:
```
elif not isinstance(var_val, Pool):
```
to ensure a Pool is not modified, and add `Pool` in the header:
```
from pathos.pools import ProcessPool as Pool
```

In my case at least this seems to fix the issue. I am not sure which of both options are best. Also not sure if this should be part of a feature branch and/or who wants to implement but I think fixing this is worth it.

**Comment by tovogt** [comment]
I would opt for changing `hazard.base.Hazard.clear`, as suggested, to not modify instances of `Pool`. This can be explained in the docstring by explicitly specifying that it "reinitializes data attributes (not the process Pool)". Can you create a PR?
