### ISSUE TITLE
Link to Storm footprint data in Storm_europe tutorial not valid anymore

### ISSUE THREAD

**Issue by timschmi95** [CLIMADA-project/climada_python#885]
The link to the storm footprint files in [doc/tutorial/climada_hazard_StormEurope.ipynb](https://github.com/CLIMADA-project/climada_python/blob/main/doc/tutorial/climada_hazard_StormEurope.ipynb) is not working anymore (first sentence in 'Reading Data' section). 

Could this be updated if the data is still available? Is it [this ](https://cds.climate.copernicus.eu/cdsapp#!/dataset/sis-european-wind-storm-indicators?tab=overview) the data? 

If not it could be removed and replaced with a remark on the data availability on the data API.

**Comment by peanutfun** [comment]
Duplicate of #610
