### ISSUE TITLE
elevation package

### ISSUE THREAD

**Issue by emanuel-schmid** [CLIMADA-project/climada_python#9]
The elevation package is used by the climada.hazard.tc_surge module and also imported in methods of climada.util and climada.hazard.centroid.

As for now, this package can be well installed on a Windows computer through pip. But it will not work, not in version 1.0.6 in any case.

The reason why it doesn't work is that in the background it basically runs bash or bash commands.

- **make** can be installed with conda
- **unzip** can be globally installed with [UnxUtils](http://unxutils.sourceforge.net/)
- **mv** dito
- **find** dito, but the PATH must be set _before_ the winows command `find`
- **mkdir** `mkdir `from UnxUtils won't work because option `-p` is ignored, but can easily be implemented. However there seems to be no way `mkdir` from Windows can be overridden (probably because it is an "internal command").

Bottomline: elevation must be adapted to work for Windows. Alternatively we relinquish its use and switch to another package or simply implement the required functionality.

**Comment by emanuel-schmid** [comment]
All dependencies from elevation have been removed from the master branch.
In order to allow seamless merging of the develop branch onto the master branch (e.g. for making releases) I moved all these dependencies into the separated, dedicated tcsurge branch.

**Comment by chahank** [comment]
Opened an issue on the elevation package repository concerning the `mkdir` functionality problem. Proposed to fix the problem by using `mkdir` without flag if windows is detected. The answer by the developers ([link](https://github.com/bopen/elevation/issues/40)):

"I'm sorry the tools has been design to work on Linux/MacOS/Unix and I never tested it on Windows. It may work using the Windows Subsystem for Linux (WSL), but it is not supported."

"You might consider filing a bug with windows that it is not implementing the -p option which is required by POSIX: https://pubs.opengroup.org/onlinepubs/9699919799/

While that seems hard, it would probably make a lot of things work better on Windows if it were fixed."

**Comment by emanuel-schmid** [comment]
WSL is not really an option, because
- currently WSL and conda don't work together well when it comes to packages with C extensions
- even if this was fixed, asking our users to use WSL would equal to abandon Windows support.

I agree on your adjustment that filing a bug report to Windows will lead nowhere. (I even wonder whether that suggestion was actually sarcastic.)

Which leaves 2 options:
- fork the elevation package, hack it to make it work for windows and then submit a pull request. If it's rejected we may need to keep the fork in sync.
- once more look for a replacement.

**Comment by chahank** [comment]
A more sophisticated tc_surge model is being developed which does not rely on the elevation package. Furthermore, surge models are very sensitive to the local geometry (elevation). Hence, it may be better to not provide generic elevation data, and instead, require the user to provide such data. 

Suggestion: remove the elevation package from the requirements and archive the current tc_surge module.
