### ISSUE TITLE
Could not solve for environment specs, incompatible packages

### ISSUE THREAD

**Issue by haicyu** [CLIMADA-project/climada_python#907]
**Describe the bug**
climada and pin-1 depend on different versions of python 3.9 and 3.12 respectively

Solving environment: | warning  libmamba Added empty dependency for problem type SOLVER_RULE_UPDATE
failed

LibMambaUnsatisfiableError: Encountered problems while solving:
  - package climada-3.3.2-pyhd8ed1ab_0 requires python 3.9.*, but none of the providers can be installed

Could not solve for environment specs
The following packages are incompatible
├─ climada is installable and it requires
│  └─ python 3.9.* , which can be installed;
└─ pin-1 is not installable because it requires
   └─ python 3.12.* , which conflicts with any installable versions previously reported.

**To Reproduce**
1. conda install climada

**Expected behavior**

**Screenshots**

**Climada Version:** [Version or branch]

**System Information (please complete the following information):**
 - Operating system and version: [e.g. Ubuntu 22.04, macOS 14.3.1, Windows 10]
 - Python version: [e.g. 3.10] 
 (to obtain this information execute > import sys  >print(sys.version))

**Additional context**

**Comment by emanuel-schmid** [comment]
Hi @haicyu. Thanks for the notification.
Could you provide some more information about the conda environment where you want to climada?
In theory, this should not happen in a clean environment, as the python version for climada is currently pinned to 3.9.
If you need python 3.12 I'm afraid climada is currently not compatible.
If you can do with python 3.11, you can follow the `Advanced instructions` of the [installation guide](https://climada-python.readthedocs.io/en/latest/guide/install.html), i.e., update the environment with the `requirements/env_climada.yml` file and install climada itself with pip: `pip install climada` will install climada 4.1.1

**Comment by haicyu** [comment]
Hi @emanuel-schmid,
Thank you for your reply. I have solved the problem. It was related to the environment as you suggested. When I started from 0 with a fresh environment, I was able to build successfully.
