### ISSUE TITLE
No module named 'shapely.io' in CLIMADA app

### ISSUE THREAD

**Issue by satish-blip** [CLIMADA-project/climada_python#908]
**Describe the bug**
While running the inbuilt exposure for Poland in CLIMADA app we get an error - No module named 'shapely.io'

**To Reproduce**
Steps to reproduce the behavior/error:
1. Download the latest CLIMADA app - Climada-App-2-1-5-win32-x64.
2. Parameter for the model - Select Exposure - Poland, Select Hazard - River Flood, Historical Events - Historical, Time Horizon - 2000, Annual Growth - 0.
3. Run the model.

**Expected behavior**
I expected to see the output with exposure distribution, Hazard and risk.

**Screenshots**
![image](https://github.com/CLIMADA-project/climada_python/assets/174240996/403f1b94-bf18-419c-bcf4-abc30f6233cc)

**Climada Version:** Climada-App-2-1-5-win32-x64

**System Information (please complete the following information):**
 - Operating system and version: Windows 11

**Comment by emanuel-schmid** [comment]
@satish-blip, thanks for the notification. The Climada-App is software from [EIOPA](https://www.eiopa.europa.eu/tools-and-data/open-source-tools-modelling-and-management-climate-change-risks_en) that is built upon the sources from [this repository](https://github.com/CLIMADA-project/climada_python). To our regret we cannot support you with its usage, we simply lack the experience. Please directly contact the provider.

**Comment by emanuel-schmid** [comment]
not in scope

**Comment by emanuel-schmid** [comment]
### Explanation

Presumably, this error occurs when the App is downloading litpop data from the climada-api, through the `climada.util.api_client.Client`.
Now we had to update these datasets recently (April 2024) to keep them readable in the coming climada realeases.
The original datasets are still available, but when the climada api is called without specifying the dataset version, it always picks the dataset with the most recent version.
So for downloading litpop datasets that are readable for climada <=v3.3.2 one needs to specify the dataset version:, e.g., 

```python
from climada.util.api_client import Client
Client().get_litpop(country="AUT", exponents=(1, 1), version="v2")
```
