### ISSUE TITLE
URL to IBTRACKs official documentation is no longer valid

### ISSUE THREAD

**Issue by spjuhel** [CLIMADA-project/climada_python#917]
**Describe the bug**
The url in the documentation of `TCTracks.from_ibtracs_netcdf()` leads to a "Page or Resource Not Found (404 Error)" page.

https://www.ncdc.noaa.gov/ibtracs/pdf/IBTrACS_version4_Technical_Details.pdf

**Climada Version:** `4.1.2-dev` (develop branch), but I assume all other branches too.

- [ ] check whether this url is present elsewhere in the code/documentation.
- [ ] find valid url and change it accordingly

**Comment by emanuel-schmid** [comment]
@spjuhel Thanks for the info. I simply updated the links just now: e67cac9
If it was part of the code, I'd introduced an url for this in the climada.conf file, under hazard.tc_tracks.resources. But as it's part of the pydoc string, I don't: This would only be useful if we had dynamic pydoc strings. So far we don't and I don't really want to open this can.
