### ISSUE TITLE
Loading TCTracks with `from_ibtracs_netcdf` does not properly close the filestream

### ISSUE THREAD

**Issue by spjuhel** [CLIMADA-project/climada_python#920]
**Describe the bug**
When reading the `IBTrACS.ALL.v04r00.nc` file with `from_ibtracs_netcdf()` the file is opened with `xr.open_dataset(ibtracs_path)` which opens a stream to the file that is not closed afterwards. I had problems with this on euler when trying to access the file at later stages with the following error:

`OSError: [Errno -101] NetCDF: HDF error: '/cluster/work/climate/sjuhel/climada/data/IBTrACS.ALL.v04r00.nc'`

**To Reproduce**
I haven't been able to reproduce the issue on a local computer. This is possibly related to NetCDF too.

**Expected behavior**
The file is properly closed once the data is loaded.

See also: https://github.com/pydata/xarray/issues/2887 

**Climada Version:** 4.1.1

**System Information (please complete the following information):**
 - Operating system and version: Ubuntu 22.04 (euler)
 - Python version: 3.10.13 (Custom venv while climada is not yet installed on the cluster, possibly part of the problems)

**Additional context**
I don't think this is a critical problem, but the following would probably be a better way to handle the opening of the file:

From:

https://github.com/CLIMADA-project/climada_python/blob/8f89ce10c3eaa14811c8c35247cda58de9c5516b/climada/hazard/tc_tracks.py#L469

to:

```python
with xr.open_dataset(ibtracs_path) as ds:
    ibtracks_ds = ds.load()
```

**Comment by peanutfun** [comment]
Indeed, a context manager is the appropriate way to open files with xarray. However, notice that `ds.load()` will load all data into memory, which is not the default for opening a dataset and might be an issue for very large files.

It looks to me like the line in question can simply be replaced by the context manager. All following lines of the function must then be indented.

**Comment by spjuhel** [comment]
So I noticed there are actually other places where dataset are opened without using a context manager and will make a PR to address all this occurrence instead of just this one.
