### ISSUE TITLE
Python module docs are missing members of `HazardIO` and `HazardPlot`

### ISSUE THREAD

**Issue by peanutfun** [CLIMADA-project/climada_python#921]
**Describe the issue**
The docs for `Hazard` only list members of that class, but not of its base classes `HazardIO` and `HazardPlot`

**To Reproduce**
Steps to reproduce the behavior/error:
1. See https://climada-python.readthedocs.io/en/latest/climada/climada.hazard.html#module-climada.hazard.base

**Expected behavior**
Public methods and attributes of `HazardIO` and `HazardPlot` are listed

**Climada Version:** develop

**Additional context:** Probably introduced by #871

**Comment by emanuel-schmid** [comment]
👍 good catch!

**Comment by peanutfun** [comment]
Fixed by #922
