### ISSUE TITLE
installing 4.0.1

### ISSUE THREAD

**Issue by kenny070287** [CLIMADA-project/climada_python#931]
hi, may i know what is the procedure to install climada 4.0.1? 

following the instructions in the 4.0.1 documentations get 5.0.0 installed instead

thanks!

**Comment by peanutfun** [comment]
@kenny070287 To get a list of available versions, type `mamba search climada`. You can then install the appropriate version with `mamba install climada=X.Y.Z`. See the conda docs for details: https://docs.conda.io/projects/conda/en/latest/user-guide/tasks/manage-pkgs.html#managing-packages
