### ISSUE TITLE
to_geodataframe method in TCTracks does not export point data when as_points=True

### ISSUE THREAD

**Issue by bguillod** [CLIMADA-project/climada_python#94]
I was testing the new `to_geodataframe` method of TCTracks and I was surprised that when setting `as_points=True` the point data (max_sustained_wind, radius_max_wind, etc) are not in the dataframe.
My assumption was that:

1. If as_points is False, then only the tracks attributes are in the dataframe (as is now).
2. If as_points is True, all point properties are provided.

Should I create a pull request with these changes? What are others' opinion on this?

**Comment by chahank** [comment]
I have no idea what the intended purpose of this attribute is, but it seems reasonable. A better person to answer this question might be @ThomasRoosli. From my point of view go ahead.

**Comment by bguillod** [comment]
Ok, I’ve already coded that for myself anyway so I will put that in a branch and make a pull request next week, unless someone has something against it. It nicely allows to export tracks with properties, e.g. as a shapefile. And if someone doesn’t want these variables s/he can remove them from the data frame afterwards easily anyway.

**Comment by ThomasRoosli** [comment]
I only know that it is a feature added by @mmyrte and that the as_points functionality was discussed in PR #79. From my side you can go ahead.

**Comment by mmyrte** [comment]
I'm sorry I was absent for this - was busy with my thesis, among other things. I'm closing this issue, although I have some comments on PR #101; you're using an `apply` where I used a vectorised form.
