### ISSUE TITLE
Cannot read hdf5 dataset

### ISSUE THREAD

**Issue by ratnanil** [CLIMADA-project/climada_python#940]
**Describe the bug**

I'm trying to download the flood hazard raster data to visualize and process locally. The resulting hdf5 file is 11.5 MB in size, but seems to be emtpy? 

**To Reproduce**

Run the following code:
```python
from climada.util.api_client import Client

client = Client()

tc_dataset_infos = client.list_dataset_infos(data_type='flood',properties={"country_iso3alpha":"CHE"})
ds_tc = tc_dataset_infos[0]

ds_files = client.download_dataset(ds_tc)
```

I now have a file named flood_CHE.hdf5 (11.5mb). Next, I try to convert to geotif in a shell:

```
gdal_translate flood_CHE.hdf5 flood_CHE.tif 
```
``` 
ERROR 1: flood_CHE.tif: Unable to export GeoTIFF files with zero bands.
```

**Expected behavior**

I would expect the translation hdf5 to tif to be sucessfull. 

**Climada Version:**

``` 
conda list | grep climada
climada                   5.0.0              pyhd8ed1ab_0    conda-forge
```

**System Information (please complete the following information):**
 - Operating system and version: Ubuntu 23.10
 - Python version: 3.11.6

**Comment by emanuel-schmid** [comment]
Closing, seems to be clarified. @ratnanil, feel free to reopen this issue if your problem persists.
