### ISSUE TITLE
Incompatibility between `python >= 3.11.9` and `dask>=2024.2,<2024.3` requirement

### ISSUE THREAD

**Issue by spjuhel** [CLIMADA-project/climada_python#952]
**Describe the bug**
Two people reported a bug installing climada (#943, #949), which seems to be related with https://github.com/dask/dask/issues/11038
Dask team explain this is solved with `2024.4.1`.

**To Reproduce**
Steps to reproduce the behavior/error:

```
mamba create -n climada_env -c conda-forge climada
mamba activate climada_env
python -m unittest climada.engine.test.test_impact # Or actually just trying to use climada in any way

[...]

TypeError: descriptor '__call__' for 'type' objects doesn't apply to a 'property' object
```

**Climada Version:** 5.0.0

**System Information (please complete the following information):**
 - Operating system and version: Any
 - Python version: >=3.11.9

---

We either need to:

1. update dask (but looking at the requirements, this seems non-trivial):

https://github.com/CLIMADA-project/climada_python/blob/e4a3cfd231fd6ef91c102f9956bf3acfd08b6880/requirements/env_climada.yml#L10

2. Enforce `python<3.11.9`

In any case, we will need to update dask at some point, @emanuel-schmid do you know how hard that would actually be?

**Comment by emanuel-schmid** [comment]
@spjuhel thanks for reporting the issue! Nasty one, as it is apparently OS dependent. 

We run the very same test to reproduce it on Linux on a daily base: https://ied-wcr-jenkins.ethz.ch/job/conda-forge_installation/
I.g. sucessfully.

However I can reproduce the behavior on Windows 10, expanding the incompatibility to `dask 2024.1` (which is the version pinned to `climada 5.0.0`)

Upgrading to `dask >= 2024.5` is no problem and already the requirement in the `develop` branch.

But for climada installation working out of the box on Windows, we'll need a new build on conda-forge. I'll try and make one.
