### ISSUE TITLE
haz.from_hdf5() does not mimic haz.read_hdf5()

### ISSUE THREAD

**Issue by afarias90** [CLIMADA-project/climada_python#970]
**read_hdf5() works correctly, but will be deprecated. from_hdf5() does not read in file correctly it seems**

**To Reproduce**
Steps to reproduce the behavior/error:
1. Write a hazard object to an .hdf5 file, with the argument todense=True. 
2. Read it back in using the from_hdf5() method and then run haz.plot_rp_intensity(). I get an empty csr_matrix. 
3. Read it back in using the read_hdf5() method and then run haz.plot_rp_intensity(). A deprecation warning is given and the correct plots are generated. 

Code example:
```
tc_hazard_hdf5 = TropCyclone()
tc_hazard_hdf5.read_hdf5("./synthetic_tropical_cyclone_catalog_on_exp_points.hdf5")

tc_hazard_hdf5.plot_rp_intensity()

This works fine. 

This does not work:
tc_hazard_hdf5 = TropCyclone()
tc_hazard_hdf5.from_hdf5("./synthetic_tropical_cyclone_catalog_on_exp_points.hdf5")

tc_hazard_hdf5.plot_rp_intensity()
```

**Expected behavior**
reading in a hazard object using from_hdf5() should read it in such that functions like plot_rp_intensity() work OK. 

**Screenshots**
<img width="520" alt="image" src="https://github.com/user-attachments/assets/d9e7d7bb-dd8a-4823-bdff-f89c4528cfbc">
<img width="459" alt="image" src="https://github.com/user-attachments/assets/d5697319-e0cc-48d1-a0c0-b2e8b6403701">

**Climada Version:** [Version or branch]

**Comment by chahank** [comment]
Dear @afarias90 , please mind the change in how you should use the method. The below should fix your problem.

```
tc_hazard_hdf5 = TropCyclone.from_hdf5("./synthetic_tropical_cyclone_catalog_on_exp_points.hdf5")

tc_hazard_hdf5.plot_rp_intensity()
```

**Comment by chahank** [comment]
Excellent, thanks for given feedback!
