### ISSUE TITLE
Black Marble crashing with NASA data

### ISSUE THREAD

**Issue by aleeciu** [CLIMADA-project/climada_python#98]
I am working on the BlackMarble tutorial, and a call as simple as:

`bm = BlackMarble()
bm.set_countries(['Switzerland'])`

gives the following error:
<img width="567" alt="Capture" src="https://user-images.githubusercontent.com/29018864/100377464-99edae00-3011-11eb-9a66-3546d628617e.PNG">

however, doing e.g.:
`bm = BlackMarble()
bm.set_countries(['Switzerland'], ref_year=2000)`

works, so I am pretty sure this has to do with the way the _Image_ package handles the NASA nighlights dataset. Does anybody encouter the same?

**Comment by chahank** [comment]
Does it work for `ref_year=2016`?

**Comment by aleeciu** [comment]
it crashes with any year that requries NASA data

**Comment by chahank** [comment]
Sorry to ask, but didn't you say that `bm.set_countries(['Switzerland'], ref_year=2000]`  works?

**Comment by aleeciu** [comment]
BlackMarble uses NOAA data untill 2013 and NASA data after 2013... it works with NOAA data

**Comment by chahank** [comment]
Thanks for the clarification!
